In [1]:
!pip install selenium

Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Requirement already satisfied: urllib3 in c:\users\allen\anaconda3\lib\site-packages (from selenium) (1.25.8)
Installing collected packages: selenium
Successfully installed selenium-3.141.0

In [2]:
#importing all the required libraries
import selenium
import pandas as pd
from selenium import webdriver
from time import sleep
from selenium.common.exceptions import NoSuchElementException   # importing Exemption

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [104]:
driver=webdriver.Chrome(r"C:\Users\allen\Downloads\chromedriver_win32\chromedriver.exe")

In [106]:
driver=webdriver.Chrome("chromedriver.exe")

Q1: Write a python program to scrape data for “Data Analyst” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.

In [105]:
url='https://www.naukri.com/'
driver.get(url)

In [75]:
search_job=driver.find_element_by_id('qsb-keyword-sugg')
search_job #keyword search bar

In [76]:
search_job.send_keys("Data Analyst") #enter "Data Analyst" keyword search bar

In [77]:
search_loc=driver.find_element_by_id('qsb-location-sugg')
search_loc #location search bar

In [78]:
search_loc.send_keys("Bangalore") #enters 'Bangalore' in location search bar

In [79]:
search_btn=driver.find_element_by_xpath("//button[@class='btn']")
search_btn.click() #clicks on search button

In [80]:
job_title_tags=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")

In [81]:
job_title=[]
for i in job_title_tags:
    if len(job_title)<10:
        job_title.append(i.text)

job_title = pd.DataFrame(job_title)
job_title.columns=['Job_title']
job_title
#Job titles of first 10 jobs in Bangolore

                                                             Job_title
0  Data Scientist / Data Analyst -Business Analyst
1  Hiring Data Analysts For E commerce Platform || WFH
2  Data Analyst
3  Data Analyst
4  Hiring For Data Analyst/ MIS Reporting Analyst - Bangalore
5  DA - Urgent Opening For Data Analyst BFSI Domain - Pan India
6  Data Analyst - Informatica MDM
7  Data Analyst
8  Assistant Vice President - MIS & Reporting ( Business Data Analyst)
9  Data Analyst

In [82]:
job_location_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")

In [83]:
pd.set_option("display.max_colwidth", -1) #displays whole column value

In [84]:
job_location=[]
for i in job_location_tags:
    if len(job_location)<10:
        job_location.append(i.text)

job_location = pd.DataFrame(job_location)
job_location.columns=['Job_location']
job_location
#Job Locations of first 10 jobs in Bangolore

                                                                                                      Job_location
0  Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru
1  Bangalore/Bengaluru
2  Bangalore/Bengaluru
3  Bangalore/Bengaluru
4  Bangalore/Bengaluru
5  Kolkata, Hyderabad/Secunderabad, Pune, Ahmedabad, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)
6  Bangalore/Bengaluru
7  Bangalore/Bengaluru
8  Mumbai, Bangalore/Bengaluru
9  Bangalore/Bengaluru

In [85]:
company_name_tags=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")

In [86]:
company_name=[]
for i in company_name_tags:
    if len(company_name)<10:
        company_name.append(i.text)

company_name = pd.DataFrame(company_name)
company_name.columns=['Company_name']
company_name
#Company names of first 10 jobs in Bangolore

                                             Company_name
0  Inflexion Analytix Private Limited
1  Allegis Services India Pvt. Ltd.
2  Shell India Markets Private Limited
3  Applied Materials
4  PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd
5  Tata Consultancy Services Ltd.
6  Shell India Markets Private Limited
7  Shell India Markets Private Limited
8  INTERTRUSTVITEOS CORPORATE AND FUND SERVICES PVT. LTD.
9  Myntra Designs Pvt. Ltd.

In [87]:
experience_required_tags=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")

In [88]:
experience_required=[]
for i in experience_required_tags:
    if len(experience_required)<10:
        experience_required.append(i.text)

experience_required = pd.DataFrame(experience_required)
experience_required.columns=['Experience_required']
experience_required
#Experience required of first 10 jobs in Bangolore

  Experience_required
0  0-3 Yrs
1  0-5 Yrs
2  5-8 Yrs
3  7-10 Yrs
4  2-4 Yrs
5  4-9 Yrs
6  6-9 Yrs
7  5-8 Yrs
8  12-18 Yrs
9  3-6 Yrs

In [90]:
First10jobresults=pd.DataFrame({})
First10jobresults['Job_title']=job_title['Job_title']
First10jobresults['Job_location']=job_location['Job_location']
First10jobresults['Company_name']=company_name['Company_name']
First10jobresults['Experience_required']=experience_required['Experience_required']
First10jobresults
#first 10 job-title, job-location, company_name, experience_require for 'Data Analyst' Job position in bangalore

,Job_title,Job_location,Company_name,Experience_required
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru",Inflexion Analytix Private Limited,0-3 Yrs
1,Hiring Data Analysts For E commerce Platform || WFH,Bangalore/Bengaluru,Allegis Services India Pvt. Ltd.,0-5 Yrs
2,Data Analyst,Bangalore/Bengaluru,Shell India Markets Private Limited,5-8 Yrs
3,Data Analyst,Bangalore/Bengaluru,Applied Materials,7-10 Yrs
4,Hiring For Data Analyst/ MIS Reporting Analyst - Bangalore,Bangalore/Bengaluru,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs
5,DA - Urgent Opening For Data Analyst BFSI Domain - Pan India,"Kolkata, Hyderabad/Secunderabad, Pune, Ahmedabad, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)",Tata Consultancy Services Ltd.,4-9 Yrs
6,Data Analyst - Informatica MDM,Bangalore/Bengaluru,Shell India Markets Private Limited,6-9 Yrs
7,Data Analyst,Bangalore/Bengaluru,Shell India Markets Private Limited,5-8 Yrs
8,Assistant Vice President - MIS & Reporting ( Business Data Analyst),"Mumbai, Bangalore/Bengaluru",INTERTRUSTVITEOS CORPORATE AND FUND SERVICES PVT. LTD.,12-18 Yrs
9,Data Analyst,Bangalore/Bengaluru,Myntra Designs Pvt. Ltd.,3-6 Yrs

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the job-title, job-location, company_name, full job-description. You have to scrape first 10 jobs data.

In [46]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.naukri.com/'
driver.get(url)

In [47]:
search_job1=driver.find_element_by_id('qsb-keyword-sugg')
search_job1 # keyowrd search bar

In [48]:
search_job1.send_keys("Data Scientist") #enters'Data Scientist' in keyword search bar

In [49]:
search_loc1=driver.find_element_by_id('qsb-location-sugg')
search_loc1 # location search bar

In [50]:
search_loc1.send_keys("Bangalore") #enters'Bangalore' in location search bar

In [51]:
search_btn1=driver.find_element_by_xpath("//button[@class='btn']")
search_btn1.click() #clicks on search button

In [52]:
job_title_tags1=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")

In [53]:
job_title1=[]
for i in job_title_tags1:
    if len(job_title1)<10:
        job_title1.append(i.text)

job_title1 = pd.DataFrame(job_title1)
job_title1.columns=['Job_title']
job_title1
#Job titles of first 10 jobs in Bangolore

                                         Job_title
0  Data Scientist / Data Analyst -Business Analyst
1                  Senior Data Scientist, Modeling
2                      Data Scientist - IBM Garage
3                                   Data Scientist
4              Senior Data Scientist - Credit risk
5                        Big Data - Data Scientist
6                    Specialist I - Data Scientist
7                                   Data Scientist
8                              Lead Data Scientist
9                       SDE Lead Data Scientist-L3

In [54]:
job_location_tags1=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")

In [55]:
job_location1=[]
for i in job_location_tags1:
    if len(job_location1)<10:
        job_location1.append(i.text)

job_location1 = pd.DataFrame(job_location1)
job_location1.columns=['Job_location']
job_location1
#Job Locations of first 10 jobs in Bangolore

                                        Job_location
0  Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...
1  Kolkata, Gurgaon/Gurugram, Bangalore/Bengaluru...
2  Noida, Hyderabad/Secunderabad, Bangalore/Benga...
3  Noida, Hyderabad/Secunderabad, Bangalore/Benga...
4                                Bangalore/Bengaluru
5  Kochi/Cochin, Indore, Hyderabad/Secunderabad, ...
6                                Bangalore/Bengaluru
7                                Bangalore/Bengaluru
8                                Bangalore/Bengaluru
9                                Bangalore/Bengaluru

In [56]:
company_name_tags1=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")

In [57]:
company_name1=[]
for i in company_name_tags1:
    if len(company_name1)<10:
        company_name1.append(i.text)

company_name1 = pd.DataFrame(company_name1)
company_name1.columns=['Company_name']
company_name1
#Company names of first 10 jobs in Bangolore

                         Company_name
0  Inflexion Analytix Private Limited
1                             Nielsen
2              IBM India Pvt. Limited
3              IBM India Pvt. Limited
4                  Scienaptic Systems
5           Xoriant Solutions Pvt Ltd
6               Philips India Limited
7              IBM India Pvt. Limited
8      Intel Technology India Pvt Ltd
9   Huawei Technologies India Pvt Ltd

In [58]:
experience_required_tags1=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")

In [59]:
experience_required1=[]
for i in experience_required_tags1:
    if len(experience_required1)<10:
        experience_required1.append(i.text)

experience_required1 = pd.DataFrame(experience_required1)
experience_required1.columns=['Experience_required']
experience_required1
#Experience required of first 10 jobs in Bangolore

  Experience_required
0             0-3 Yrs
1             3-7 Yrs
2             5-8 Yrs
3             5-8 Yrs
4            5-10 Yrs
5             1-3 Yrs
6             4-7 Yrs
7             6-8 Yrs
8            6-10 Yrs
9             5-8 Yrs

In [60]:
First10jobresultsofdatascientist=pd.DataFrame({})
First10jobresultsofdatascientist['Job_title']=job_title1['Job_title']
First10jobresultsofdatascientist['Job_location']=job_location1['Job_location']
First10jobresultsofdatascientist['Company_name']=company_name1['Company_name']
First10jobresultsofdatascientist['Experience_required']=experience_required1['Experience_required']
First10jobresultsofdatascientist
#first 10 job-title, job-location, company_name, experience_require for 'Data scientist' Job position in bangalore

,Job_title,Job_location,Company_name,Experience_required
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,0-3 Yrs
1,"Senior Data Scientist, Modeling","Kolkata, Gurgaon/Gurugram, Bangalore/Bengaluru...",Nielsen,3-7 Yrs
2,Data Scientist - IBM Garage,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,5-8 Yrs
3,Data Scientist,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,5-8 Yrs
4,Senior Data Scientist - Credit risk,Bangalore/Bengaluru,Scienaptic Systems,5-10 Yrs
5,Big Data - Data Scientist,"Kochi/Cochin, Indore, Hyderabad/Secunderabad, ...",Xoriant Solutions Pvt Ltd,1-3 Yrs
6,Specialist I - Data Scientist,Bangalore/Bengaluru,Philips India Limited,4-7 Yrs
7,Data Scientist,Bangalore/Bengaluru,IBM India Pvt. Limited,6-8 Yrs
8,Lead Data Scientist,Bangalore/Bengaluru,Intel Technology India Pvt Ltd,6-10 Yrs
9,SDE Lead Data Scientist-L3,Bangalore/Bengaluru,Huawei Technologies India Pvt Ltd,5-8 Yrs

In [61]:
jobdesc=[] #scraping all urls of first 10 job's full description
for i in driver.find_elements_by_xpath("//div[@class='info fleft']/a"):
    if len(jobdesc)<10:
        jobdesc.append(i.get_attribute('href'))
jobdesc

['https://www.naukri.com/job-listings-data-scientist-data-analyst-business-analyst-inflexion-analytix-private-limited-mumbai-hyderabad-secunderabad-pune-gurgaon-gurugram-chennai-bangalore-bengaluru-0-to-3-years-100521000368?src=jobsearchDesk&sid=16213661800726183&xp=1&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-modeling-nielsen-kolkata-gurgaon-gurugram-bangalore-bengaluru-vadodara-baroda-mumbai-all-areas-3-to-7-years-280421003878?src=jobsearchDesk&sid=16213661800726183&xp=2&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-garage-ibm-india-pvt-limited-noida-hyderabad-secunderabad-bangalore-bengaluru-5-to-8-years-040521900448?src=jobsearchDesk&sid=16213661800726183&xp=3&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-noida-hyderabad-secunderabad-bangalore-bengaluru-5-to-8-years-030521900421?src=jobsearchDesk&sid=16213661800726183&xp=4&px=1',
 'https://www.naukri.com/job-listings-senior-data-scientist-credit-risk-scienaptic-systems-bangalore-bengaluru-5-to-10-years-030521500996?src=jobsearchDesk&sid=16213661800726183&xp=5&px=1',
 'https://www.naukri.com/job-listings-big-data-data-scientist-xoriant-solutions-pvt-ltd-kochi-cochin-indore-hyderabad-secunderabad-pune-ahmedabad-bangalore-bengaluru-mumbai-all-areas-1-to-3-years-130521005018?src=jobsearchDesk&sid=16213661800726183&xp=6&px=1',
 'https://www.naukri.com/job-listings-specialist-i-data-scientist-philips-india-limited-bangalore-bengaluru-4-to-7-years-170521500993?src=jobsearchDesk&sid=16213661800726183&xp=7&px=1',
 'https://www.naukri.com/job-listings-data-scientist-ibm-india-pvt-limited-bangalore-bengaluru-6-to-8-years-110521907352?src=jobsearchDesk&sid=16213661800726183&xp=8&px=1',
 'https://www.naukri.com/job-listings-lead-data-scientist-intel-technology-india-pvt-ltd-bangalore-bengaluru-6-to-10-years-070521500578?src=jobsearchDesk&sid=16213661800726183&xp=9&px=1',
 'https://www.naukri.com/job-listings-sde-lead-data-scientist-l3-huawei-technologies-india-pvt-ltd-bangalore-bengaluru-5-to-8-years-120521901434?src=jobsearchDesk&sid=16213661800726183&xp=10&px=1']

In [62]:
len(jobdesc)

10

In [97]:
jobdescription=[]
for i in jobdesc:
    url=i
    driver.get(url)
    sleep(4)
    try:
        job=driver.find_element_by_xpath("//div[@class='dang-inner-html']")
        jobdescription.append(job.text.replace('\\n', '\n'))
    except NoSuchElementException:
        job=driver.find_element_by_xpath("//div[@class='clearboth description']")
        jobdescription.append(job.text.replace('\\n', '\n'))
    print(jobdescription)

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science."]
["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills', 'Roles & Responsibilities & Key Skills:\n\nBig Data DS\n\nExperience with big data/advanced analytics concepts and algorithms (e.g., text mining, social listening, recommender systems, predictive modeling, etc.).\nRelevant programming background (e.g., Java/Python/R).\nStrong understanding of relevant tools/platforms (e.g., Hadoop eco system and database systems);\nRelevant domain knowledge is plus; (healthcare/transportation/hi-tech/insurance);\nExcellent oral and written communication skills.\nStrong attention to detail, with a research-focused mindset.\nExcellent critical thinking and problem solving skills.\nHigh motivation, good work ethic and maturity.\nMinimum 1-3 yrs of proven project experience.\n\nQualification: BS or MS Degree in Computer Science, Information Technology, or equivalent.\nBCA/ BE/ MCA / B.Tech (Computer science, IT)\n\nKey Competencies & Personal Skills:\nExcellent organization skills, attention to detail, and ability to multi-task.\nDemonstrated sense of responsibility and capability to deliver quickly.\nExcellent communication skills. Clearly articulating/ documenting technical/ functional specifications is a key requirement.\nAttitude to learn new tools.\nProactive problem-solver. Relationship builder and team player.\nFlexibility to work in multiple complex projects and changing priorities.\nExperience with Agile methodology\nExcellent interpersonal skill (articulation using verbal and non-verbal skills).\nFlexible to learn.\nAbility to express their design ideas and thoughts.\nAdaptability to continuously changing team requirements.\nDemonstrated ability to deliver working solutions on time.\nStrong analytical thinking and problem-solving skills\n\nKey Skills What we offer in this role:\nBest market exposure, internal visibility for growth.\nWork on robust, secure and architectural environment.\nOpportunity to work in a technical satisfying environment.\nFlawless blend of volume & niche to enrich your entire experience & add starts to your career.\nYoung fast-growing team.\n\nOther Mandatory Aspects:\nEarly/ immediate joiners are welcome.']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills', 'Roles & Responsibilities & Key Skills:\n\nBig Data DS\n\nExperience with big data/advanced analytics concepts and algorithms (e.g., text mining, social listening, recommender systems, predictive modeling, etc.).\nRelevant programming background (e.g., Java/Python/R).\nStrong understanding of relevant tools/platforms (e.g., Hadoop eco system and database systems);\nRelevant domain knowledge is plus; (healthcare/transportation/hi-tech/insurance);\nExcellent oral and written communication skills.\nStrong attention to detail, with a research-focused mindset.\nExcellent critical thinking and problem solving skills.\nHigh motivation, good work ethic and maturity.\nMinimum 1-3 yrs of proven project experience.\n\nQualification: BS or MS Degree in Computer Science, Information Technology, or equivalent.\nBCA/ BE/ MCA / B.Tech (Computer science, IT)\n\nKey Competencies & Personal Skills:\nExcellent organization skills, attention to detail, and ability to multi-task.\nDemonstrated sense of responsibility and capability to deliver quickly.\nExcellent communication skills. Clearly articulating/ documenting technical/ functional specifications is a key requirement.\nAttitude to learn new tools.\nProactive problem-solver. Relationship builder and team player.\nFlexibility to work in multiple complex projects and changing priorities.\nExperience with Agile methodology\nExcellent interpersonal skill (articulation using verbal and non-verbal skills).\nFlexible to learn.\nAbility to express their design ideas and thoughts.\nAdaptability to continuously changing team requirements.\nDemonstrated ability to deliver working solutions on time.\nStrong analytical thinking and problem-solving skills\n\nKey Skills What we offer in this role:\nBest market exposure, internal visibility for growth.\nWork on robust, secure and architectural environment.\nOpportunity to work in a technical satisfying environment.\nFlawless blend of volume & niche to enrich your entire experience & add starts to your career.\nYoung fast-growing team.\n\nOther Mandatory Aspects:\nEarly/ immediate joiners are welcome.', 'Responsibilities and Key Result Areas\nDesign and develop project prototypes and solutions.\nParticipate in project estimation, planning and risk management activities\nIs responsible for delivering input in the planning process to the project leader\nEnsures that there is proper documentation for the developed solutions.\nEnsure compliance to the Quality Management System and regulatory requirements\nKey Technical Skills:\n4 - 7 yrs years of experience in data science\nDeveloped Proficient in algorithms on regression modelling (linear/logistic), supervised and unsupervised classification,\ntree-based techniques (Decision trees /Random forest), neural nets, bagging, Pattern Mining and boosting techniques, etc.\nProficient and hands on experience in developing models using concepts of Artificial Intelligence,\nMachine Learning and Deep Learning related technologies (such as Keras, TensorFlow, pyTorch, Azure ML, AWS ML, Scikit, Jupyter, MatLab etc.)\nExperience with containers like Docker is added advantage\nExperience in Sql\nWorking experience in agile/SAFe development methodologies\nSoft Skill set:\nFast learner. Ability to grasp key concepts quickly with minimal or no supervision\nGo-Getter Attitude. Ability to take ownership of team goals and deliver it with quality and within required timeline\nTeam Player attitude. Key characteristic of the individual who puts the team first before self.\nAbility to think out of box: Ability to come up with bright ideas and always looking at the next big thing in technology\nFlexible and willingness to stretch oneself when needed.']

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills', 'Roles & Responsibilities & Key Skills:\n\nBig Data DS\n\nExperience with big data/advanced analytics concepts and algorithms (e.g., text mining, social listening, recommender systems, predictive modeling, etc.).\nRelevant programming background (e.g., Java/Python/R).\nStrong understanding of relevant tools/platforms (e.g., Hadoop eco system and database systems);\nRelevant domain knowledge is plus; (healthcare/transportation/hi-tech/insurance);\nExcellent oral and written communication skills.\nStrong attention to detail, with a research-focused mindset.\nExcellent critical thinking and problem solving skills.\nHigh motivation, good work ethic and maturity.\nMinimum 1-3 yrs of proven project experience.\n\nQualification: BS or MS Degree in Computer Science, Information Technology, or equivalent.\nBCA/ BE/ MCA / B.Tech (Computer science, IT)\n\nKey Competencies & Personal Skills:\nExcellent organization skills, attention to detail, and ability to multi-task.\nDemonstrated sense of responsibility and capability to deliver quickly.\nExcellent communication skills. Clearly articulating/ documenting technical/ functional specifications is a key requirement.\nAttitude to learn new tools.\nProactive problem-solver. Relationship builder and team player.\nFlexibility to work in multiple complex projects and changing priorities.\nExperience with Agile methodology\nExcellent interpersonal skill (articulation using verbal and non-verbal skills).\nFlexible to learn.\nAbility to express their design ideas and thoughts.\nAdaptability to continuously changing team requirements.\nDemonstrated ability to deliver working solutions on time.\nStrong analytical thinking and problem-solving skills\n\nKey Skills What we offer in this role:\nBest market exposure, internal visibility for growth.\nWork on robust, secure and architectural environment.\nOpportunity to work in a technical satisfying environment.\nFlawless blend of volume & niche to enrich your entire experience & add starts to your career.\nYoung fast-growing team.\n\nOther Mandatory Aspects:\nEarly/ immediate joiners are welcome.', 'Responsibilities and Key Result Areas\nDesign and develop project prototypes and solutions.\nParticipate in project estimation, planning and risk management activities\nIs responsible for delivering input in the planning process to the project leader\nEnsures that there is proper documentation for the developed solutions.\nEnsure compliance to the Quality Management System and regulatory requirements\nKey Technical Skills:\n4 - 7 yrs years of experience in data science\nDeveloped Proficient in algorithms on regression modelling (linear/logistic), supervised and unsupervised classification,\ntree-based techniques (Decision trees /Random forest), neural nets, bagging, Pattern Mining and boosting techniques, etc.\nProficient and hands on experience in developing models using concepts of Artificial Intelligence,\nMachine Learning and Deep Learning related technologies (such as Keras, TensorFlow, pyTorch, Azure ML, AWS ML, Scikit, Jupyter, MatLab etc.)\nExperience with containers like Docker is added advantage\nExperience in Sql\nWorking experience in agile/SAFe development methodologies\nSoft Skill set:\nFast learner. Ability to grasp key concepts quickly with minimal or no supervision\nGo-Getter Attitude. Ability to take ownership of team goals and deliver it with quality and within required timeline\nTeam Player attitude. Key characteristic of the individual who puts the team first before self.\nAbility to think out of box: Ability to come up with bright ideas and always looking at the next big thing in technology\nFlexible and willingness to stretch oneself when needed.', 'The Data Warehousing Practitioner actively participates on multi-functional project teams developing ETL and Visualization enabled solutions, owning and leading the work done. Recommends and implements analytics enabled solutions to improve business process, to generate insights, to support business goals and strategy development. They would also own and deliver complete projects of moderate scope\nAs a Senior Data Warehousing Practitioner, you recommend and implement ETL & Visualization solutions to improve business process, to generate insights, to support business goals and strategy development :\nYou will play a lead position with a strong technology and solution delivery acumen, who will be accountable for the successful design, development, and delivery of business intelligence solutions\nWill be responsible for driving the overall solution design and determining the architecture necessary for the BI team to develop and implement large complex projects\nWorks with business partners, development teams and se

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills', 'Roles & Responsibilities & Key Skills:\n\nBig Data DS\n\nExperience with big data/advanced analytics concepts and algorithms (e.g., text mining, social listening, recommender systems, predictive modeling, etc.).\nRelevant programming background (e.g., Java/Python/R).\nStrong understanding of relevant tools/platforms (e.g., Hadoop eco system and database systems);\nRelevant domain knowledge is plus; (healthcare/transportation/hi-tech/insurance);\nExcellent oral and written communication skills.\nStrong attention to detail, with a research-focused mindset.\nExcellent critical thinking and problem solving skills.\nHigh motivation, good work ethic and maturity.\nMinimum 1-3 yrs of proven project experience.\n\nQualification: BS or MS Degree in Computer Science, Information Technology, or equivalent.\nBCA/ BE/ MCA / B.Tech (Computer science, IT)\n\nKey Competencies & Personal Skills:\nExcellent organization skills, attention to detail, and ability to multi-task.\nDemonstrated sense of responsibility and capability to deliver quickly.\nExcellent communication skills. Clearly articulating/ documenting technical/ functional specifications is a key requirement.\nAttitude to learn new tools.\nProactive problem-solver. Relationship builder and team player.\nFlexibility to work in multiple complex projects and changing priorities.\nExperience with Agile methodology\nExcellent interpersonal skill (articulation using verbal and non-verbal skills).\nFlexible to learn.\nAbility to express their design ideas and thoughts.\nAdaptability to continuously changing team requirements.\nDemonstrated ability to deliver working solutions on time.\nStrong analytical thinking and problem-solving skills\n\nKey Skills What we offer in this role:\nBest market exposure, internal visibility for growth.\nWork on robust, secure and architectural environment.\nOpportunity to work in a technical satisfying environment.\nFlawless blend of volume & niche to enrich your entire experience & add starts to your career.\nYoung fast-growing team.\n\nOther Mandatory Aspects:\nEarly/ immediate joiners are welcome.', 'Responsibilities and Key Result Areas\nDesign and develop project prototypes and solutions.\nParticipate in project estimation, planning and risk management activities\nIs responsible for delivering input in the planning process to the project leader\nEnsures that there is proper documentation for the developed solutions.\nEnsure compliance to the Quality Management System and regulatory requirements\nKey Technical Skills:\n4 - 7 yrs years of experience in data science\nDeveloped Proficient in algorithms on regression modelling (linear/logistic), supervised and unsupervised classification,\ntree-based techniques (Decision trees /Random forest), neural nets, bagging, Pattern Mining and boosting techniques, etc.\nProficient and hands on experience in developing models using concepts of Artificial Intelligence,\nMachine Learning and Deep Learning related technologies (such as Keras, TensorFlow, pyTorch, Azure ML, AWS ML, Scikit, Jupyter, MatLab etc.)\nExperience with containers like Docker is added advantage\nExperience in Sql\nWorking experience in agile/SAFe development methodologies\nSoft Skill set:\nFast learner. Ability to grasp key concepts quickly with minimal or no supervision\nGo-Getter Attitude. Ability to take ownership of team goals and deliver it with quality and within required timeline\nTeam Player attitude. Key characteristic of the individual who puts the team first before self.\nAbility to think out of box: Ability to come up with bright ideas and always looking at the next big thing in technology\nFlexible and willingness to stretch oneself when needed.', 'The Data Warehousing Practitioner actively participates on multi-functional project teams developing ETL and Visualization enabled solutions, owning and leading the work done. Recommends and implements analytics enabled solutions to improve business process, to generate insights, to support business goals and strategy development. They would also own and deliver complete projects of moderate scope\nAs a Senior Data Warehousing Practitioner, you recommend and implement ETL & Visualization solutions to improve business process, to generate insights, to support business goals and strategy development :\nYou will play a lead position with a strong technology and solution delivery acumen, who will be accountable for the successful design, development, and delivery of business intelligence solutions\nWill be responsible for driving the overall solution design and determining the architecture necessary for the BI team to develop and implement large complex projects\nWorks with business partners, development teams and se

["Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nManigandan -+91 7299917200\n\nEmail : manigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Maths and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science.", 'We wont say we can predict the future, but our team of Analysts get pretty close, they turn millions of data points into useful information & insights that help our clients to make better decisions on their marketing mix and achieve superior results. Be part of the future and join in on one of the major transformations in the market research industry with the integration of big data and classic marketing mix analysis.\n\nResponsibilities:\nDeliver as a part of our consultant team in driving high quality results on custom project work\nEnsure effective and timely delivery of project work\nWork towards understanding statistical models and deliver business insights and findings\nEnsure compliance to Marketing Mix Modeling modeling practices and company quality standards\nMaximize the efficient and effective use of resources by utilizing appropriate processes and tools\nTo build and maintain effective contacts with other departments to ensure the efficient and effective use of resources\nLiaise with appropriate Marketing Mix Modeling and Nielsen departments to ensure hardware and software requirements are fulfilled\nWork with co/ third party modellers to deliver business insights and findings\n\nQualifications and Skills\n2-5 years of relevant experience\nMasters degree in Economics, Mathematics, Statistics, Engineering\nIn-depth understanding of statistical modeling techniques and applications\nGood and working knowledge of any statistical languages like SAS, R, Pythons\nSolid proficiency of decision making and problem resolution skills\nPassion for results with a challenger mindset\n\nAbout the Team:\nGlobal Product, Technology & Operations supports Nielsen Medias growth strategy by enabling positive client and market solutions. Our Operations Team is in a unique position as the center of data collection, analysis and delivery. We deliver outcomes with the highest quality and integrity standards in an agile and transparent way while standing by our Nielsen values.', 'As a Data Scientist in the IBM Garage team you will part of a cross-functional team that delivers a unique client co-creation experience to accelerate client transformation.\n\nYour Role and Responsibilities\nWho you are\nYou are a key contributor to a pre-sales Garage team ,partnering with client to understand business problems and propose solutions.\nYou demonstrate strong business acumen and ability to understand business problems, formulate hypotheses and test conclusions to influence solution design.\nWhat you will do\nContribute to co-creation of rapid proofs of concept and minimally viable solutions that demonstrate business value, leading to client investment in strategic solution .\nTranslate business problems into leading-edge analytics solutions using consulting skills ,industry expertise and technical knowledge\nDeliver meaningful insights and predict emerging trends to inform business solution that optimize client value\nApply Data Engineering techniques to gather ,prepare, cleanse and transform client data for analysis and AI automation ,including automating data pipelines\nRequired Technical and Professional Expertise\nExcellent understanding of machine learning and deep learning techniques and algorithms, such Deep CNNs, Optimizers, Feature Engineering, Transformers, etc.\nExperience handling large scale production datasets and understanding of related challenges and processes to address them\nExperience with common data science toolkits such as NumPy, scikit-learn, spaCy, Keras, PyTorch, etc. Excellence in at least one of these is highly desirable\nExperience with NoSQL databases, such as MongoDB, DnamoDB, Cloudant etc and understanding of basic data wrangling techniques\nGood to have academic training in a quantitative discipline and /or a specialized degree in data science or analytics .\nPossesses relevant industry and /or business domain knowledge such finance or healthcare .\nPreferred Technical and Professional Expertise\nDemonstrated experience in applying user centric approach to design and create compelling prototypes that lead to transformative change for the client\nKnowledge of a variety of modern application of data science, including machine learning ,optimization ,neural networks and /or artificial intelligence that can be applied to solve client problems\nDeep understanding of statistical machine learning models with Python or R to propose innovative solution\nExpertise in the use of cloud based infrastructure to manage the volume and veracity of complex data streams .', 'Introduction\nAs a Data Scientist at IBM, you will help transform our clients’ data into tangible business value by analyzing information, communicating outcomes and collaborating on product development. Work with Best in Class open source and visual tools, along with the most flexible and scalable deployment options. Whether it’s investigating patient trends or weather patterns, you will work to solve real world problems for the industries transforming how we live.\n\nYour Role and Responsibilities\nAs businesses, governments and communities become more data driven in their decision making and business operations, demand on the new and innovative AI and Analytics related capabilities are exponentially growing. As trusted advisor to the Chief Analytics Officer and various CXOs (Marketing, Risk, Digital), build compelling value proposition for flexible and futuristic Analytics driven insights and solutions. You will partner with sector teams, global markets team and all IBM brands to sense, originate, qualify opportunities, and pursue the deals to closure.\nResponsibilities:\nOriginate new Analytics &AI opportunities in partnership with Global Markets, Sectors and IBM Brands\nWork closely with the deal teams to shape and solution Analytics & AI led programs, continuously engage with key client executives and share IBM solution details, effectively communicate value proposition on analytics led insights and embed AI solution in client processes.\nOwn end to end delivery of, a) large & complex Analytics &AI led transformation programs, b) small and nimble business insights initiatives to realize quick gains, c) work with IBM and Partners to bring the best tools and delivery methods.\nOwn the offerings and assets on key components of Analytics & AI value chain, including understanding burning platform and industry trends, define and frame hypothesis,\nBuild key partnerships with top tools, platform and fintechs.\nImprovise new and innovative data assets and drive it’s adoption to the market.\nBe a thought leader on AI\nShould have hired and nurtured talent and grow them in market facing specialists and consultants. Should have built a community of practice on data.\nRequired Technical and Professional Expertise\nSomeone who has traversed the Analytics &AI value chain, having moved the clients from data to insights.\nDeep expertise in applying Analytics for two or more industries (BFSI, Manufacturing, Distribution, Electronics, Oil&Gas etc.)\nIn depth understanding of AI tools across Machine Learning, Intelligent Automation, Conversation Intelligence and how they all come together to build AI ecosystem\nWorked in a third party consulting, service, technology organization for a fair share of the career.\nConsulted clients on aspiration to make them information led decision making business.\nHands on expertise in developing and implementing predictive models (statistical and machine learning) for large enterprises.\nProven deep client relationships and drive the advisory agenda.\nProven ability to enhance value of an opportunity through new technology\nAbility to run multiple and disparate client conversations, opportunity pursuits, and handle the execution of dynamic practice agenda.\nPreferred Technical and Professional Expertise\nSupport both the development of new business opportunities and the delivery of analytics platform services to clients.\nAdvise clients in the planning, design, management, execution, and reporting of the core components for big data offerings. Skills include: architecture, tool selection, data lake design and implementation\nStrong relations in the Indian market with key client decision makers', 'Responsibilities and duties Focus on developing clear and concise analytical approach for problem solving with client partnership\nStrong understanding of ML libraries and applications e.g. Neural Net, SVMs, boosting methods and implementation using R/Python. Should have academic paper level understanding of math e.g. linear algebra, calculus etc.\nAbility to code on SAS/R for data munging, analysis and insights and/or languages like Python for creating efficient production ready code\nManaging delivery of projects including timely communication, setting milestones and tracking Generating actionable insights for business/KPI improvements Ability to work independently, structure analyses and handle multiple priorities Develop and Maintaining Credit Risk Models Strategies Rich experience in at least one production ready deployment of Machine Learning algorithms is a plus. Experience in working on real life large messy dataset to solve real business problems. Kaggle experience is a plus.\n  Skills Competencies: Experience in Financial Services/ Fintech/ BFSI along with Credit Risk in Retail Banking and Data Science 5 years of experience in building predictive models (Application Scorecard, Behaviour Scorecard, Collection Score Card, Loan Pricing, Loss Forecasting, Cross Sell Model) Experienced Statistical software skills (e.g. SAS, R, Python Strong understanding of ML libraries and applications. Strong experience in leading credit risk model development, validation, deployment, and documentation Analytically oriented with ability to grasp complex risk management strategies, processes, models and draw insights / identify areas of opportunity\nStrong track record of delivering on high value / critical projects. Ability to communicate with senior stakeholders crisply and confidently on findings, status, bottlenecks, and escalations\nProven track record of delivering in a start-up environment would be a plus Strong written and oral communication skills', 'Roles & Responsibilities & Key Skills:\n\nBig Data DS\n\nExperience with big data/advanced analytics concepts and algorithms (e.g., text mining, social listening, recommender systems, predictive modeling, etc.).\nRelevant programming background (e.g., Java/Python/R).\nStrong understanding of relevant tools/platforms (e.g., Hadoop eco system and database systems);\nRelevant domain knowledge is plus; (healthcare/transportation/hi-tech/insurance);\nExcellent oral and written communication skills.\nStrong attention to detail, with a research-focused mindset.\nExcellent critical thinking and problem solving skills.\nHigh motivation, good work ethic and maturity.\nMinimum 1-3 yrs of proven project experience.\n\nQualification: BS or MS Degree in Computer Science, Information Technology, or equivalent.\nBCA/ BE/ MCA / B.Tech (Computer science, IT)\n\nKey Competencies & Personal Skills:\nExcellent organization skills, attention to detail, and ability to multi-task.\nDemonstrated sense of responsibility and capability to deliver quickly.\nExcellent communication skills. Clearly articulating/ documenting technical/ functional specifications is a key requirement.\nAttitude to learn new tools.\nProactive problem-solver. Relationship builder and team player.\nFlexibility to work in multiple complex projects and changing priorities.\nExperience with Agile methodology\nExcellent interpersonal skill (articulation using verbal and non-verbal skills).\nFlexible to learn.\nAbility to express their design ideas and thoughts.\nAdaptability to continuously changing team requirements.\nDemonstrated ability to deliver working solutions on time.\nStrong analytical thinking and problem-solving skills\n\nKey Skills What we offer in this role:\nBest market exposure, internal visibility for growth.\nWork on robust, secure and architectural environment.\nOpportunity to work in a technical satisfying environment.\nFlawless blend of volume & niche to enrich your entire experience & add starts to your career.\nYoung fast-growing team.\n\nOther Mandatory Aspects:\nEarly/ immediate joiners are welcome.', 'Responsibilities and Key Result Areas\nDesign and develop project prototypes and solutions.\nParticipate in project estimation, planning and risk management activities\nIs responsible for delivering input in the planning process to the project leader\nEnsures that there is proper documentation for the developed solutions.\nEnsure compliance to the Quality Management System and regulatory requirements\nKey Technical Skills:\n4 - 7 yrs years of experience in data science\nDeveloped Proficient in algorithms on regression modelling (linear/logistic), supervised and unsupervised classification,\ntree-based techniques (Decision trees /Random forest), neural nets, bagging, Pattern Mining and boosting techniques, etc.\nProficient and hands on experience in developing models using concepts of Artificial Intelligence,\nMachine Learning and Deep Learning related technologies (such as Keras, TensorFlow, pyTorch, Azure ML, AWS ML, Scikit, Jupyter, MatLab etc.)\nExperience with containers like Docker is added advantage\nExperience in Sql\nWorking experience in agile/SAFe development methodologies\nSoft Skill set:\nFast learner. Ability to grasp key concepts quickly with minimal or no supervision\nGo-Getter Attitude. Ability to take ownership of team goals and deliver it with quality and within required timeline\nTeam Player attitude. Key characteristic of the individual who puts the team first before self.\nAbility to think out of box: Ability to come up with bright ideas and always looking at the next big thing in technology\nFlexible and willingness to stretch oneself when needed.', 'The Data Warehousing Practitioner actively participates on multi-functional project teams developing ETL and Visualization enabled solutions, owning and leading the work done. Recommends and implements analytics enabled solutions to improve business process, to generate insights, to support business goals and strategy development. They would also own and deliver complete projects of moderate scope\nAs a Senior Data Warehousing Practitioner, you recommend and implement ETL & Visualization solutions to improve business process, to generate insights, to support business goals and strategy development :\nYou will play a lead position with a strong technology and solution delivery acumen, who will be accountable for the successful design, development, and delivery of business intelligence solutions\nWill be responsible for driving the overall solution design and determining the architecture necessary for the BI team to develop and implement large complex projects\nWorks with business partners, development teams and se

Q3: In this question you have to scrape data using the filters available on the webpage as shown below:
You

In [262]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.naukri.com/'
driver.get(url)

In [263]:
search_job3=driver.find_element_by_id('qsb-keyword-sugg')
search_job3

search_job3.send_keys("Data Scientist")
#enters "Data Scientist" in keyowrd search bar

In [264]:
search_btn1=driver.find_element_by_xpath("//button[@class='btn']")
search_btn1.click() #clicks on search button

In [265]:
search_btn2=driver.find_element_by_xpath("(//i[@class='fleft naukicon naukicon-checkbox'])[2]")
search_btn2.click() #clicks on “Delhi/NCR” filter

In [266]:
search_btn3=driver.find_element_by_xpath("(//i[@class='fleft naukicon naukicon-checkbox'])[5]")
search_btn3.click() #clicks on “3-6” lakhs filter

In [267]:
job_title_tags2=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")

In [268]:
job_title2=[]
for i in job_title_tags2:
    if len(job_title2)<10:
        job_title2.append(i.text)

job_title2 = pd.DataFrame(job_title2)
job_title2.columns=['Job_title']
job_title2
#Job titles of first 10 jobs using location filter as “Delhi/NCR” and salary filter as “3-6” lakhs

                                                       Job_title
0  Data Scientist / Data Analyst -Business Analyst
1  Data Scientist
2  Data Scientist - High growth VC backed Influencer Marketplace
3  Excellent opportunity For Data Scientist
4  Data Scientist
5  DATA Scientist – Gurgaon (Exp 3-6 years)
6  DATA Scientist – Gurgaon (Exp 3-6 years)
7  Data Scientist - Noida
8  Data Scientist - Noida/ B'lore
9  Data Scientist

In [269]:
job_location_tags2=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")

In [270]:
job_location2=[]
for i in job_location_tags2:
    if len(job_location2)<10:
        job_location2.append(i.text)
job_location2
job_location2 = pd.DataFrame(job_location2)
job_location2.columns=['Job_location']
job_location2
#Job Locations of first 10 jobs using location filter as “Delhi/NCR” and salary filter as “3-6” lakhs

                                                                           Job_location
0  Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru
1  Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru
2  Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)
3  Noida, Bangalore/Bengaluru
4  New Delhi, Gurgaon/Gurugram, Delhi / NCR
5  Gurgaon/Gurugram, Delhi / NCR
6  Gurgaon/Gurugram, Delhi / NCR
7  Noida
8  Noida, Bangalore/Bengaluru
9  Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)

In [271]:
company_name_tags2=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")

In [272]:
company_name2=[]
for i in company_name_tags2:
    if len(company_name2)<10:
        company_name2.append(i.text)

company_name2 = pd.DataFrame(company_name2)
company_name2.columns=['Company_name']
company_name2
#Company names of first 10 jobs using location filter as “Delhi/NCR” and salary filter as “3-6” lakhs

                                                Company_name
0  Inflexion Analytix Private Limited
1  IBM India Pvt. Limited
2  Ravgins International Pvt. Ltd.
3  NEC CORPORATION INDIA PRIVATE LIMITED
4  Mobikwik
5  CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVATE L IMITED
6  CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVATE L IMITED
7  Optum Global Solutions (India) Private Limited
8  NEC CORPORATION INDIA PRIVATE LIMITED
9  Cloudstrats Technologies Private Limited

In [273]:
experience_required_tags2=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")

In [274]:
experience_required2=[]
for i in experience_required_tags2:
    if len(experience_required2)<10:
        experience_required2.append(i.text)

experience_required2 = pd.DataFrame(experience_required2)
experience_required2.columns=['Experience_required']
experience_required2
#Experience required of first using location filter as “Delhi/NCR” and salary filter as “3-6” lakhs

  Experience_required
0  0-3 Yrs
1  4-9 Yrs
2  3-5 Yrs
3  3-7 Yrs
4  3-5 Yrs
5  3-6 Yrs
6  3-6 Yrs
7  3-5 Yrs
8  3-8 Yrs
9  5-8 Yrs

In [275]:
First10jobresultsofdatascientistindelhi=pd.DataFrame({})
First10jobresultsofdatascientistindelhi['Job_title']=job_title2['Job_title']
First10jobresultsofdatascientistindelhi['Job_location']=job_location2['Job_location']
First10jobresultsofdatascientistindelhi['Company_name']=company_name2['Company_name']
First10jobresultsofdatascientistindelhi['Experience_required']=experience_required2['Experience_required']
First10jobresultsofdatascientistindelhi
# first 10 job-title, job-location, company_name, experience_require for 'Data scientist' Job position in Delhi/NCR,
# with salary of 3-6 lakhs

,Job_title,Job_location,Company_name,Experience_required
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru",Inflexion Analytix Private Limited,0-3 Yrs
1,Data Scientist,"Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru",IBM India Pvt. Limited,4-9 Yrs
2,Data Scientist - High growth VC backed Influencer Marketplace,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)",Ravgins International Pvt. Ltd.,3-5 Yrs
3,Excellent opportunity For Data Scientist,"Noida, Bangalore/Bengaluru",NEC CORPORATION INDIA PRIVATE LIMITED,3-7 Yrs
4,Data Scientist,"New Delhi, Gurgaon/Gurugram, Delhi / NCR",Mobikwik,3-5 Yrs
5,DATA Scientist – Gurgaon (Exp 3-6 years),"Gurgaon/Gurugram, Delhi / NCR",CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVATE L IMITED,3-6 Yrs
6,DATA Scientist – Gurgaon (Exp 3-6 years),"Gurgaon/Gurugram, Delhi / NCR",CRESCENDO GLOBAL LEADERSHIP HIRING INDIA PRIVATE L IMITED,3-6 Yrs
7,Data Scientist - Noida,Noida,Optum Global Solutions (India) Private Limited,3-5 Yrs
8,Data Scientist - Noida/ B'lore,"Noida, Bangalore/Bengaluru",NEC CORPORATION INDIA PRIVATE LIMITED,3-8 Yrs
9,Data Scientist,"Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)",Cloudstrats Technologies Private Limited,5-8 Yrs

Q4: Write a python program to scrape data for first 10 job results for Data scientist
Designation in Noida location. You have to scrape company_name, No. of days
ago when job was posted, Rating of the company.

In [314]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.glassdoor.co.in/index.htm'
driver.get(url)

In [338]:
search_job3=driver.find_element_by_xpath("//input[@placeholder='Job Title, Keywords or Company']")
search_job3.click() #clicks on keyword search bar

In [339]:
# search_job3=driver.find_element_by_xpath("//span[@class='SVGInline d-flex SearchStyles__searchIcon']")
# search_job3.click()

In [340]:
search_job4=driver.find_element_by_id('scKeyword')
search_job4 #clicks on keyword search bar

In [341]:
search_job4.send_keys("Data Scientist") #enters "Data Scientist" in search bar

In [342]:
search_loc4=driver.find_element_by_id('prefix__icon-arrow-1')
search_loc4.click() #clicks on location search bar

In [347]:
search_loc3=driver.find_element_by_id('sc.location')
search_loc3 #clicks on location search bar

In [30]:
from selenium.webdriver.common.keys import Keys #importing keys

In [350]:
search_loc3.send_keys(Keys.CONTROL + "a") 
search_loc3.send_keys(Keys.DELETE) #clears location search bar
search_loc3.send_keys("Noida") #enters "Noida" in location search bar

In [351]:
search_btn3=driver.find_element_by_xpath("//button[@class='gd-ui-button ml-std col-auto SearchStyles__newSearchButton css-iixdfr']")
search_btn3.click() #clicks on search button

In [352]:
company_name_tags4=driver.find_elements_by_xpath("//a[@class=' css-l2wjgv e1n63ojh0 jobLink']")

In [353]:
company_name4=[]
for i in company_name_tags4:
    if len(company_name4)<10:
        company_name4.append(i.text)
company_name4
company_name4 = pd.DataFrame(company_name4)
company_name4.columns=['company_name']
company_name4
#company names of first 10 Data Scientists jobs in Noida from glassdoor

                   company_name
0                Biz2Credit Inc
1                      Techlive
2                      Ericsson
3                 NatWest Group
4  Salasar New Age Technologies
5            Apsidata Solutions
6                       CRMNEXT
7  Salasar New Age Technologies
8        Data Trained Education
9                     dunnhumby

In [354]:
days=driver.find_elements_by_xpath("//div[@class='d-flex align-items-end pl-std css-mi55ob']")

In [355]:
no_of_days=[]
for i in days:
    if len(no_of_days)<10:
        no_of_days.append(i.text)
no_of_days
no_of_days = pd.DataFrame(no_of_days)
no_of_days.columns=['No_of_days']
no_of_days
#No. of days ago when job was posted of first 10 Data Scientists jobs in Noida from glassdoor

  No_of_days
0       30d+
1       30d+
2        13d
3        24h
4       30d+
5         3d
6        12d
7       30d+
8         1d
9        24h

In [356]:
rat=[] #scraping all urls of first 10 job's full description
for i in driver.find_elements_by_xpath("//div[@class='d-flex justify-content-between align-items-start']/a"):
    if len(rat)<10:
        rat.append(i.get_attribute('href'))
rat

['https://www.glassdoor.co.in/partner/jobListing.htm?pos=101&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&ea=1&cs=1_b6832e69&cb=1621375824340&jobListingId=1006687249100&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-94036c835379de77',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=102&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_5460cbb7&cb=1621375824339&jobListingId=1006461286442&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-a1ea358f023a69b7',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=103&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_f6da4d8b&cb=1621375824339&jobListingId=1007039772952&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-6bf9c5704a989f4b',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=104&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_43964edd&cb=1621375824339&jobListingId=1007064515465&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-c453417daf20e214',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=105&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_e887528e&cb=1621375824339&jobListingId=1006624053994&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-a8cb856cd397a474',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=106&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_e4e26a62&cb=1621375824339&jobListingId=1007059872386&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-9ad5d1bd01b93491',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=107&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_91387fa7&cb=1621375824340&jobListingId=1007042885469&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-a99a33f8c13a0bc2',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=108&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_fae33f46&cb=1621375824340&jobListingId=1006624054035&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-c47c5ae51c2ed2ee',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=109&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&ea=1&cs=1_12444a79&cb=1621375824343&jobListingId=1007062410781&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-d9e77ada0df0a0db',
 'https://www.glassdoor.co.in/partner/jobListing.htm?pos=110&ao=1136043&s=58&guid=000001798187adfb82f22184bd53cb86&src=GD_JOB_AD&t=SR&vt=w&uido=047932A66C2519CE32EC31CA5D9D071C&cs=1_789d39fe&cb=1621375824340&jobListingId=1007064801516&jrtk=1-1f60ofc2su3kk801-1f60ofc3eu2il800-f80d93a916d13044']

In [357]:
rating=[]
for i in rat:
    url=i
    driver.get(url)
    sleep(4)
    try:
        ratings=driver.find_element_by_xpath("//span[@class='css-1pmc6te e11nt52q4']")
        rating.append(ratings.text)
    except NoSuchElementException:
        rating.append('None')

In [358]:
rating = pd.DataFrame(rating)
rating.columns=['rating']
rating['rating']=rating['rating'].str.replace('\n','')
rating
#Ratings of the company of first 10 Data Scientists jobs in Noida from glassdoor

  rating
0   3.8★
1   5.0★
2   4.1★
3   3.9★
4   None
5   None
6   3.6★
7   None
8   None
9   4.1★

In [359]:
datascientistnoida10=pd.DataFrame({})
datascientistnoida10['Company_name']=company_name4['company_name']
datascientistnoida10['No_of_days_before_job_posted']=no_of_days['No_of_days']
datascientistnoida10['Ratings']=rating['rating']
datascientistnoida10
# 10 job results for Data scientist Designation in Noida location
#scraped company_name, No. of days ago when job was posted, Rating of the company

                   Company_name No_of_days_before_job_posted Ratings
0                Biz2Credit Inc                         30d+    3.8★
1                      Techlive                         30d+    5.0★
2                      Ericsson                          13d    4.1★
3                 NatWest Group                          24h    3.9★
4  Salasar New Age Technologies                         30d+    None
5            Apsidata Solutions                           3d    None
6                       CRMNEXT                          12d    3.6★
7  Salasar New Age Technologies                         30d+    None
8        Data Trained Education                           1d    None
9                     dunnhumby                          24h    4.1★

Q5: Write a python program to scrape the salary data for Data Scientist designation
in Noida location.

In [434]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.glassdoor.co.in/Salaries/index.htm'
driver.get(url)

In [435]:
search_job5=driver.find_element_by_id('KeywordSearch')
search_job5.click()#click on keyword search bar

In [436]:
search_job5.send_keys("Data Scientist")  #entering Data Scientist in keyword search bar

In [437]:
search_loc5=driver.find_element_by_id('LocationSearch')
search_loc5.click() #click on location search bar

In [440]:
search_loc5.send_keys("Noida") #entering noida in locationsearch bar

In [441]:
search_btn1=driver.find_element_by_xpath("//button[@class='gd-btn-mkt']")
search_btn1.click() #clicks on search button

In [442]:
company_name_tags5=driver.find_elements_by_xpath("//div[@class='d-flex']/div/p[2]")

In [443]:
company_name5=[]
for i in company_name_tags5:
    if len(company_name5)<10:
        company_name5.append(i.text)
company_name5
company_name5 = pd.DataFrame(company_name5)
company_name5.columns=['company_name']
company_name5
#company names of first 10 Data Scientists jobs in Noida from glassdoor

                company_name
0  Tata Consultancy Services
1                  Accenture
2                        IBM
3         Ericsson-Worldwide
4                  Delhivery
5         UnitedHealth Group
6         Valiance Solutions
7              ZS Associates
8                EXL Service
9     Optum Global Solutions

In [444]:
min_sal=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']/span[1]")

In [445]:
min_salary=[]
for i in min_sal:
    if len(min_salary)<10:
        min_salary.append(i.text)
min_salary
min_salary = pd.DataFrame(min_salary)
min_salary.columns=['min_salary']
min_salary
#Minimum salaries of first 10 companies

  min_salary
0      ₹343K
1      ₹577K
2      ₹586K
3      ₹355K
4      ₹450K
5    ₹1,069K
6      ₹502K
7      ₹202K
8      ₹575K
9    ₹1,014K

In [446]:
max_sal=driver.find_elements_by_xpath("//div[@class='common__RangeBarStyle__values d-flex justify-content-between ']/span[2]")

In [447]:
max_salary=[]
for i in max_sal:
    if len(max_salary)<10:
        max_salary.append(i.text)
max_salary
max_salary = pd.DataFrame(max_salary)
max_salary.columns=['max_salary']
max_salary
#Maximum salaries of first 10 companies

  max_salary
0    ₹1,095K
1    ₹2,213K
2    ₹2,730K
3    ₹1,613K
4   ₹11,622K
5    ₹1,520K
6    ₹1,465K
7    ₹1,809K
8    ₹1,520K
9    ₹2,149K

In [448]:
avg_sal=driver.find_elements_by_xpath("//div[@class='col-2 d-none d-md-flex flex-row justify-content-end']/strong[1]")

In [449]:
avg_salary=[]
for i in avg_sal:
    if len(avg_salary)<10:
        avg_salary.append(i.text)
avg_salary
avg_salary = pd.DataFrame(avg_salary)
avg_salary.columns=['avg_salary']
avg_salary
#Average salaries of first 10 companies

    avg_salary
0   ₹ 6,11,228
1  ₹ 11,46,533
2   ₹ 8,97,795
3   ₹ 7,38,057
4  ₹ 12,39,781
5  ₹ 13,36,142
6   ₹ 8,15,192
7  ₹ 11,35,221
8  ₹ 11,44,243
9  ₹ 14,13,288

In [450]:
#rating?????

In [452]:
datascientistnoidasalary=pd.DataFrame({})
datascientistnoidasalary['Company_name']=company_name5['company_name']
datascientistnoidasalary['Min_salary']=min_salary['min_salary']
datascientistnoidasalary['Max_salary']=max_salary['max_salary']
datascientistnoidasalary['Avg_salary']=avg_salary['avg_salary']
datascientistnoidasalary
# min salary, max salary, company_name, Average salary and rating of the first 10 companies in Noida

                Company_name Min_salary Max_salary   Avg_salary
0  Tata Consultancy Services      ₹343K    ₹1,095K   ₹ 6,11,228
1                  Accenture      ₹577K    ₹2,213K  ₹ 11,46,533
2                        IBM      ₹586K    ₹2,730K   ₹ 8,97,795
3         Ericsson-Worldwide      ₹355K    ₹1,613K   ₹ 7,38,057
4                  Delhivery      ₹450K   ₹11,622K  ₹ 12,39,781
5         UnitedHealth Group    ₹1,069K    ₹1,520K  ₹ 13,36,142
6         Valiance Solutions      ₹502K    ₹1,465K   ₹ 8,15,192
7              ZS Associates      ₹202K    ₹1,809K  ₹ 11,35,221
8                EXL Service      ₹575K    ₹1,520K  ₹ 11,44,243
9     Optum Global Solutions    ₹1,014K    ₹2,149K  ₹ 14,13,288

In [ ]:
# rating??

Q6 : Scrape data of first 100 sunglasses listings on flipkart.com.

In [689]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.flipkart.com/'
driver.get(url)

In [690]:
flipkart=driver.find_element_by_xpath("//input[@type='text']")
flipkart

In [691]:
flipkart.send_keys(Keys.CONTROL + "a")
flipkart.send_keys(Keys.DELETE)
#clears the search bar

In [692]:
flipkart.send_keys("sunglasses")

In [693]:
search_btn6=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn6.click()#click on search button

In [694]:
brand=[]
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        if len(brand)<100:
            brand.append(j.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
brand = pd.DataFrame(brand)
brand.columns=['brand']
brand
#first 100 sunglasses brands on flipkart.com

             brand
0     Singco India
1         bulgaria
2         Fastrack
3   ROZZETTA CRAFT
4           PIRASO
..             ...
95       ROYAL SON
96        Fastrack
97          GANSTA
98          GANSTA
99    Silver Kartz

[100 rows x 1 columns]

In [696]:
search_btn6=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn6.click() #clicks on search button

In [697]:
prddesc=[]
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//a[@class='IRpwTa']"):
        if len(prddesc)<100:
            prddesc.append(j.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
prddesc = pd.DataFrame(prddesc)
prddesc.columns=['prddesc']
prddesc
#first 100 sunglasses product description on flipkart.com

                                              prddesc
0   UV Protection, Riding Glasses, Others Aviator,...
1           Others Rectangular Sunglasses (Free Size)
2    UV Protection Rectangular Sunglasses (Free Size)
3   UV Protection Retro Square Sunglasses (Free Size)
4               UV Protection Aviator Sunglasses (54)
..                                                ...
95       UV Protection Aviator Sunglasses (Free Size)
96  Gradient, UV Protection Wayfarer Sunglasses (F...
97   UV Protection, Gradient Wayfarer Sunglasses (53)
98   UV Protection, Mirrored Wayfarer Sunglasses (53)
99      UV Protection Wayfarer Sunglasses (Free Size)

[100 rows x 1 columns]

In [699]:
search_btn6=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn6.click()#clicks on search button

In [700]:
price=[]
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        if len(price)<100:
            price.append(j.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
price = pd.DataFrame(price)
price.columns=['price']
price
#first 100 sunglasses price on flipkart.com

   price
0   ₹209
1   ₹449
2   ₹630
3   ₹499
4   ₹250
..   ...
95  ₹499
96  ₹682
97  ₹349
98  ₹199
99  ₹664

[100 rows x 1 columns]

In [703]:
search_btn6=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn6.click()#click all search button

In [704]:
discount=[]
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        if len(discount)<100:
            discount.append(j.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
discount = pd.DataFrame(discount)
discount.columns=['discount']
discount
#first 100 sunglasses discount % on flipkart.com

   discount
0   70% off
1   55% off
2   21% off
3   77% off
4   84% off
..      ...
95  61% off
96  14% off
97  82% off
98  80% off
99  66% off

[100 rows x 1 columns]

In [708]:
pd.set_option("display.max_colwidth", -1) #displays whole column value

In [710]:
sunglasses=pd.DataFrame({})
sunglasses['Brand']=brand['brand']
sunglasses['Product_description']=prddesc['prddesc']
sunglasses['Price']=price['price']
sunglasses['Discount']=discount['discount']
sunglasses
#data of first 100 sunglasses listings on flipkart.com

,Brand,Product_description,Price,Discount
0,Singco India,"UV Protection, Riding Glasses, Others Aviator, Wayfarer...",₹209,70% off
1,bulgaria,Others Rectangular Sunglasses (Free Size),₹449,55% off
2,Fastrack,UV Protection Rectangular Sunglasses (Free Size),₹630,21% off
3,ROZZETTA CRAFT,UV Protection Retro Square Sunglasses (Free Size),₹499,77% off
4,PIRASO,UV Protection Aviator Sunglasses (54),₹250,84% off
...,...,...,...,...
95,ROYAL SON,UV Protection Aviator Sunglasses (Free Size),₹499,61% off
96,Fastrack,"Gradient, UV Protection Wayfarer Sunglasses (Free Size)",₹682,14% off
97,GANSTA,"UV Protection, Gradient Wayfarer Sunglasses (53)",₹349,82% off
98,GANSTA,"UV Protection, Mirrored Wayfarer Sunglasses (53)",₹199,80% off
99,Silver Kartz,UV Protection Wayfarer Sunglasses (Free Size),₹664,66% off

Q7: Scrape 100 reviews data from flipkart.com for iphone11 phone

In [766]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.flipkart.com/apple-iphone-11-black-64-gb-includes-earpods-power-adapter/p/itm0f37c2240b217?pid=MOBFKCTSVZAXUHGR&lid=LSTMOBFKCTSVZAXUHGREPBFGI&marketplace'
driver.get(url)

In [767]:
search_btn7=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
search_btn7.click() #click all reviews button

In [768]:
rate=[]
for i in range(0,11):
    for i in driver.find_elements_by_xpath("//div[@class='_3LWZlK _1BLPMq']"):
        if len(rate)<100:
            rate.append(i.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
rate = pd.DataFrame(rate)
rate.columns=['rate']
rate
#top 100 ratings of iphone 11

   rate
0   5
1   5
2   5
3   5
4   4
.. ..
95  5
96  5
97  5
98  5
99  5

[100 rows x 1 columns]

In [ ]:
search_btn7=driver.find_element_by_xpath("//div[@class='_3UAT2v _16PBlm']")
search_btn7.click() #click all reviews button

In [773]:
review=[]
for j in range(0,11):
    for i in driver.find_elements_by_xpath("//p[@class='_2-N8zT']"):
        if len(review)<100:
            review.append(i.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
review = pd.DataFrame(review)
review.columns=['review']
review
#top 100 Review_summary of iphone 11

               review
0   Brilliant
1   Perfect product!
2   Great product
3   Worth every penny
4   Good choice
..          ...
95  Excellent
96  Fabulous!
97  Wonderful
98  Fabulous!
99  Value-for-money

[100 rows x 1 columns]

In [794]:
full_review=[]
for j in range(0,11):
    for i in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
        if len(full_review)<100:
            try:
                driver.find_element_by_xpath("//span[@class='_1BWGvX']").click()
                full_review.append(i.text)
            
            except NoSuchElementException:
                full_review.append(i.text) 
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
full_review = pd.DataFrame(full_review)
full_review.columns=['full_review']
full_review['full_review']=full_review['full_review'].str.replace('\n',' ')
full_review
#top 100 Full review of iphone 11

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         full_review
0   The Best Phone for the Money\n\nThe iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.\n\nCompelling ultra-wide camera\nNew Night mode is excellent\nLong battery life
1   Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .
2   Amazing Powerful and Durable Gadget.\n\nI’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.\n\nI shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.\n\nDon’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.\n\nI’ve attached my puppy pics and no filter used just in day light capture and see the quality for comparison.
3   Previously I was using one plus 3t it was a great phone\nAnd then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11\nI have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display\nBut I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red\nMy experience after using 3 weeks\n1. The delivery was on time and I came in good packaging\n2. First impression were awesome the display is not as bad as it is written in the spec list it’s the high quality LCD Panel that you will get in any phone and using dark made/light mode will not make any difference since it’s an LCD panel\n3. Cameras were excellent even in the night 5? I have also uploaded some sample images\n4. Performance mind blowing Apple A13 chip is super fast everything is buttery smooth\n5. Battery 3110 mah and the optimisation of Apple and IOS 13 you will get good battery life and you will not get fast charger out of box you have to buy this separately\n\nThe final thing I wanna say is if you are on a budget of 60-70 go for the iPhone 11 and If you have enough money go for the iPhone 11 Pro Max don’t buy the iPhone 11 Pro (My opinion)\nOr you can get iPhone 11 and Apple Watch series 5 with same price of 11 pro\nThe phone is great you will not regret after buying it go for it ??
4   So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome
..                                                                                                                                                                                                                                       ...
95  Awesome camera, smooth and fast UI, display is great (though not LED) but the black area at the top could have been reduced. Battery remains a day even if used heavily. Charger in the box is ok, but 12 or 18W could have been nothing like anything. Overall an excellent product and comfortable to use. I have got it almost a month back and so far so good.
96  They are selling cheep quality items. There is a black line on the edge of the display. Waiting for the replacement..\n\nUpdate:today I got the replacement from flipkart.. The second one is nice and the display and camera quality is much better than the previous one.. Thanks for the support
97  I write this review after using a week this iPhone 11.\nI'm 6 Years Old Android User and this is my first iPhone. Basically I searched for a phone with a Great Camera and Video Quality for Making YouTube Videos My Budget was around 40-50k then I search a lot on the Internet. Then I finally decide to buy this phone. I've been using this phone for about a week and I purchased this phone at 45K and I'm really happy with that. Its Software Integration with Processor is Just Awesome! This phone can easily beat any Android Smartphone which comes with a flagship-grade processor. I thought its display is not too good then its upper iPhones but I was wrong Its display is so Bright and Buttery Smooth. Its video quality is beyond my expectations. If you want to see the Unboxing of My iPhone 11 then you can see it on my YouTube Channel "Vishwas Kaushik" I really Happy with this product from Apple at this Price Thanks Flipkart.
98  Everything is perfect pictures come out so clearly and at first I wasn’t sure when I got it then when I started to use it and get the hang of it it was amazing!! I can’t wait to see what the next future phones will be like. The screen display on this bad boy are unbelievable they are so clear and never fail me. The performance is super cool there is a lot of cool features as well I like this phone because I feel that it is easy to use and one of my favorite things about this phone is the Face ID!! It is just remarkable and easy to get into my phone instead of doing the whole password which sometimes takes ages!! Overall I think this is the best phone yet to be built!! I used to have a really old phone like the iPhone 6s which is a big step up. This iPhone 6s wasn’t the best at taking pictures
99  The best all rounder iphone. Flipkart is doing a great job. They're delivery services are blazing fast. I got delivery on the same day. Genuine Apple Product. Working great. Talking about review There's no need of review for iphones. They're simply the best.

[100 rows x 1 columns]

In [805]:
full_review=[]
for j in range(0,11):
    for i in driver.find_elements_by_xpath("//div[@class='t-ZTKy']"):
        if len(full_review)<100:
            try:
                driver.find_element_by_xpath("//span[@class='_1BWGvX']").click()
                full_review.append(i.text)
            
            except NoSuchElementException:
                full_review.append(i.text) 
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
full_review = pd.DataFrame(full_review)
full_review.columns=['full_review']
full_review['full_review']=full_review['full_review'].str.replace('\n',' ')
full_review
#top 100 Full review of iphone 11

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            full_review
0   The Best Phone for the Money  The iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price.  Compelling ultra-wide camera New Night mode is excellent Long battery life
1   Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .
2   Amazing Powerful and Durable Gadget.  I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone.  I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years.  Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb.  I’ve attached my puppy pics and no filter used just in day light capture and see the quality for comparison.
3   Previously I was using one plus 3t it was a great phone And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red My experience after using 3 weeks 1. The delivery was on time and I came in good packaging 2. First impression were awesome the display is not as bad as it is written in the spec list it’s the high quality LCD Panel that you will get in any phone and using dark made/light mode will not make any difference since it’s an LCD panel 3. Cameras were excellent even in the night 5? I have also uploaded some sample images 4. Performance mind blowing Apple A13 chip is super fast everything is buttery smooth 5. Battery 3110 mah and the optimisation of Apple and IOS 13 you will get good battery life and you will not get fast charger out of box you have to buy this separately  The final thing I wanna say is if you are on a budget of 60-70 go for the iPhone 11 and If you have enough money go for the iPhone 11 Pro Max don’t buy the iPhone 11 Pro (My opinion) Or you can get iPhone 11 and Apple Watch series 5 with same price of 11 pro The phone is great you will not regret after buying it go for it ??
4   So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome
..                                                                                                                                                                                                                                       ...
95  Well , as we all know if its not an Iphone , its not an iphone . The iphones are always beast . The camera game has been level up . The A13 Bionic is just fabulous . The update this year are certainly the camera which is damn good with d addition of wide angle lens as well as ultra wide . If anyones purchasing an iphone for the first time , do opt for the black color . Its just feels more than premium . Battery life is damn good with lasting fully a day . Overall a nice package . Well managed and timely delivery by flipkart always . Cheers to FLIPKART 🤘🏻
96  A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11
97  Nice value for money good and best price I phone mind blowing camera processor very fast other android mobile I am happy India top selling phone 2020
98  Just an awesome phone...upgraded from 6s to 11 and trust me guys it's super cool with amazing features..loved it ♥️ and a big thank you to Flipkart for delivering it in just 2 days ?
99  As usual a great product from Apple. but the look wise there were some scope to make it more attractive. from the back it looks nice. picture quality is awesome . face id is blazing fast. The lightning fast bionic processor makes the phone butter smooth.Battery back up is unbeatable and best of the released iPhone.full display is still missing. however, a iPhone is a iPhone. The iPhone lovers know the value of an iPhone 🙂

[100 rows x 1 columns]

In [806]:
iphone11reviews=pd.DataFrame({})
iphone11reviews['Rating']=rate['rate']
iphone11reviews['Review']=review['review']
iphone11reviews['Full_review']=full_review['full_review']
iphone11reviews
# 100 reviews data from flipkart.com for iphone11

,Rating,Review,Full_review
0,5,Brilliant,"The Best Phone for the Money The iPhone 11 offers superb cameras, a more durable design and excellent battery life for an affordable price. Compelling ultra-wide camera New Night mode is excellent Long battery life"
1,5,Perfect product!,Amazing phone with great cameras and better battery which gives you the best performance. I just love the camera .
2,5,Great product,"Amazing Powerful and Durable Gadget. I’m am very happy with the camera picture quality, Amazing face id unlocked in dark room, Strong battery with perfect screen size as you can carry easily in pocket. This is my third iPhone. I shifted from android Samsung Note series to iPhone because of the strong build quality and peace of mind for next 3-4 years. Don’t think to much just go for it and I suggest you to go for minimum 128gb variant or more 256gb. I’ve attached my puppy pics and no filter used just in day light capture and see the quality for comparison."
3,5,Worth every penny,Previously I was using one plus 3t it was a great phone And then I decided to upgrade I am stuck between Samsung s10 plus or iPhone 11 I have seen the specs and everything were good except the display it’s somewhere between 720-1080 and it’s not even an amoled it’s an LCD display But I decided to go with iPhone because I have never used an IOS device I have Been an android user from the past 9 years I ordered IPhone 11 (128gb) product red My experience after using 3 weeks 1. The delivery was on time and I came in good packaging 2. First impression were awesome the display is not as bad as it is written in the spec list it’s the high quality LCD Panel that you will get in any phone and using dark made/light mode will not make any difference since it’s an LCD panel 3. Cameras were excellent even in the night 5? I have also uploaded some sample images 4. Performance mind blowing Apple A13 chip is super fast everything is buttery smooth 5. Battery 3110 mah and the optimisation of Apple and IOS 13 you will get good battery life and you will not get fast charger out of box you have to buy this separately The final thing I wanna say is if you are on a budget of 60-70 go for the iPhone 11 and If you have enough money go for the iPhone 11 Pro Max don’t buy the iPhone 11 Pro (My opinion) Or you can get iPhone 11 and Apple Watch series 5 with same price of 11 pro The phone is great you will not regret after buying it go for it ??
4,4,Good choice,So far it’s been an AMAZING experience coming back to iOS after nearly a decade but it’s not as versatile as android though phone is sturdy dropped it accidentally a couple of times and nothing happened fortunately camera is awesome
...,...,...,...
95,5,Excellent,"Well , as we all know if its not an Iphone , its not an iphone . The iphones are always beast . The camera game has been level up . The A13 Bionic is just fabulous . The update this year are certainly the camera which is damn good with d addition of wide angle lens as well as ultra wide . If anyones purchasing an iphone for the first time , do opt for the black color . Its just feels more than premium . Battery life is damn good with lasting fully a day . Overall a nice package . Well managed and timely delivery by flipkart always . Cheers to FLIPKART 🤘🏻"
96,5,Fabulous!,A perfect phone and a good battery super camera and the sound is dynamic overall the phone is perfect for upgrading from lower iPhone model to iPhone 11
97,5,Wonderful,Nice value for money good and best price I phone mind blowing camera processor very fast other android mobile I am happy India top selling phone 2020
98,5,Fabulous!,Just an awesome phone...upgraded from 6s to 11 and trust me guys it's super cool with amazing features..loved it ♥️ and a big thank you to Flipkart for delivering it in just 2 days ?
99,5,Value-for-money,"As usual a great product from Apple. but the look wise there were some scope to make it more attractive. from the back it looks nice. picture quality is awesome . face id is blazing fast. The lightning fast bionic processor makes the phone butter smooth.Battery back up is unbeatable and best of the released iPhone.full display is still missing. however, a iPhone is a iPhone. The iPhone lovers know the value of an iPhone 🙂"

Q8: Scrape data for first 100 sneakers you find when you visit flipkart.com and
search for “sneakers” in the search field.

In [52]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.flipkart.com/'
driver.get(url)

In [53]:
flipkart2=driver.find_element_by_xpath("//input[@type='text']")
flipkart2

In [54]:
flipkart2.send_keys(Keys.CONTROL + "a")
flipkart2.send_keys(Keys.DELETE)
#clearing text in search box

In [55]:
flipkart2.send_keys("sneakers") #enters "sneakers" in search bar

In [56]:
search_btn8=driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn8.click() #click on search button

In [51]:
brand1=[]
for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        if len(brand1)<100:
            brand1.append(j.text)
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(4)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(4)
brand1 = pd.DataFrame(brand1)
brand1.columns=['brand1']
brand1
# first 100 sneakers brand name

          brand1
0       PEHANOSA
1         DUCATI
2   Robbie jones
3       HOTSTYLE
4   Robbie jones
..           ...
95      Bersache
96      Wen Hawk
97       Airland
98      HOTSTYLE
99   casualpoint

[100 rows x 1 columns]

In [57]:
brand1=[]
shoedesc=[]
price1=[]
discount1=[]


for i in range(0,3):
    for j in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"):
        if len(brand1)<100:
            brand1.append(j.text)
    
    
    
    for j in driver.find_elements_by_xpath("//div[@class='_2B099V']/a"):
        if len(shoedesc)<200:
            shoedesc.append(j.get_attribute('title'))    
    
    
    
    for j in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        if len(price1)<100:
            price1.append(j.text)
            
    
    
    for j in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        if len(discount1)<100:
            discount1.append(j.text)            
          
    
    
    
    try:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][2]").click()
        sleep(8)
    except NoSuchElementException:
        driver.find_element_by_xpath("//a[@class='_1LKTO3'][1]").click()
        sleep(8)
        
# first 100 sneakers brand name

brand1 = pd.DataFrame(brand1)
brand1.columns=['brand1']

# first 100 sneakers brand description

shoedesc = pd.DataFrame(shoedesc)
shoedesc.columns=['shoedesc']
shoedesc=shoedesc.iloc[range(0,len(shoedesc),2)] 
shoedesc=shoedesc.reset_index(drop=True)  #resetting index


# first 100 sneakers price

price1 = pd.DataFrame(price1)
price1.columns=['price1']

# first 100 sneakers discount

discount1 = pd.DataFrame(discount1)
discount1.columns=['discount1']

In [58]:
Sneakers=pd.DataFrame({})
Sneakers['Brand']=brand1['brand1']
Sneakers['Product_description']=shoedesc['shoedesc']
Sneakers['Price1']=price1['price1']
Sneakers['Discount1']=discount1['discount1']
Sneakers
#data of first 100 sneakers listings on flipkart.com

,Brand,Product_description,Price1,Discount1
0,PEHANOSA,Sneakers For Men,₹499,50% off
1,DUCATI,Sneakers For Men,"₹1,924",47% off
2,Robbie jones,Casual Sneakers Shoes For Men Sneakers For Men,₹379,62% off
3,HOTSTYLE,Sneakers Sneakers For Men,₹283,43% off
4,Robbie jones,Sneakers For Men,₹474,52% off
...,...,...,...,...
95,Englewood,White Shoes For Men | Casual White Laceups Sho...,₹499,46% off
96,Airland,shoe Sneakers For Men,₹265,40% off
97,HOTSTYLE,Sneakers Sneakers For Men,₹299,52% off
98,Robbie jones,Sneakers For Men,₹474,69% off
99,SHURAB,sneakers men sports shoes | Casual Sneakers Sh...,₹399,67% off

Q9: Go to the link - https://www.myntra.com/shoes
Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”, as shown in
the below image

In [1000]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.myntra.com/shoes'
driver.get(url)

In [1001]:
filter_button=driver.find_element_by_xpath("(//div[@class='common-checkboxIndicator'])[16]")
filter_button.click() #clicks on '6589.0 TO 13059.0' price filter

In [1002]:
filter_button=driver.find_element_by_xpath("(//div[@class='common-checkboxIndicator'])[18]")
filter_button.click() #clicks on 'Black' color filter

In [1008]:
prodbrand1=[]
proddesc=[]
prodprice=[]

for i in range(0,3):
    
    for j in driver.find_elements_by_xpath("(//h3[@class='product-brand'])"):
        if len(prodbrand1)<100:
            prodbrand1.append(j.text)
    
    
    
    
    for j in driver.find_elements_by_xpath("(//h4[@class='product-product'])"):
        if len(proddesc)<100:
            proddesc.append(j.text)

    
    
    for j in driver.find_elements_by_xpath("(//div[@class='product-price'])/span[1]"):
        if len(prodprice)<100:
            prodprice.append(j.text)
    Next_button=driver.find_element_by_xpath("(//span[@class='pagination-arrowRight'])")
    Next_button.click()
    sleep(6)    

#first 100 shoes brand's on myntra.com in black color and price range of "6589.0 TO 13059.0"    
prodbrand1 = pd.DataFrame(prodbrand1)
prodbrand1.columns=['prodbrand1']

#first 100 shoes brand's product description on myntra.com in black color and price range of "6589.0 TO 13059.0"
proddesc = pd.DataFrame(proddesc)
proddesc.columns=['proddesc']

#first 100 shoes brand's price on myntra.com in black color and price range of "6589.0 TO 13059.0"
prodprice = pd.DataFrame(prodprice)
prodprice.columns=['prodprice']
prodprice['prodprice'] = prodprice['prodprice'].str[4:9]
prodprice['prodprice']=prodprice['prodprice'].str.replace('R','')

In [1009]:
myntra=pd.DataFrame({})
myntra['Brand']=prodbrand1['prodbrand1']
myntra['Short Shoe description']=proddesc['proddesc']
myntra['Discount1']=prodprice['prodprice']
myntra
#data of first 100 shoes brands, Short Shoe descriptio and price of the shoe 
#on myntra.com in black color and price range of "6589.0 TO 13059.0"

                   Brand          Short Shoe description Discount1
0   Nike                  AIR ZOOM PEGASUS Running Shoes  11495
1   Nike                  Men AIR ZOOM Running Shoes      7721
2   Nike                  Men KD13 EP Basketball Shoes    12995
3   Nike                  Men React Infinity Running      11621
4   PUMA Motorsport       Unisex Mercedes Running Shoes   7999
..              ...                                 ...    ...
95  Heel & Buckle London  Women Leather Pumps             7192
96  Nike                  Men AIR ZOOM PEGASUS 38 Run     8995
97  Geox                  Women Solid Flatforms           6749
98  UNDER ARMOUR          Men Charged Bandit 6 Running    7649
99  Geox                  Women Leather Boat Shoes        8990

[100 rows x 3 columns]

Q10: Go to webpage https://www.amazon.in/
 Enter “Laptop” in the search field and then click the search icon.
 Then set CPU Type filter to “Intel Core i7” and “Intel Core i9” as shown in the
below image:

In [4]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.amazon.in/'
driver.get(url)

In [5]:
search_job10=driver.find_element_by_id('twotabsearchtextbox')
search_job10 # keyowrd search bar

In [6]:
search_job10.send_keys('Laptop') #enters'Laptop' in keyword search bar

In [7]:
search=driver.find_element_by_id('nav-search-submit-button')
search.click() #clicks on search button

In [8]:
#intel core 17

filter_button=driver.find_elements_by_xpath("(//span[@class='a-size-base a-color-base'])")
for i in filter_button:
    if i.text=='Intel Core i7':
        i.click()
        break

In [9]:
laptitle=[]
for j in driver.find_elements_by_xpath("(//span[@class='a-size-medium a-color-base a-text-normal'])"):
    if len(laptitle)<10:
        laptitle.append(j.text)

laptitle = pd.DataFrame(laptitle)
laptitle.columns=['laptitle']
laptitle
#top 10 laptops for i7 in amazon.com

                                            laptitle
0  Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...
1  Lenovo Yoga Slim 7 10th Gen Intel Core i7 14 i...
2  Mi Notebook Horizon Edition 14 Intel Core i5-1...
3  HP 2019 Probook 440 G6 14 Inch HD Business Lap...
4  Asus ROG Zephyrus S Ultra Slim Gaming Laptop, ...
5  Lenovo Legion 5Pi 10th Gen Intel Core i7 15.6"...
6  (Renewed) Dell Intel 4th Gen Core i7 4600U 14-...
7  Lenovo Legion Y540 Intel Core i7 9th Gen 15.6”...
8  Lenovo Yoga Slim 7i 11th Gen Intel Core i7 14"...
9  CUK VivoBook K571 by ASUS 15 Inch Gaming Lapto...

In [10]:
lapprice=[]
for j in driver.find_elements_by_xpath("(//span[@class='a-price-whole'])"):
    if len(lapprice)<10:
        lapprice.append(j.text)

lapprice = pd.DataFrame(lapprice)
lapprice.columns=['lapprice']
lapprice
#top 10 laptop's price for i7 in amazon.com

   lapprice
0    83,990
1    83,990
2    53,999
3  1,35,386
4  3,43,099
5  1,35,490
6    39,999
7    68,990
8    97,990
9  1,44,643

In [12]:
ratingurli7=[] #scraping all urls of first 10 i7 laptops
for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a"):
    if len(ratingurli7)<10:
        ratingurli7.append(i.get_attribute('href'))
ratingurli7

['https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_computers_sr_pg1_1?ie=UTF8&adId=A04686372EO1LCBF9AV16&url=%2FLenovo-Touchscreen-Fingerprint-Graphite-82HS0092IN%2Fdp%2FB08WRZQBQ6%2Fref%3Dsr_1_1_sspa%3Fdchild%3D1%26keywords%3DLaptop%26qid%3D1621656769%26refinements%3Dp_n_feature_thirteen_browse-bin%253A12598163031%26rnid%3D12598141031%26s%3Dcomputers%26sr%3D1-1-spons%26psc%3D1&qualifier=1621656769&id=1948385856452844&widgetName=sp_atf',
 'https://www.amazon.in/gp/slredirect/picassoRedirect.html/ref=pa_sp_atf_computers_sr_pg1_1?ie=UTF8&adId=A0372319347VE4FKU20UM&url=%2FLenovo-Laptop-Windows-Graphics-82A1009KIN%2Fdp%2FB087D38ZP4%2Fref%3Dsr_1_2_sspa%3Fdchild%3D1%26keywords%3DLaptop%26qid%3D1621656769%26refinements%3Dp_n_feature_thirteen_browse-bin%253A12598163031%26rnid%3D12598141031%26s%3Dcomputers%26sr%3D1-2-spons%26psc%3D1&qualifier=1621656769&id=1948385856452844&widgetName=sp_atf',
 'https://www.amazon.in/Notebook-Horizon-i5-10210U-Graphics-XMA1904-AR/dp/B089F5JGM1/ref=sr_1_3?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-3',
 'https://www.amazon.in/HP-440-G6-Laptop-Professional/dp/B07VRKML6Q/ref=sr_1_4?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-4',
 'https://www.amazon.in/Asus-Zephyrus-GeForce-i7-8750H-GX531GW-AS76/dp/B07KS1JF2H/ref=sr_1_5?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-5',
 'https://www.amazon.in/Lenovo-Legion-Gaming-Windows-82AW005SIN/dp/B08CQ21154/ref=sr_1_6?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-6',
 'https://www.amazon.in/Renewed-Dell-1366x768-Graphics-Lattitude/dp/B08RS41X61/ref=sr_1_7?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-7',
 'https://www.amazon.in/Lenovo-Legion-Gaming-GeForce-81SY00U7IN/dp/B092MRQCJ6/ref=sr_1_8?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-8',
 'https://www.amazon.in/Lenovo-Graphics-Fingerprint-Aluminium-82A3009QIN/dp/B08ZNLVSPG/ref=sr_1_9?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-9',
 'https://www.amazon.in/VivoBook-GeForce-Windows-Notebook-Computer/dp/B08CHP2TJC/ref=sr_1_10?dchild=1&keywords=Laptop&qid=1621656769&refinements=p_n_feature_thirteen_browse-bin%3A12598163031&rnid=12598141031&s=computers&sr=1-10']

In [13]:
lapratingi7=[]
for i in ratingurli7:
    url=i
    driver.get(url)
    sleep(4)
    try:
        ratingi7=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")
        lapratingi7.append(ratingi7.text)
    except NoSuchElementException:
        lapratingi7.append('None')
lapratingi7 = pd.DataFrame(lapratingi7)            
lapratingi7.columns=['laprating']
lapratingi7

      laprating
0    4 out of 5
1  3.2 out of 5
2  4.4 out of 5
3    5 out of 5
4  4.3 out of 5
5  4.3 out of 5
6          None
7  4.1 out of 5
8          None
9  4.7 out of 5

In [14]:
laptopi7=pd.DataFrame({})
laptopi7['Title']=laptitle['laptitle']
laptopi7['Price']=lapprice['lapprice']
laptopi7['Rating']=lapratingi7['laprating']
laptopi7
#first 10 i7 laptop's Title, price and ratings

                                               Title     Price        Rating
0  Lenovo IdeaPad Flex 5 11th Gen Intel Core i7 1...    83,990    4 out of 5
1  Lenovo Yoga Slim 7 10th Gen Intel Core i7 14 i...    83,990  3.2 out of 5
2  Mi Notebook Horizon Edition 14 Intel Core i5-1...    53,999  4.4 out of 5
3  HP 2019 Probook 440 G6 14 Inch HD Business Lap...  1,35,386    5 out of 5
4  Asus ROG Zephyrus S Ultra Slim Gaming Laptop, ...  3,43,099  4.3 out of 5
5  Lenovo Legion 5Pi 10th Gen Intel Core i7 15.6"...  1,35,490  4.3 out of 5
6  (Renewed) Dell Intel 4th Gen Core i7 4600U 14-...    39,999          None
7  Lenovo Legion Y540 Intel Core i7 9th Gen 15.6”...    68,990  4.1 out of 5
8  Lenovo Yoga Slim 7i 11th Gen Intel Core i7 14"...    97,990          None
9  CUK VivoBook K571 by ASUS 15 Inch Gaming Lapto...  1,44,643  4.7 out of 5

First 10 i9 laptop's Title, price and ratings

In [15]:
driver=webdriver.Chrome("chromedriver.exe")
url='https://www.amazon.in/'
driver.get(url)

In [16]:
search_job11=driver.find_element_by_id('twotabsearchtextbox')
search_job11 # keyowrd search bar

In [17]:
search_job11.send_keys('Laptop') #enters'Laptop' in keyword search bar

In [18]:
search2=driver.find_element_by_id('nav-search-submit-button')
search2.click() #clicks on search button

In [20]:
#intel core 19

filter_button=driver.find_elements_by_xpath("(//span[@class='a-size-base a-color-base'])")
for i in filter_button:
    if i.text=='Intel Core i9':
        i.click()
        break

In [21]:
laptitle1=[]
for j in driver.find_elements_by_xpath("(//span[@class='a-size-medium a-color-base a-text-normal'])"):
    if len(laptitle1)<10:
        laptitle1.append(j.text)

laptitle1 = pd.DataFrame(laptitle1)
laptitle1.columns=['laptitle']
laptitle1
#top 10 laptops for i9 in amazon.com

                                            laptitle
0  ASUS ZenBook Pro Duo Intel Core i9-10980HK 10t...
1  ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 1...
2  Dell XPS 9570 15.6" (39.62cms) UHD Laptop (8th...
3  Lenovo Legion 7 10th Gen Intel Core i9 15.6 in...
4  ASUS ROG Zephyrus Duo 15, 15.6" FHD 300Hz/3ms,...
5  ASUS ZenBook Pro Duo UX581GV-H2041T Intel Core...
6  ASUS ROG Strix Scar 17 (2020), 17.3" FHD 300Hz...
7  ASUS ROG Strix Scar 15 (2020), 15.6" FHD 300Hz...
8  (Renewed) Dell XPS 9570 Laptop|i9-8950HK|32GB ...
9  Dell G7 7500 15.6inch FHD 300 Hz Display Gamin...

In [22]:
lapprice1=[]
for j in driver.find_elements_by_xpath("(//span[@class='a-price-whole'])"):
    if len(lapprice1)<10:
        lapprice1.append(j.text)

lapprice1 = pd.DataFrame(lapprice1)
lapprice1.columns=['lapprice']
lapprice1
#top 10 laptop's price for i9 in amazon.com

   lapprice
0  2,99,325
1  4,13,890
2  2,48,790
3  2,62,990
4  2,66,990
5  2,79,990
6  2,77,490
7  2,15,990
8  1,89,900
9  2,00,690

In [23]:
ratingurli9=[] #scraping all urls of first 10 job's full description
for i in driver.find_elements_by_xpath("//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']/a"):
    if len(ratingurli9)<10:
        ratingurli9.append(i.get_attribute('href'))
ratingurli9

['https://www.amazon.in/ASUS-i9-10980HK-Touchscreen-Celestial-UX581LV-H2035T/dp/B08CHDLVT1/ref=sr_1_1?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-1',
 'https://www.amazon.in/Asus-G703GI-E5148T-17-3-inch-i9-8950HK-Processor/dp/B07GRCW51K/ref=sr_1_2?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-2',
 'https://www.amazon.in/Dell-9570-15-6-inch-i9-8950HK-Integrated/dp/B08C5FMBLB/ref=sr_1_3?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-3',
 'https://www.amazon.in/Lenovo-Legion-Windows-Graphics-81YU006HIN/dp/B08GG9RZJC/ref=sr_1_4?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-4',
 'https://www.amazon.in/ASUS-Zephyrus-i9-10980HK-RTX-2080-SUPER-Max-Q-GX550LXS-HF168TS/dp/B08PFBB6RG/ref=sr_1_5?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-5',
 'https://www.amazon.in/ASUS-UX581GV-H2041T-Touchscreen-ScreenPad-Celestial/dp/B08521KLH6/ref=sr_1_6?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-6',
 'https://www.amazon.in/ASUS-Strix-Scar-i9-10980HK-RTX-2080-Super-G732LXS-HG059T/dp/B08GQZWVL9/ref=sr_1_7?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-7',
 'https://www.amazon.in/ASUS-i9-10980HK-Graphics-Windows-G532LWS-HF079T/dp/B08HX42DGG/ref=sr_1_8?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-8',
 'https://www.amazon.in/Renewed-Dell-XPS-i9-8950HK-Backlit/dp/B08X6DJVYR/ref=sr_1_9?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-9',
 'https://www.amazon.in/15-6inch-i9-10885H-Graphics-Warranty-D560233WIN9B/dp/B08HYPJDLD/ref=sr_1_10?dchild=1&keywords=Laptop&qid=1621657856&refinements=p_n_feature_thirteen_browse-bin%3A16757432031&rnid=12598141031&s=computers&sr=1-10']

In [24]:
lapratingi9=[]
for i in ratingurli9:
    url=i
    driver.get(url)
    sleep(4)
    try:
        ratingi9=driver.find_element_by_xpath("//span[@class='a-size-medium a-color-base']")
        lapratingi9.append(ratingi9.text)
    except NoSuchElementException:
        lapratingi9.append('None')
lapratingi9 = pd.DataFrame(lapratingi9)            
lapratingi9.columns=['laprating']
lapratingi9

      laprating
0  3.8 out of 5
1  3.7 out of 5
2  2.4 out of 5
3  3.7 out of 5
4          None
5  3.9 out of 5
6  4.8 out of 5
7  4.2 out of 5
8          None
9  3.4 out of 5

In [25]:
laptopi9=pd.DataFrame({})
laptopi9['Title']=laptitle1['laptitle']
laptopi9['Price']=lapprice1['lapprice']
laptopi9['Rating']=lapratingi9['laprating']
laptopi9
#first 10 i9 laptop's Title, price and ratings

                                               Title     Price        Rating
0  ASUS ZenBook Pro Duo Intel Core i9-10980HK 10t...  2,99,325  3.8 out of 5
1  ASUS ROG G703GI-E5148T 17.3" (43.94 cms) FHD 1...  4,13,890  3.7 out of 5
2  Dell XPS 9570 15.6" (39.62cms) UHD Laptop (8th...  2,48,790  2.4 out of 5
3  Lenovo Legion 7 10th Gen Intel Core i9 15.6 in...  2,62,990  3.7 out of 5
4  ASUS ROG Zephyrus Duo 15, 15.6" FHD 300Hz/3ms,...  2,66,990          None
5  ASUS ZenBook Pro Duo UX581GV-H2041T Intel Core...  2,79,990  3.9 out of 5
6  ASUS ROG Strix Scar 17 (2020), 17.3" FHD 300Hz...  2,77,490  4.8 out of 5
7  ASUS ROG Strix Scar 15 (2020), 15.6" FHD 300Hz...  2,15,990  4.2 out of 5
8  (Renewed) Dell XPS 9570 Laptop|i9-8950HK|32GB ...  1,89,900          None
9  Dell G7 7500 15.6inch FHD 300 Hz Display Gamin...  2,00,690  3.4 out of 5