In [3]:
#importing all the required libraries
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
from time import sleep
from selenium.common.exceptions import NoSuchElementException   # importing Exemption
import warnings
warnings.filterwarnings('ignore')

In [4]:
pd.set_option("display.max_colwidth", -1) #displays whole column value

In [4]:
driver=webdriver.Chrome("chromedriver.exe")

In [5]:
url='https://www.olx.in/'
driver.get(url)

In [6]:
search=driver.find_element_by_xpath("/html/body/div[1]/div/header/div/div/div[2]/div/div/div[2]/div/form/fieldset/div/input")
search # keyword search bar

In [7]:
search.send_keys('Used Cars') #enters'Laptop' in keyword search bar

In [8]:
search=driver.find_element_by_xpath('/html/body/div[1]/div/header/div/div/div[2]/div/div/div[3]')
search.click() #clicks on search button

In [41]:
producturl=[] 
for i in range(0,24):
    for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
                producturl.append(j.get_attribute('href'))
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(5)
producturl

['https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/mahindra-xylo-d4-2018-diesel-iid-1645309437',
 'https://www.olx.in/item/mahindra-xylo-d4-2016-diesel-iid-1644907442',
 'https://www.olx.in/item/ford-mustang-v8-2017-petrol-iid-1648403861',
 'https://www.olx.in/item/honda-city-2015-2017-i-dtec-e-2015-diesel-iid-1645168372',
 'https://www.olx.in/item/my-wagonr-company-fitted-lpg-for-sale-white-colour-top-condition-iid-1646248893',
 'https://www.olx.in/item/force-motors-others-2016-diesel-iid-1635316999',
 'https://www.olx.in/item/mahindra-scorpio-s11-2018-diesel-iid-1646746068',
 'https://www.olx.in/item/ford-ecosport-15-tdci-ambiente-2016-diesel-iid-1646745808',
 'https://www.olx.in/item/toyota-innova-25-v-8-str-2009-diesel-iid-1642714678',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2002-cng-hybrids-iid-1641925343',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/hyundai-grand-i10-sportz-12-kappa-vtvt-2017-petrol-iid-1623478215',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-iid-1648224871',
 'https://www.olx.in/item/honda-city-i-dtec-zx-2017-diesel-iid-1632219564',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1650790027',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2010-cng-hybrids-iid-1650789358',
 'https://www.olx.in/item/mahindra-xylo-d4-bs-iii-2018-diesel-iid-1649224931',
 'https://www.olx.in/item/toyota-etios-g-sp-2016-diesel-iid-1648308258',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-cng-2007-cng-amp-hybrids-iid-1647575301',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/mahindra-xylo-d4-2018-diesel-iid-1645309437',
 'https://www.olx.in/item/mahindra-xylo-d4-2016-diesel-iid-1644907442',
 'https://www.olx.in/item/ford-mustang-v8-2017-petrol-iid-1648403861',
 'https://www.olx.in/item/honda-city-2015-2017-i-dtec-e-2015-diesel-iid-1645168372',
 'https://www.olx.in/item/my-wagonr-company-fitted-lpg-for-sale-white-colour-top-condition-iid-1646248893',
 'https://www.olx.in/item/force-motors-others-2016-diesel-iid-1635316999',
 'https://www.olx.in/item/mahindra-scorpio-s11-2018-diesel-iid-1646746068',
 'https://www.olx.in/item/ford-ecosport-15-tdci-ambiente-2016-diesel-iid-1646745808',
 'https://www.olx.in/item/toyota-innova-25-v-8-str-2009-diesel-iid-1642714678',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2002-cng-hybrids-iid-1641925343',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/hyundai-grand-i10-sportz-12-kappa-vtvt-2017-petrol-iid-1623478215',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-iid-1648224871',
 'https://www.olx.in/item/honda-city-i-dtec-zx-2017-diesel-iid-1632219564',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1650790027',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2010-cng-hybrids-iid-1650789358',
 'https://www.olx.in/item/mahindra-xylo-d4-bs-iii-2018-diesel-iid-1649224931',
 'https://www.olx.in/item/toyota-etios-g-sp-2016-diesel-iid-1648308258',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-cng-2007-cng-amp-hybrids-iid-1647575301',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-tour-ldi-2016-diesel-iid-1628255310',
 'https://www.olx.in/item/toyota-fortuner-trd-sportivo-28-2wd-at-2014-diesel-iid-1650033695',
 'https://www.olx.in/item/audi-a4-30-tfsi-technology-2019-petrol-iid-1649225327',
 'https://www.olx.in/item/mahindra-xylo-h4-bs-iv-2019-diesel-iid-1642713864',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641832767',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641818898',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641815438',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2012-petrol-iid-1641118734',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-zdi-plus-2016-diesel-iid-1635891459',
 'https://www.olx.in/item/honda-city-zx-cvt-2007-petrol-iid-1646520068',
 'https://www.olx.in/item/hyundai-creta-16-crdi-sx-2017-diesel-iid-1646620141',
 'https://www.olx.in/item/hyundai-i20-2012-2014-sportz-14-crdi-2013-diesel-iid-1645118842',
 'https://www.olx.in/item/hyundai-accent-2012-cng-hybrids-iid-1650783224',
 'https://www.olx.in/item/mahindra-scorpio-2015-diesel-iid-1646195747',
 'https://www.olx.in/item/3bhk-4bhk-2bhk-flat-floor-plot-kothi-villa-shop-showroom-2-3-4-bhk-car-iid-1622553892',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1618719550',
 'https://www.olx.in/item/maruti-suzuki-ertiga-lxi-2018-cng-hybrids-iid-1650034495',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-vdi-bsiii-2010-diesel-iid-1649225800',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/mahindra-xylo-d4-2018-diesel-iid-1645309437',
 'https://www.olx.in/item/mahindra-xylo-d4-2016-diesel-iid-1644907442',
 'https://www.olx.in/item/ford-mustang-v8-2017-petrol-iid-1648403861',
 'https://www.olx.in/item/honda-city-2015-2017-i-dtec-e-2015-diesel-iid-1645168372',
 'https://www.olx.in/item/my-wagonr-company-fitted-lpg-for-sale-white-colour-top-condition-iid-1646248893',
 'https://www.olx.in/item/force-motors-others-2016-diesel-iid-1635316999',
 'https://www.olx.in/item/mahindra-scorpio-s11-2018-diesel-iid-1646746068',
 'https://www.olx.in/item/ford-ecosport-15-tdci-ambiente-2016-diesel-iid-1646745808',
 'https://www.olx.in/item/toyota-innova-25-v-8-str-2009-diesel-iid-1642714678',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2002-cng-hybrids-iid-1641925343',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/hyundai-grand-i10-sportz-12-kappa-vtvt-2017-petrol-iid-1623478215',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-iid-1648224871',
 'https://www.olx.in/item/honda-city-i-dtec-zx-2017-diesel-iid-1632219564',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1650790027',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2010-cng-hybrids-iid-1650789358',
 'https://www.olx.in/item/mahindra-xylo-d4-bs-iii-2018-diesel-iid-1649224931',
 'https://www.olx.in/item/toyota-etios-g-sp-2016-diesel-iid-1648308258',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-cng-2007-cng-amp-hybrids-iid-1647575301',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-tour-ldi-2016-diesel-iid-1628255310',
 'https://www.olx.in/item/toyota-fortuner-trd-sportivo-28-2wd-at-2014-diesel-iid-1650033695',
 'https://www.olx.in/item/audi-a4-30-tfsi-technology-2019-petrol-iid-1649225327',
 'https://www.olx.in/item/mahindra-xylo-h4-bs-iv-2019-diesel-iid-1642713864',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641832767',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641818898',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641815438',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2012-petrol-iid-1641118734',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-zdi-plus-2016-diesel-iid-1635891459',
 'https://www.olx.in/item/honda-city-zx-cvt-2007-petrol-iid-1646520068',
 'https://www.olx.in/item/hyundai-creta-16-crdi-sx-2017-diesel-iid-1646620141',
 'https://www.olx.in/item/hyundai-i20-2012-2014-sportz-14-crdi-2013-diesel-iid-1645118842',
 'https://www.olx.in/item/hyundai-accent-2012-cng-hybrids-iid-1650783224',
 'https://www.olx.in/item/mahindra-scorpio-2015-diesel-iid-1646195747',
 'https://www.olx.in/item/3bhk-4bhk-2bhk-flat-floor-plot-kothi-villa-shop-showroom-2-3-4-bhk-car-iid-1622553892',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1618719550',
 'https://www.olx.in/item/maruti-suzuki-ertiga-lxi-2018-cng-hybrids-iid-1650034495',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-vdi-bsiii-2010-diesel-iid-1649225800',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-2010-petrol-iid-1647250858',
 'https://www.olx.in/item/honda-city-vx-cvt-2016-petrol-iid-1644348075',
 'https://www.olx.in/item/mini-cooper-d-5-door-2017-diesel-iid-1641926834',
 'https://www.olx.in/item/mercedes-benz-r-class-r350-cdi-4matic-2013-diesel-iid-1641926308',
 'https://www.olx.in/item/toyota-innova-25-g-diesel-7-seater-2007-diesel-iid-1623313017',
 'https://www.olx.in/item/hyundai-grand-i10-2013-2016-crdi-asta-2014-diesel-iid-1622489659',
 'https://www.olx.in/item/renault-lodgy-110-ps-rxz-7-str-stepway-2015-diesel-iid-1617219895',
 'https://www.olx.in/item/nissan-micra-2010-2012-diesel-xv-2011-diesel-iid-1607075404',
 'https://www.olx.in/item/toyota-fortuner-30-4x4-manual-2011-diesel-iid-1649224534',
 'https://www.olx.in/item/mahindra-bolero-zlx-2016-diesel-iid-1625811278',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-lxi-2011-petrol-iid-1605335846',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-ldi-option-2016-diesel-iid-1649155518',
 'https://www.olx.in/item/maruti-suzuki-eeco-5-seater-ac-2016-petrol-iid-1650495126',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-lxi-2016-petrol-iid-1647824621',
 'https://www.olx.in/item/honda-others-2007-petrol-iid-1650770266',
 'https://www.olx.in/item/ford-endeavour-2007-diesel-iid-1650769393',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2005-iid-1650831120',
 'https://www.olx.in/item/daewoo-matiz-2000-petrol-58000-km-driven-iid-1650831116',
 'https://www.olx.in/item/mpfi-gypsi-for-sale-iid-1650831109',
 'https://www.olx.in/item/maruti-suzuki-ertiga-vdi-2012-diesel-iid-1649716680',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/mahindra-xylo-d4-2018-diesel-iid-1645309437',
 'https://www.olx.in/item/mahindra-xylo-d4-2016-diesel-iid-1644907442',
 'https://www.olx.in/item/ford-mustang-v8-2017-petrol-iid-1648403861',
 'https://www.olx.in/item/honda-city-2015-2017-i-dtec-e-2015-diesel-iid-1645168372',
 'https://www.olx.in/item/my-wagonr-company-fitted-lpg-for-sale-white-colour-top-condition-iid-1646248893',
 'https://www.olx.in/item/force-motors-others-2016-diesel-iid-1635316999',
 'https://www.olx.in/item/mahindra-scorpio-s11-2018-diesel-iid-1646746068',
 'https://www.olx.in/item/ford-ecosport-15-tdci-ambiente-2016-diesel-iid-1646745808',
 'https://www.olx.in/item/toyota-innova-25-v-8-str-2009-diesel-iid-1642714678',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2002-cng-hybrids-iid-1641925343',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/hyundai-grand-i10-sportz-12-kappa-vtvt-2017-petrol-iid-1623478215',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-iid-1648224871',
 'https://www.olx.in/item/honda-city-i-dtec-zx-2017-diesel-iid-1632219564',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1650790027',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2010-cng-hybrids-iid-1650789358',
 'https://www.olx.in/item/mahindra-xylo-d4-bs-iii-2018-diesel-iid-1649224931',
 'https://www.olx.in/item/toyota-etios-g-sp-2016-diesel-iid-1648308258',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-cng-2007-cng-amp-hybrids-iid-1647575301',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',

In [29]:
# producturl=[] 
for i in range(0,24):
#     for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
#                 producturl.append(j.get_attribute('href'))
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(5)
# producturl

In [43]:
url = []
for i in producturl:
    if i not in url:
        url.append(i)

In [44]:
len(url)

442

In [46]:
url

['https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2011-diesel-iid-1644597991',
 'https://www.olx.in/item/tata-tiago-2016-diesel-iid-1647898241',
 'https://www.olx.in/item/ford-ecosport-10-ecoboost-titanium-plus-2014-petrol-iid-1632908375',
 'https://www.olx.in/item/tata-zest-2015-diesel-xms-iid-1649703131',
 'https://www.olx.in/item/opel-astra-1997-petrol-iid-1650806137',
 'https://www.olx.in/item/chevrolet-spark-2014-1o-lt-iid-1649717953',
 'https://www.olx.in/item/honda-city-2014-2015-v-mt-2014-diesel-iid-1645168358',
 'https://www.olx.in/item/honda-city-i-vtec-v-2019-petrol-iid-1629828558',
 'https://www.olx.in/item/ford-aspire-titatinium-blu-ti-vct-2016-petrol-iid-1582155753',
 'https://www.olx.in/item/jaguar-xj-l-30-diesel-2011-diesel-iid-1572884399',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-plus-2017-petrol-iid-1644969622',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-optional-2017-petrol-iid-1648191932',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zxi-petrol-2017-petrol-iid-1641224393',
 'https://www.olx.in/item/maruti-suzuki-alto-2008-petrol-iid-1650802897',
 'https://www.olx.in/item/toyota-etios-2015-diesel-iid-1650791449',
 'https://www.olx.in/item/tata-safari-2012-4x2-lx-dicor-bharat-iv-delhi-registered-iid-1648568564',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2018-diesel-41000-km-driven-iid-1648568325',
 'https://www.olx.in/item/skoda-rapid-2012-well-maintained-iid-1648567729',
 'https://www.olx.in/item/renault-kwid-climber-10-amt-2017-petrol-iid-1648404507',
 'https://www.olx.in/item/mahindra-xylo-d4-2018-diesel-iid-1645309437',
 'https://www.olx.in/item/mahindra-xylo-d4-2016-diesel-iid-1644907442',
 'https://www.olx.in/item/ford-mustang-v8-2017-petrol-iid-1648403861',
 'https://www.olx.in/item/honda-city-2015-2017-i-dtec-e-2015-diesel-iid-1645168372',
 'https://www.olx.in/item/my-wagonr-company-fitted-lpg-for-sale-white-colour-top-condition-iid-1646248893',
 'https://www.olx.in/item/force-motors-others-2016-diesel-iid-1635316999',
 'https://www.olx.in/item/mahindra-scorpio-s11-2018-diesel-iid-1646746068',
 'https://www.olx.in/item/ford-ecosport-15-tdci-ambiente-2016-diesel-iid-1646745808',
 'https://www.olx.in/item/toyota-innova-25-v-8-str-2009-diesel-iid-1642714678',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2002-cng-hybrids-iid-1641925343',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/hyundai-grand-i10-sportz-12-kappa-vtvt-2017-petrol-iid-1623478215',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-iid-1648224871',
 'https://www.olx.in/item/honda-city-i-dtec-zx-2017-diesel-iid-1632219564',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1650790027',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2010-cng-hybrids-iid-1650789358',
 'https://www.olx.in/item/mahindra-xylo-d4-bs-iii-2018-diesel-iid-1649224931',
 'https://www.olx.in/item/toyota-etios-g-sp-2016-diesel-iid-1648308258',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-cng-2007-cng-amp-hybrids-iid-1647575301',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-tour-ldi-2016-diesel-iid-1628255310',
 'https://www.olx.in/item/toyota-fortuner-trd-sportivo-28-2wd-at-2014-diesel-iid-1650033695',
 'https://www.olx.in/item/audi-a4-30-tfsi-technology-2019-petrol-iid-1649225327',
 'https://www.olx.in/item/mahindra-xylo-h4-bs-iv-2019-diesel-iid-1642713864',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641832767',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641818898',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1641815438',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2012-petrol-iid-1641118734',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-zdi-plus-2016-diesel-iid-1635891459',
 'https://www.olx.in/item/honda-city-zx-cvt-2007-petrol-iid-1646520068',
 'https://www.olx.in/item/hyundai-creta-16-crdi-sx-2017-diesel-iid-1646620141',
 'https://www.olx.in/item/hyundai-i20-2012-2014-sportz-14-crdi-2013-diesel-iid-1645118842',
 'https://www.olx.in/item/hyundai-accent-2012-cng-hybrids-iid-1650783224',
 'https://www.olx.in/item/mahindra-scorpio-2015-diesel-iid-1646195747',
 'https://www.olx.in/item/3bhk-4bhk-2bhk-flat-floor-plot-kothi-villa-shop-showroom-2-3-4-bhk-car-iid-1622553892',
 'https://www.olx.in/item/get12-returns-on-showroom-shop-flat-plot-2bhk-3bhk-4bhk-2-3-4-bhk-car-iid-1618719550',
 'https://www.olx.in/item/maruti-suzuki-ertiga-lxi-2018-cng-hybrids-iid-1650034495',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-vdi-bsiii-2010-diesel-iid-1649225800',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-2010-petrol-iid-1647250858',
 'https://www.olx.in/item/honda-city-vx-cvt-2016-petrol-iid-1644348075',
 'https://www.olx.in/item/mini-cooper-d-5-door-2017-diesel-iid-1641926834',
 'https://www.olx.in/item/mercedes-benz-r-class-r350-cdi-4matic-2013-diesel-iid-1641926308',
 'https://www.olx.in/item/toyota-innova-25-g-diesel-7-seater-2007-diesel-iid-1623313017',
 'https://www.olx.in/item/hyundai-grand-i10-2013-2016-crdi-asta-2014-diesel-iid-1622489659',
 'https://www.olx.in/item/renault-lodgy-110-ps-rxz-7-str-stepway-2015-diesel-iid-1617219895',
 'https://www.olx.in/item/nissan-micra-2010-2012-diesel-xv-2011-diesel-iid-1607075404',
 'https://www.olx.in/item/toyota-fortuner-30-4x4-manual-2011-diesel-iid-1649224534',
 'https://www.olx.in/item/mahindra-bolero-zlx-2016-diesel-iid-1625811278',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-lxi-2011-petrol-iid-1605335846',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-ldi-option-2016-diesel-iid-1649155518',
 'https://www.olx.in/item/maruti-suzuki-eeco-5-seater-ac-2016-petrol-iid-1650495126',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-lxi-2016-petrol-iid-1647824621',
 'https://www.olx.in/item/honda-others-2007-petrol-iid-1650770266',
 'https://www.olx.in/item/ford-endeavour-2007-diesel-iid-1650769393',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2005-iid-1650831120',
 'https://www.olx.in/item/daewoo-matiz-2000-petrol-58000-km-driven-iid-1650831116',
 'https://www.olx.in/item/mpfi-gypsi-for-sale-iid-1650831109',
 'https://www.olx.in/item/maruti-suzuki-ertiga-vdi-2012-diesel-iid-1649716680',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-vxi-2014-iid-1649716000',
 'https://www.olx.in/item/toyota-fortuner-30-4x2-automatic-2017-diesel-iid-1650831101',
 'https://www.olx.in/item/hyundai-verna-2006-2010-crdi-2010-diesel-iid-1643670226',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2018-diesel-well-maintained-iid-1650831096',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-vxi-2013-petrol-iid-1646912185',
 'https://www.olx.in/item/hyundai-i10-2009-petrol-85000-km-driven-iid-1650831049',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2009-petrol-iid-1645264250',
 'https://www.olx.in/item/tata-indigo-ecs-2014-iid-1650831021',
 'https://www.olx.in/item/hyundai-i10-2009-petrol-lpg-well-maintained-iid-1650830986',
 'https://www.olx.in/item/hyundai-santro-xing-gl-plus-cng-2011-cng-hybrids-iid-1650830967',
 'https://www.olx.in/item/toyota-innova-crysta-28-zx-at-2019-diesel-iid-1648126165',
 'https://www.olx.in/item/ford-ecosport-15-diesel-titanium-2018-diesel-iid-1648648647',
 'https://www.olx.in/item/bmw-x3-xdrive-20d-luxury-line-2017-diesel-iid-1646796112',
 'https://www.olx.in/item/maruti-suzuki-ertiga-2017-iid-1649315727',
 'https://www.olx.in/item/mahindra-xylo-2014-diesel-iid-1650766755',
 'https://www.olx.in/item/in-good-condition-untouched-vehicle-iid-1650830955',
 'https://www.olx.in/item/mahindra-thar-others-2021-diesel-iid-1650830949',
 'https://www.olx.in/item/tata-nano-2010-petrol-well-maintained-iid-1650830910',
 'https://www.olx.in/item/chevrolet-aveo-2008-only-52000-km-driven-iid-1650830884',
 'https://www.olx.in/item/volkswagen-polo-2012-diesel-well-maintained-iid-1650830872',
 'https://www.olx.in/item/maruti-suzuki-omni-iid-1650830870',
 'https://www.olx.in/item/maruti-suzuki-swift-2016-diesel-62000-km-driven-iid-1650830869',
 'https://www.olx.in/item/nissan-terrano-xv-d-thp-110-ps-2014-diesel-iid-1650830866',
 'https://www.olx.in/item/indica-v2-ls-2012-model-9-years-iid-1650830842',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-2016-petrol-iid-1650830802',
 'https://www.olx.in/item/hyundai-xcent-2014-petrol-38000km-iid-1650830799',
 'https://www.olx.in/item/well-maintained-ownercomedriver-iid-1650830794',
 'https://www.olx.in/item/other-brands-others-2018-diesel-iid-1650830758',
 'https://www.olx.in/item/maruti-suzuki-eeco-5-seater-ac-2016-petrol-iid-1650830731',
 'https://www.olx.in/item/good-condition-iid-1650830722',
 'https://www.olx.in/item/honda-brio-2011-2013-ex-mt-2013-petrol-iid-1642726703',
 'https://www.olx.in/item/datsun-redigo-t-2017-petrol-iid-1641837594',
 'https://www.olx.in/item/renault-duster-2013-diesel-iid-1650158548',
 'https://www.olx.in/item/audi-q3-2017-fwd-premium-petrol-with-sunroof-driven-11000-km-iid-1644614818',
 'https://www.olx.in/item/hyundai-venue-2020-diesel-iid-1647503640',
 'https://www.olx.in/item/hyundai-santro-xing-xl-2005-petrol-iid-1650830707',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-10-vxi-2004-petrol-iid-1650830699',
 'https://www.olx.in/item/maruti-suzuki-sx4-zdi-2011-diesel-iid-1650830698',
 'https://www.olx.in/item/mg-others-2020-diesel-iid-1650830693',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-vdi-bsiii-2010-diesel-iid-1650830672',
 'https://www.olx.in/item/mini-cooper-convertible-2014-2016-16-2014-petrol-iid-1650830671',
 'https://www.olx.in/item/maruti-suzuki-ertiga-2012-2015-vdi-2012-diesel-iid-1650830664',
 'https://www.olx.in/item/sony-car-system-iid-1650776283',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2018-petrol-iid-1650830638',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-10-lxi-cng-2013-cng-hybrids-iid-1650830626',
 'https://www.olx.in/item/hyundai-i20-2012-diesel-111500-km-driven-iid-1650830622',
 'https://www.olx.in/item/mani-problem-iid-1650830596',
 'https://www.olx.in/item/mahindra-rexton-2014-diesel-82500-km-driven-iid-1650830583',
 'https://www.olx.in/item/maruti-suzuki-alto-800-cng-lxi-2006-cng-hybrids-iid-1650830579',
 'https://www.olx.in/item/maruti-suzuki-ertiga-shvs-vdi-2017-diesel-iid-1629256906',
 'https://www.olx.in/item/hyundai-verna-2018-petrol-26000-km-driven-iid-1650680473',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-vxi-amt-optional-2018-petrol-iid-1650414986',
 'https://www.olx.in/item/maruti-suzuki-eeco-2018-cng-hybrids-iid-1650762086',
 'https://www.olx.in/item/hyundai-elite-i20-sportz-2018-petrol-25000-km-driven-iid-1639958668',
 'https://www.olx.in/item/tata-indica-v2-2012-iid-1650827988',
 'https://www.olx.in/item/hyundai-fluidic-verna-16-crdi-sx-2013-diesel-iid-1650830562',
 'https://www.olx.in/item/mercedes-benz-new-c-class-c-220-cdi-avantgarde-2013-diesel-iid-1650830527',
 'https://www.olx.in/item/mahindra-jeep-1986-diesel-well-maintained-iid-1650830516',
 'https://www.olx.in/item/2017-oct-model-hyundai-creta-66000-kms-iid-1220062001',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2014-petrol-iid-1650830485',
 'https://www.olx.in/item/non-commercial-car-iid-1650830479',
 'https://www.olx.in/item/maruti-suzuki-omni-lpg-bs-iv-2008-lpg-iid-1650830451',
 'https://www.olx.in/item/ford-classic-2013-lady-driven-iid-1650830446',
 'https://www.olx.in/item/2015-renault-lodgy-full-option-iid-1650830439',
 'https://www.olx.in/item/tata-indica-dlg-turbo-iid-1650830416',
 'https://www.olx.in/item/super-tracter-paper-ok-iid-1650830404',
 'https://www.olx.in/item/hyundai-santro-2002-cng-hybrids-74000-km-driven-iid-1650830403',
 'https://www.olx.in/item/full-conditions-bjaj-iid-1650830387',
 'https://www.olx.in/item/toyota-innova-crysta-2018-diesel-well-maintained-iid-1650830374',
 'https://www.olx.in/item/mahindra-xuv500-w8-2wd-2013-diesel-iid-1649335305',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-vxi-2011-petrol-iid-1650031693',
 'https://www.olx.in/item/honda-brio-2013-petrol-iid-1644015934',
 'https://www.olx.in/item/hyundai-i20-2011-petrol-iid-1640152181',
 'https://www.olx.in/item/maruti-suzuki-vitara-brezza-2016-diesel-iid-1639991107',
 'https://www.olx.in/item/ford-ecosport-2015-diesel-good-condition-iid-1650830357',
 'https://www.olx.in/item/ford-ikon-2010-petrol-70000-km-driven-2025-tak-passing-hai-iid-1643278593',
 'https://www.olx.in/item/renault-kwid-2015-petrol-60000-km-driven-iid-1643960088',
 'https://www.olx.in/item/-iid-1650830309',
 'https://www.olx.in/item/good-condition-iid-1650830300',
 'https://www.olx.in/item/bmw-7-series-730ld-sedan-2013-diesel-iid-1650830290',
 'https://www.olx.in/item/honda-city-v-2010-petrol-iid-1650830279',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vxi-2019-petrol-iid-1650830247',
 'https://www.olx.in/item/ford-fiesta-2008-diesel-air-bags-all-clear-iid-1650830240',
 'https://www.olx.in/item/maruti-suzuki-eeco-2014-cng-hybrids-well-maintained-double-clinder-iid-1650830229',
 'https://www.olx.in/item/mahindra-xylo-2013-diesel-well-maintained-iid-1650830218',
 'https://www.olx.in/item/maruthi-suzuki-iid-1650830205',
 'https://www.olx.in/item/two-new-tyres-from-february-iid-1650830194',
 'https://www.olx.in/item/-iid-1650830163',
 'https://www.olx.in/item/mahindra-xuv500-2012-diesel-well-maintained-iid-1650830144',
 'https://www.olx.in/item/maruti-suzuki-ignis-12-delta-2018-petrol-iid-1649788811',
 'https://www.olx.in/item/other-brands-others-2017-petrol-iid-1627246080',
 'https://www.olx.in/item/eicher-1049-sabar-car-bajar-iid-1647618926',
 'https://www.olx.in/item/chevrolet-beat-2015-petrol-iid-1642652561',
 'https://www.olx.in/item/honda-cr-v-2015-petrol-iid-1640425959',
 'https://www.olx.in/item/excellent-condition-xylo-mdi-crde-taxi-plate-iid-1650830142',
 'https://www.olx.in/item/kia-seltos-2020-diesel-well-maintained-iid-1650830136',
 'https://www.olx.in/item/stepny-wagnor-car-iid-1650830125',
 'https://www.olx.in/item/maruti-suzuki-alto-good-condition-iid-1650830096',
 'https://www.olx.in/item/maruti-suzuki-omni-8-seater-bsiv-2017-petrol-iid-1646589836',
 'https://www.olx.in/item/car-for-traveling-for-day1300-iid-1650830064',
 'https://www.olx.in/item/bmw-3-series-gt-2014-diesel-iid-1650830058',
 'https://www.olx.in/item/mahindra-xuv500-w8-2014-diesel-69500-km-driven-iid-1650830054',
 'https://www.olx.in/item/renault-kwid-10-rxt-2018-petrol-iid-1646589972',
 'https://www.olx.in/item/tata-indigo-cs-2009-diesel-120000-km-driven-iid-1650830025',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-vdi-2011-diesel-iid-1650830009',
 'https://www.olx.in/item/hyundai-elite-i20-2016-petrol-15609-km-driven-iid-1650830005',
 'https://www.olx.in/item/hyundai-santro-xing-2004-petrol-good-condition-iid-1650829997',
 'https://www.olx.in/item/hyundai-verna-fluidic-16-vtvt-sx-2013-petrol-iid-1650829987',
 'https://www.olx.in/item/hyundai-verna-fluidic-16-vtvt-sx-2013-petrol-iid-1650829985',
 'https://www.olx.in/item/toyota-innova-25-gx-diesel-7-seater-2010-diesel-iid-1648471744',
 'https://www.olx.in/item/hyundai-creta-16-crdi-at-sx-plus-2016-diesel-iid-1650086704',
 'https://www.olx.in/item/volkswagen-polo-2016-diesel-iid-1648353136',
 'https://www.olx.in/item/maruti-suzuki-ertiga-2018-diesel-iid-1640423345',
 'https://www.olx.in/item/honda-city-2014-2015-i-vtec-vx-option-2014-petrol-iid-1640286804',
 'https://www.olx.in/item/honda-jazz-2012-petrol-iid-1650829983',
 'https://www.olx.in/item/honda-cr-v-24l-4wd-avn-2013-petrol-iid-1650829982',
 'https://www.olx.in/item/honda-jazz-2012-petrol-iid-1650829980',
 'https://www.olx.in/item/honda-cr-v-24l-4wd-avn-2013-petrol-iid-1650829979',
 'https://www.olx.in/item/mahindra-xylo-2017-without-insurance-iid-1650829974',
 'https://www.olx.in/item/mahindra-xuv500-2016-diesel-iid-1650829973',
 'https://www.olx.in/item/maruti-suzuki-alto-800-lxi-2015-petrol-iid-1644589641',
 'https://www.olx.in/item/maruti-suzuki-baleno-13-zeta-2016-diesel-iid-1648536849',
 'https://www.olx.in/item/hyundai-grand-i10-2013-2016-at-asta-2014-petrol-iid-1647691158',
 'https://www.olx.in/item/mahindra-xuv500-w8-2wd-2012-diesel-iid-1647960441',
 'https://www.olx.in/item/maruti-suzuki-swift-ldi-2012-diesel-iid-1647790323',
 'https://www.olx.in/item/maruti-suzuki-ritz-vdi-2013-diesel-iid-1643242264',
 'https://www.olx.in/item/volkswagen-polo-select-12-mpi-highline-2017-petrol-iid-1640285010',
 'https://www.olx.in/item/tata-safari-2010-diesel-iid-1640161605',
 'https://www.olx.in/item/ford-figo-2016-petrol-iid-1650829971',
 'https://www.olx.in/item/honda-amaze-2015-petrol-iid-1650829967',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-o-2016-petrol-iid-1650829966',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zdi-2013-diesel-iid-1650829963',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-2016-petrol-iid-1650829961',
 'https://www.olx.in/item/honda-jazz-2017-petrol-iid-1650829959',
 'https://www.olx.in/item/honda-city-v-2011-petrol-iid-1650829957',
 'https://www.olx.in/item/honda-amaze-2015-petrol-iid-1650829956',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-2016-petrol-iid-1650829954',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zdi-2013-diesel-iid-1650829953',
 'https://www.olx.in/item/honda-amaze-vx-cvt-petrol-2020-petrol-iid-1650829952',
 'https://www.olx.in/item/hyundai-verna-2011-2014-14-crdi-2014-diesel-iid-1648347158',
 'https://www.olx.in/item/hyundai-verna-fluidic-16-crdi-sx-2012-diesel-iid-1646919595',
 'https://www.olx.in/item/maruti-suzuki-grand-vitara-2007-2009-mt-2008-petrol-iid-1647853028',
 'https://www.olx.in/item/honda-brio-2013-2016-s-mt-2013-petrol-iid-1640156279',
 'https://www.olx.in/item/skoda-fabia-2011-petrol-iid-1645697459',
 'https://www.olx.in/item/nissan-terra-2014-petrol-iid-1650829951',
 'https://www.olx.in/item/nissan-sunny-xl-2014-petrol-iid-1650829950',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-2016-petrol-iid-1650829947',
 'https://www.olx.in/item/mahindra-xuv500-2016-diesel-iid-1650829946',
 'https://www.olx.in/item/ford-figo-2016-petrol-iid-1650829944',
 'https://www.olx.in/item/good-condition-iid-1650829943',
 'https://www.olx.in/item/hyundai-grand-i-10-2016-65000-km-driven-iid-1650829942',
 'https://www.olx.in/item/hyundai-i10-2015-petrol-iid-1650829940',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-2016-petrol-iid-1650829939',
 'https://www.olx.in/item/tata-indica-vista-terra-quadrajet-bs-iv-2009-diesel-iid-1650829938',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2015-dec-diesel-well-maintained-new-tyres-iid-1650829937',
 'https://www.olx.in/item/nissan-evalia-iid-1650829933',
 'https://www.olx.in/item/honda-city-v-2011-petrol-iid-1650829914',
 'https://www.olx.in/item/honda-amaze-2015-petrol-iid-1650829911',
 'https://www.olx.in/item/honda-amaze-2015-petrol-iid-1650829907',
 'https://www.olx.in/item/maruti-suzuki-s-cross-zeta-ddis-200-sh-2018-diesel-iid-1645260531',
 'https://www.olx.in/item/maruti-suzuki-ciaz-14-zeta-2017-petrol-iid-1648744754',
 'https://www.olx.in/item/hyundai-creta-14-ex-diesel-2018-diesel-iid-1631859748',
 'https://www.olx.in/item/hyundai-i10-2009-petrol-38000-km-driven-iid-1645297336',
 'https://www.olx.in/item/hyundai-i20-sportz-12-2011-petrol-iid-1538449873',
 'https://www.olx.in/item/hyundai-elite-i20-asta-12-o-2016-petrol-iid-1650829895',
 'https://www.olx.in/item/skoda-superb-2008-2013-28-v6-at-2012-diesel-iid-1650829865',
 'https://www.olx.in/item/renault-duster-2012-2015-85ps-diesel-rxe-2013-diesel-iid-1650829886',
 'https://www.olx.in/item/maruti-suzuki-ertiga-zdi-2013-diesel-iid-1650829884',

In [45]:
brand=[]
model=[]
variant=[]
manufacturingyear=[]
driverkilometers=[]
fuel=[]
owners=[]
location=[]
price=[]



for i in url:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand.append(br.text)
    except NoSuchElementException:
        brand.append('-')

#Model        
    try:
        mo=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model.append(mo.text)
    except NoSuchElementException:
        model.append('-')
        
#Variant
    try:
        var=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant.append(var.text)
    except NoSuchElementException:
        variant.append('-')

#Manufacturingyear
    try:
        yr=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear.append(yr.text)
    except NoSuchElementException:
        manufacturingyear.append('-')

#Kilometers Driven
    try:
        dr=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers.append(dr.text)
    except NoSuchElementException:
        driverkilometers.append('-')
        
#Fuel
    try:
        fl=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel.append(fl.text)
    except NoSuchElementException:
        fuel.append('-')

#no of owners
    try:
        own=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners.append(own.text)
    except NoSuchElementException:
        owners.append('-')
        
#location
    try:
        loc=driver.find_element_by_xpath("(//div[@class='fontweight500 value'])[1]")
        location.append(loc.text)
    except NoSuchElementException:
        location.append('-')
        
#Price
    try:
        pr=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price.append(pr.text)
    except NoSuchElementException:
        price.append('-')




brand = pd.DataFrame(brand)            
brand.columns=['brand']

model = pd.DataFrame(model)            
model.columns=['model']

variant = pd.DataFrame(variant)            
variant.columns=['variant']

manufacturingyear = pd.DataFrame(manufacturingyear)            
manufacturingyear.columns=['manufacturingyear']

driverkilometers = pd.DataFrame(driverkilometers)            
driverkilometers.columns=['driverkilometers']

fuel = pd.DataFrame(fuel)            
fuel.columns=['fuel']

owners = pd.DataFrame(owners)            
owners.columns=['owners']

location = pd.DataFrame(location)            
location.columns=['location']

price = pd.DataFrame(price)            
price.columns=['price']



car=pd.DataFrame({})
car['Brand']=brand['brand']
car['Model']=model['model']
car['Variant']=variant['variant']
car['Manufacturig year']=manufacturingyear['manufacturingyear']
car['Kilometers driven']=driverkilometers['driverkilometers']
car['Fuel']=fuel['fuel']
car['No of Owners']=owners['owners']
car['Location']=location['location']
car['Price']=price['price']
car

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Ford,Figo,2010-2012 Diesel ZXI,2011,"112,844 km",Diesel,1st,"Nerkundram Valavinayear Nagar, Chennai, Tamil Nadu","₹ 2,23,700"
1,Tata,Tiago,-,2016,"93,764 km",Diesel,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,80,000"
2,Ford,Ecosport,1.0 Ecoboost Titanium Plus,2014,"68,000 km",Petrol,2nd,"Dommasandra, Bengaluru, Karnataka","₹ 6,50,000"
3,Tata,Zest,Quadrajet 1.3 XMS,2015,"137,000 km",Diesel,1st,"Undri, Pune, Maharashtra","₹ 4,25,000"
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
437,Ford,Ikon,1.6 ZXI,2006,"89,000 km",Petrol,3rd,"Edayansathu, Vellore, Tamil Nadu","₹ 76,000"
438,Hyundai,EON,Magna,2016,"109,039 km",Petrol,1st,"Ernakulam, Kochi, Kerala","₹ 2,35,000"
439,Volkswagen,Polo,1.2 MPI Comfortline,2012,"72,500 km",Diesel,2nd,"Fulsungi, Rudrapur, Uttaranchal","₹ 3,40,000"
440,Maruti Suzuki,800,Others,2011,"50,000 km",Petrol,3rd,"Sayiwan, Dara Pora, Jammu & Kashmir","₹ 1,40,000"
441,Maruti Suzuki,Zen,Others,2002,"100,000 km",Petrol,2nd,"Sector 56, Chandigarh, Chandigarh","₹ 85,000"

In [70]:
car.isnull().sum()

Brand                0
Model                0
Variant              0
Manufacturig year    0
Kilometers driven    0
Fuel                 0
No of Owners         0
Location             0
Price                0
dtype: int64

In [58]:
print((car['Variant'] == '-').sum())

70

In [71]:
car.replace(0,'-')

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Ford,Figo,2010-2012 Diesel ZXI,2011,"112,844 km",Diesel,1st,"Nerkundram Valavinayear Nagar, Chennai, Tamil Nadu","₹ 2,23,700"
1,Tata,Tiago,-,2016,"93,764 km",Diesel,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,80,000"
2,Ford,Ecosport,1.0 Ecoboost Titanium Plus,2014,"68,000 km",Petrol,2nd,"Dommasandra, Bengaluru, Karnataka","₹ 6,50,000"
3,Tata,Zest,Quadrajet 1.3 XMS,2015,"137,000 km",Diesel,1st,"Undri, Pune, Maharashtra","₹ 4,25,000"
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
437,Ford,Ikon,1.6 ZXI,2006,"89,000 km",Petrol,3rd,"Edayansathu, Vellore, Tamil Nadu","₹ 76,000"
438,Hyundai,EON,Magna,2016,"109,039 km",Petrol,1st,"Ernakulam, Kochi, Kerala","₹ 2,35,000"
439,Volkswagen,Polo,1.2 MPI Comfortline,2012,"72,500 km",Diesel,2nd,"Fulsungi, Rudrapur, Uttaranchal","₹ 3,40,000"
440,Maruti Suzuki,800,Others,2011,"50,000 km",Petrol,3rd,"Sayiwan, Dara Pora, Jammu & Kashmir","₹ 1,40,000"
441,Maruti Suzuki,Zen,Others,2002,"100,000 km",Petrol,2nd,"Sector 56, Chandigarh, Chandigarh","₹ 85,000"

In [72]:
car.tail(20)

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
422,Honda,Amaze,2013-2016 S i-Vtech,2016,"60,000 km",Petrol,1st,"Rohini Sector 10, Delhi, Delhi","₹ 4,20,400"
423,-,-,-,-,-,-,-,-,-
424,Hyundai,Elite i20,1.4 CRDI Asta (O),2015,"65,000 km",Diesel,1st,"Amrapali Society, Raipur, Chhattisgarh","₹ 5,75,000"
425,-,-,-,-,-,-,-,-,-
426,-,-,-,-,-,-,-,-,-
427,Ford,Endeavour,2003-2013 2.5L 4X2 MT,2013,"128,000 km",Diesel,2nd,"Gomti Nagar, Lucknow, Uttar Pradesh","₹ 6,50,000"
428,Hyundai,Santro Xing,Others,2009,"75,000 km",Petrol,1st,"Vasavi Nagar, Nandikotkur Road, Kurnool, Andhra Pradesh","₹ 46,999"
429,Mahindra,Scorpio,2002-2013 VLX 2.2 mHawk BSIII,2007,"260,000 km",Diesel,2nd,"Govindapuram, Aduthurai, Tamil Nadu","₹ 3,00,000"
430,Ford,Ecosport,1.5 Diesel Titanium,2014,"72,300 km",Diesel,2nd,"Gomti Nagar, Lucknow, Uttar Pradesh","₹ 4,75,000"
431,Hyundai,Verna,CRDi 1.6 E,2017,"22,000 km",Diesel,1st,"Thomas Road Area, Ludhiana, Punjab","₹ 8,85,000"
432,Maruti Suzuki,Wagon R,CNG LXI,2009,"70,000 km",CNG & Hybrids,2nd,"Janakpuri, Delhi, Delhi","₹ 1,25,000"
433,Hyundai,Verna,2011-2014 1.6 SX,2012,"182,000 km",Diesel,1st,"Sector 85, Mohali, Punjab","₹ 3,58,000"
434,Maruti Suzuki,Swift,2011-2014 Star VDI,2011,"89,000 km",Diesel,2nd,"New Amritsar Colony, Amritsar, Punjab","₹ 3,50,000"
435,Maruti Suzuki,800,AC,1996,"96,000 km",Petrol,2nd,"Madevpet, Madikeri, Karnataka","₹ 43,000"
436,Honda,City,2008-2011 1.5 V MT,2010,"25,000 km",Petrol,1st,"Sector 1 Block AC, Bidhannagar, West Bengal","₹ 2,85,000"
437,Ford,Ikon,1.6 ZXI,2006,"89,000 km",Petrol,3rd,"Edayansathu, Vellore, Tamil Nadu","₹ 76,000"
438,Hyundai,EON,Magna,2016,"109,039 km",Petrol,1st,"Ernakulam, Kochi, Kerala","₹ 2,35,000"
439,Volkswagen,Polo,1.2 MPI Comfortline,2012,"72,500 km",Diesel,2nd,"Fulsungi, Rudrapur, Uttaranchal","₹ 3,40,000"
440,Maruti Suzuki,800,Others,2011,"50,000 km",Petrol,3rd,"Sayiwan, Dara Pora, Jammu & Kashmir","₹ 1,40,000"
441,Maruti Suzuki,Zen,Others,2002,"100,000 km",Petrol,2nd,"Sector 56, Chandigarh, Chandigarh","₹ 85,000"

In [73]:
car.to_csv (r'C:\Users\allen\car.csv', index = False, header=True)

In [75]:
car.drop(car.loc[car['Brand']=='-'].index, inplace=True)

In [76]:
car

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Ford,Figo,2010-2012 Diesel ZXI,2011,"112,844 km",Diesel,1st,"Nerkundram Valavinayear Nagar, Chennai, Tamil Nadu","₹ 2,23,700"
1,Tata,Tiago,-,2016,"93,764 km",Diesel,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,80,000"
2,Ford,Ecosport,1.0 Ecoboost Titanium Plus,2014,"68,000 km",Petrol,2nd,"Dommasandra, Bengaluru, Karnataka","₹ 6,50,000"
3,Tata,Zest,Quadrajet 1.3 XMS,2015,"137,000 km",Diesel,1st,"Undri, Pune, Maharashtra","₹ 4,25,000"
5,Chevrolet,Spark,1.0 LT,2014,"60,000 km",Petrol,1st,"RV Nagar Narayanasamu Thottam, Chennai, Tamil Nadu","₹ 2,20,000"
...,...,...,...,...,...,...,...,...,...
437,Ford,Ikon,1.6 ZXI,2006,"89,000 km",Petrol,3rd,"Edayansathu, Vellore, Tamil Nadu","₹ 76,000"
438,Hyundai,EON,Magna,2016,"109,039 km",Petrol,1st,"Ernakulam, Kochi, Kerala","₹ 2,35,000"
439,Volkswagen,Polo,1.2 MPI Comfortline,2012,"72,500 km",Diesel,2nd,"Fulsungi, Rudrapur, Uttaranchal","₹ 3,40,000"
440,Maruti Suzuki,800,Others,2011,"50,000 km",Petrol,3rd,"Sayiwan, Dara Pora, Jammu & Kashmir","₹ 1,40,000"
441,Maruti Suzuki,Zen,Others,2002,"100,000 km",Petrol,2nd,"Sector 56, Chandigarh, Chandigarh","₹ 85,000"

In [5]:
driver=webdriver.Chrome("chromedriver.exe")

In [6]:
url='https://www.olx.in/kerala_g2001160/q-cars?isSearchCall=true'
driver.get(url)

In [7]:
for i in range(0,26):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [81]:
producturl1=[] 
for i in driver.find_elements_by_xpath("//div[@class='gsc_col-xs-7 carsName']/a"):
            producturl1.append(i.get_attribute('href'))
producturl1

['https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-Amt-Bsiv-cars-Bangalore_6c4b954c-538a-44be-8dc5-a163612380dd.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Ciaz-Zxi-cars-Bangalore_c290a91b-25d8-4a71-bfb7-45dc0e8371b9.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-Bsiii-cars-Bangalore_c7db0349-ca2d-4bae-91e7-bea7033d42e7.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-cars-Bangalore_ae383c0d-8479-4218-a31c-f3f59fc6ef54.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-K10-Vxi-Amt-cars-Bangalore_31fc6d34-e780-4d86-9f81-cb11cc8f0269.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Eeco-5-Seater-Ac-cars-Bangalore_63da8f69-5ca3-4b22-b238-d85ac36a3ca1.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-cars-Bangalore_af6823e5-cd9c-41cb-82fc-6a97c5ced7f0.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Magna-1.1l-cars-Bangalore_bb11337a-885d-4716-bbb6-ef7583a4b03e.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Brio-1.2-Vx-At-cars-Bangalore_3b7f3e31-06cf-4b9a-b60d-723f18a43f20.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Zdi-cars-Bangalore_2413b0a2-38a3-46e4-9dd9-1b4a1dbcbb41.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Skoda-Rapid-1.6-Tdi-Elegance-cars-Bangalore_856f1642-4ba8-42c6-96e0-47b948a8be85.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_f0b32113-9a41-4319-84ef-0aec0fe6acb0.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-At-cars-Bangalore_50b23132-464a-4d65-976a-b91a44b1db1d.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-1.2-cars-Bangalore_8693a5b7-e0d6-4df0-93a7-866976e67e60.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Sportz-Bsiv-cars-Bangalore_c70e5f82-f67c-455d-a5eb-32a5899063de.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Mahindra-Kuv-100-Mfalcon-G80-K8-cars-Bangalore_7fc2ff07-9faa-4323-a2ea-ca4f48e08425.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Brio-1.2-E-Mt-cars-Bangalore_f74fe7c5-5700-46f7-8b3d-d742ecf00fed.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Ignis-1.2-Delta-Bsiv-cars-Bangalore_d67890f7-e7d2-409d-ac1c-befc2c1f34f8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-Bsiii-cars-Bangalore_676f25d7-eded-4ee1-ad20-bdade37c8341.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-cars-Bangalore_6e9db9a9-9462-48bc-9788-858a3e8b748b.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_97bda148-4985-4428-b4fc-a0a19f5fe387.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-Zeta-cars-Bangalore_f215271c-ce0f-4eb9-8b42-5e5542cfa3d1.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I20-Asta-1.4-Crdi-cars-Bangalore_e652c56d-c345-4890-aed3-121253530281.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-K10-2010-2014-Vxi-cars-Bangalore_7eb73605-89c5-402e-8ee3-9c2aef07eed5.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-Amt-cars-Bangalore_a27a5f63-24d5-400a-8587-e7ee72eb027e.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-At-cars-Bangalore_9fc32a70-64be-4e66-9f84-93b87887b6ee.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Volkswagen-Polo-1.2-Mpi-Comfortline-cars-Bangalore_8f688e49-00bc-46fa-9d03-820b3c734166.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-02-Anniversary-Edition-cars-Bangalore_9a27b55f-38f2-43c8-92a8-e969cecc6d33.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Amt-cars-Bangalore_b33876da-9c2c-40ac-bc56-cd0a1749d36f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Zeta-cars-Bangalore_715b92c7-641f-4bba-b09c-a9a53f69161a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Mahindra-Tuv-300-T8-cars-Bangalore_da983f56-347f-4679-98eb-dc1d8ec2a3d8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-Vx-Cvt-cars-Bangalore_ead5712a-eeca-4f31-b68d-4da466454753.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Amt-cars-Bangalore_f7d2d5f4-0ba6-4adc-a093-1536a3e117e6.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-Amt-cars-Bangalore_eeb8b452-aeb8-4248-9758-56d4e4945497.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-At-cars-Bangalore_d59a9fca-0334-4b30-acb9-102bbf9bf4d6.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-Amt-cars-Bangalore_aefc8504-db48-46e5-beab-4c70f8171187.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Delta-cars-Bangalore_327df5d1-9ec3-49a4-9ef5-5fe9cbece92a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Tata-Tigor-1.2-Revotron-Xt-cars-Bangalore_7ad7ca79-ec1e-4ea7-b448-32dfdff9c289.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Cvt-Zeta-cars-Bangalore_72d70117-4d21-48ff-8c4f-7b8e4cd1e4ac.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.3-Delta-cars-Bangalore_164dbdff-99cb-4c6d-88dd-273b425592d8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-Amt-Bsiv-cars-Bangalore_c156f162-0d94-44ab-b9a1-62b99c61e245.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-cars-Bangalore_90262e62-6aa1-4913-854b-62f78ddea71f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-cars-Bangalore_5868c205-225a-453d-be16-337259e6b595.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Bsiv-cars-Bangalore_e969dbf3-8424-4d83-b578-ecbe3cd08775.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-cars-Bangalore_591ed9dc-a659-419b-92ab-8914c3ca5a04.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_851611aa-3f79-47b2-8f78-b92278409526.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I20-Active-1.2-Sx-cars-Bangalore_c448b430-23e0-406e-a042-92f5397df6bf.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Vxi-cars-Bangalore_2d990ce6-8c5e-4e25-9fc3-e12ce780b725.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-V-cars-Bangalore_ad8b6a87-c38c-4985-8210-f0262a6597f8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Alpha-cars-Bangalore_bec9561f-4a4e-4097-9cba-e29fe5b1808e.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.3-Alpha-cars-Bangalore_5fc2d248-79bd-4a00-9d01-259e1c728bc2.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-1.2-S-I-Vtec-cars-Bangalore_6a3f201a-271b-45fc-928a-f8abd80ef815.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-cars-Bangalore_f862cc15-1aae-43ca-85d1-b227d00be46c.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_6b215681-8bd5-4bf5-a0d4-86da382e8471.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-cars-Bangalore_b3c2952d-faad-4712-9453-65d2820b4a10.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Zeta-cars-Bangalore_0bce9de6-8872-4770-a64f-383cd7574a73.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Tata-Tiago-1.2-Revotron-Xza-cars-Bangalore_d6f91db6-942f-462a-9cae-9441056cf710.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Magna-At-cars-Bangalore_fbcf33bf-8503-4825-8fac-574cd7f46462.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-Delta-cars-Bangalore_851fcc57-a979-469b-802c-fb5ebcd8b30b.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_af4a2f23-b730-4e0c-a01b-054e39857159.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-Amt-Bsiv-cars-Bangalore_c156f162-0d94-44ab-b9a1-62b99c61e245.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-cars-Bangalore_90262e62-6aa1-4913-854b-62f78ddea71f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-cars-Bangalore_5868c205-225a-453d-be16-337259e6b595.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Bsiv-cars-Bangalore_e969dbf3-8424-4d83-b578-ecbe3cd08775.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-cars-Bangalore_591ed9dc-a659-419b-92ab-8914c3ca5a04.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_851611aa-3f79-47b2-8f78-b92278409526.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I20-Active-1.2-Sx-cars-Bangalore_c448b430-23e0-406e-a042-92f5397df6bf.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Vxi-cars-Bangalore_2d990ce6-8c5e-4e25-9fc3-e12ce780b725.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-V-cars-Bangalore_ad8b6a87-c38c-4985-8210-f0262a6597f8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Alpha-cars-Bangalore_bec9561f-4a4e-4097-9cba-e29fe5b1808e.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.3-Alpha-cars-Bangalore_5fc2d248-79bd-4a00-9d01-259e1c728bc2.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-1.2-S-I-Vtec-cars-Bangalore_6a3f201a-271b-45fc-928a-f8abd80ef815.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-Lxi-cars-Bangalore_f862cc15-1aae-43ca-85d1-b227d00be46c.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_6b215681-8bd5-4bf5-a0d4-86da382e8471.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-cars-Bangalore_b3c2952d-faad-4712-9453-65d2820b4a10.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Zeta-cars-Bangalore_0bce9de6-8872-4770-a64f-383cd7574a73.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Tata-Tiago-1.2-Revotron-Xza-cars-Bangalore_d6f91db6-942f-462a-9cae-9441056cf710.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Magna-At-cars-Bangalore_fbcf33bf-8503-4825-8fac-574cd7f46462.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-Delta-cars-Bangalore_851fcc57-a979-469b-802c-fb5ebcd8b30b.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_af4a2f23-b730-4e0c-a01b-054e39857159.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-cars-Bangalore_6e44d60b-74fd-43f5-9a8e-3d5837a0d9b5.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Ignis-Zeta-cars-Bangalore_9e896d8b-dd68-48f0-83d7-ea865a7dbb51.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-At-Asta-cars-Bangalore_6f1a6a36-c89d-4c96-bfe5-3dbe146ef307.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Eeco-5-Seater-Ac-Bsiv-cars-Bangalore_d20f9f5e-6355-4510-abfb-b304daf7b425.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Asta-cars-Bangalore_6f8d51b5-bc08-4c5e-a46b-f79fcec7cdd8.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Sportz-cars-Bangalore_7429e165-6b8b-4ae1-8631-04b9496bd84d.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Baleno-1.2-Cvt-Zeta-cars-Bangalore_fdbfa29e-f307-46e8-b720-1beb7abd27fe.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-Plus-Optional-cars-Bangalore_329146f6-0c3d-46a9-a668-f7302037b938.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-Bs-Iv-cars-Bangalore_27981604-848b-4318-b505-5854e3705051.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Sportz-Bsiv-cars-Bangalore_e2642805-8c4a-477f-a277-cf91109e4a99.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Wagon-R-Vxi-cars-Bangalore_7a506f22-3aba-4ab3-88c8-5084b95f5be4.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-1.2-Vx-I-Vtec-cars-Bangalore_73121336-83f2-452d-845b-94105225b1ec.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Santro-Asta-Bsiv-cars-Bangalore_73ebc36c-c487-4a45-ac5f-99f6528b01a0.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-1.2-Kappa-Asta-cars-Bangalore_bdd25b83-83ee-423d-a9bd-b2b27330d8a3.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Sportz-cars-Bangalore_42635d4c-4153-48f1-801d-82074de86197.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-cars-Bangalore_4431c24f-4165-4366-a461-e4002f3ef4e2.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-Rxt-cars-Bangalore_af69d5e6-71a0-4ff6-b55a-d038b28b5022.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Jazz-V-Cvt-cars-Bangalore_9d160fe9-4672-4156-8b83-87b33c058329.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-At-Asta-cars-Bangalore_7c250dbf-6554-4542-a489-436813b3a64f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I20-Active-1.2-Sx-cars-Bangalore_c26bf577-cef0-4f5d-a104-0b21ad7cc414.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vdi-cars-Bangalore_5e64b529-a14e-4681-b1ac-32908fe1f036.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_249737c7-189b-4fc9-84a1-7a672580dbe1.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-Option-cars-Bangalore_9be04346-5e58-4eec-bf37-6ee6130268fe.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_c722c128-b08f-4173-a230-ed0d1362a985.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Amt-cars-Bangalore_cb0c4cb9-de06-4b8e-b586-fcceaffb4832.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Opt-cars-Bangalore_371bc3ae-0cc1-40bf-9e4f-1dd039b031a9.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Ignis-1.2-Zeta-Bsiv-cars-Bangalore_2704dafb-04dc-41ad-b97d-1095fe5468f3.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Eeco-5-Seater-Ac-cars-Bangalore_b6aa3d08-0a1a-471d-a300-ce722119540a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-cars-Bangalore_3badd221-e4c8-490f-a6fd-10a030a4e56b.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-At-cars-Bangalore_3321e695-00a1-4e85-bb71-dafdb6d46ace.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-At-cars-Bangalore_4ac8f1b5-3bb6-4fef-a43f-a24dd25efc8f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_136d77d5-5a65-4d49-be7d-943deb3f9c56.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vdi-cars-Bangalore_d643a33f-5544-4e5d-9fb4-1b382a77ba4a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Tata-Tiago-1.2-Revotron-Xza-cars-Bangalore_cb5a7784-48e3-4c80-b7aa-011b30e51f37.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Era-cars-Bangalore_8366d352-a8b1-4259-a1f1-c9a0717ff7bb.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Magna-cars-Bangalore_2270d4e5-a6f8-4174-accf-efb71002d6ef.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Magna-1.1l-cars-Bangalore_302a2e01-c1e5-4e51-846a-4ac9b81bed17.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Sportz-cars-Bangalore_330cd39f-7ca1-4c06-ba1b-6a16c8670a35.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_fc33ab76-64fa-404a-a0bd-e96a9412bc50.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-Option-cars-Bangalore_a280b678-0b75-4a06-a16c-8befee19f433.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vdi-cars-Bangalore_5e64b529-a14e-4681-b1ac-32908fe1f036.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_249737c7-189b-4fc9-84a1-7a672580dbe1.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-Option-cars-Bangalore_9be04346-5e58-4eec-bf37-6ee6130268fe.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_c722c128-b08f-4173-a230-ed0d1362a985.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Amt-cars-Bangalore_cb0c4cb9-de06-4b8e-b586-fcceaffb4832.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-1.0-Rxt-Opt-cars-Bangalore_371bc3ae-0cc1-40bf-9e4f-1dd039b031a9.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Ignis-1.2-Zeta-Bsiv-cars-Bangalore_2704dafb-04dc-41ad-b97d-1095fe5468f3.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Eeco-5-Seater-Ac-cars-Bangalore_b6aa3d08-0a1a-471d-a300-ce722119540a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-cars-Bangalore_3badd221-e4c8-490f-a6fd-10a030a4e56b.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-At-cars-Bangalore_3321e695-00a1-4e85-bb71-dafdb6d46ace.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Zxi-At-cars-Bangalore_4ac8f1b5-3bb6-4fef-a43f-a24dd25efc8f.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-800-Lxi-cars-Bangalore_136d77d5-5a65-4d49-be7d-943deb3f9c56.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vdi-cars-Bangalore_d643a33f-5544-4e5d-9fb4-1b382a77ba4a.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Tata-Tiago-1.2-Revotron-Xza-cars-Bangalore_cb5a7784-48e3-4c80-b7aa-011b30e51f37.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Era-cars-Bangalore_8366d352-a8b1-4259-a1f1-c9a0717ff7bb.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Magna-cars-Bangalore_2270d4e5-a6f8-4174-accf-efb71002d6ef.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Magna-1.1l-cars-Bangalore_302a2e01-c1e5-4e51-846a-4ac9b81bed17.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Sportz-cars-Bangalore_330cd39f-7ca1-4c06-ba1b-6a16c8670a35.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_fc33ab76-64fa-404a-a0bd-e96a9412bc50.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Grand-I10-Asta-Option-cars-Bangalore_a280b678-0b75-4a06-a16c-8befee19f433.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-I10-Sportz-cars-Bangalore_734826a8-8e1d-4ec7-af19-e97d322eb9b0.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Hyundai-Eon-Era-Plus-cars-Bangalore_45bbb85b-052a-46eb-8286-f2e1aa181b11.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Honda-Brio-V-Mt-cars-Bangalore_0f07048d-f25a-4175-ae5e-530bd801a964.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Celerio-Vxi-Amt-Bsiv-cars-Bangalore_63728e99-40e3-451a-9a5d-9e810e2189db.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Volkswagen-Vento-Diesel-Highline-cars-Bangalore_f0e04d59-71af-4889-91ef-1ab7d95b30a1.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Alto-K10-2010-2014-Vxi-cars-Bangalore_4419091a-f466-4aea-959d-1f1190fdf5da.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Renault-Kwid-Amt-cars-Bangalore_4d405d4a-25bc-401b-93d2-f450b46b5ca9.htm',
 'https://www.cardekho.com/buy-used-car-details/used-Maruti-Swift-Dzire-Vxi-cars-Bangalore_cc7d96b2-4613-4958-9d81-289c505f68ca.htm',

In [20]:
producturl2

['https://www.olx.in/item/toyota-innova-crysta-24-v-2017-diesel-iid-1633534874',
 'https://www.olx.in/item/tata-zest-2016-diesel-iid-1649277891',
 'https://www.olx.in/item/honda-city-1998-petrol-iid-1646994630',
 'https://www.olx.in/item/honda-city-2006-petrol-iid-1650467418',
 'https://www.olx.in/item/bmw-5-series-2011-diesel-luxury-line-hr-registration-single-owner-iid-1649440139',
 'https://www.olx.in/item/renault-kwid-climber-10-mt-opt-2018-petrol-iid-1650844324',
 'https://www.olx.in/item/renault-kwid-10-rxt-amt-opt-2017-petrol-iid-1650844290',
 'https://www.olx.in/item/ford-ikon-14-tdci-duratorq-2010-diesel-iid-1650844265',
 'https://www.olx.in/item/hyundai-i10-12-kappa-magna-2013-petrol-iid-1650844246',
 'https://www.olx.in/item/maruti-suzuki-celerio-vxi-amt-2014-petrol-iid-1650844217',
 'https://www.olx.in/item/hyundai-grand-i10-12-crdi-sportz-option-2013-diesel-iid-1650844190',
 'https://www.olx.in/item/hyundai-i20-2009-2011-magna-2011-petrol-iid-1650844169',
 'https://www.olx.in/item/hyundai-santro-xing-2008-petrol-72000-km-driven-iid-1646261971',
 'https://www.olx.in/item/chevrolet-sail-u-va-12-lt-abs-2013-petrol-iid-1650844153',
 'https://www.olx.in/item/toyota-etios-liva-2013-diesel-well-maintained-iid-1650844040',
 'https://www.olx.in/item/mahindra-jeep-1995-diesel-well-maintained-iid-1650843915',
 'https://www.olx.in/item/toyota-commuter-diesel-2014-diesel-iid-1650843645',
 'https://www.olx.in/item/mitsubishi-pajero-select-plus-4x4-mt-2011-diesel-iid-1650843591',
 'https://www.olx.in/item/skoda-rapid-2011-2013-16-tdi-active-2014-diesel-iid-1634135454',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2015-petrol-well-maintained-iid-1650843065',
 'https://www.olx.in/item/toyota-land-cruiser-v8-petrol-2007-petrol-iid-1647088073',
 'https://www.olx.in/item/jeep-compass-14-limited-option-2018-petrol-iid-1649996009',
 'https://www.olx.in/item/hyundai-verna-anniversary-edition-2018-iid-1649927466',
 'https://www.olx.in/item/hyundai-santro-xing-2008-petrol-iid-1642339922',
 'https://www.olx.in/item/toyota-innova-2007-diesel-well-maintained-iid-1645741242',
 'https://www.olx.in/item/ford-ikon-2003-iid-1645635738',
 'https://www.olx.in/item/honda-city-i-vtec-v-2018-petrol-iid-1650045255',
 'https://www.olx.in/item/audi-a4-20-tdi-177bhp-premium-2010-diesel-iid-1650045077',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-13-lxi-2006-petrol-iid-1625533434',
 'https://www.olx.in/item/toyota-innova-crysta-28-zx-at-2019-diesel-iid-1649237333',
 'https://www.olx.in/item/ford-ikon-2010-diesel-well-maintained-iid-1650842016',
 'https://www.olx.in/item/second-hand-omni-venam-iid-1650842008',
 'https://www.olx.in/item/toyota-innova-2012-diesel-235000-km-driven-iid-1650841825',
 'https://www.olx.in/item/maruti-suzuki-800-2010-petrol-good-condition-iid-1650841788',
 'https://www.olx.in/item/honda-amaze-2018-diesel-35500-km-driven-iid-1650841607',
 'https://www.olx.in/item/tata-nano-2010-petrol-good-condition-iid-1650841342',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-2010-petrol-82000-km-driven-iid-1650841217',
 'https://www.olx.in/item/used-car-loan-kuwy-iid-1566588557',
 'https://www.olx.in/item/mahindra-thar-crde-4x4-bs-iv-2021-diesel-iid-1649236350',
 'https://www.olx.in/item/mercedes-benz-s-class-s-500-l-2011-petrol-iid-1650003289',
 'https://www.olx.in/item/used-car-loan-service-iid-1649735883',
 'https://www.olx.in/item/mercedes-benz-new-c-class-c-250-cdi-avantgarde-2012-diesel-iid-1646388547',
 'https://www.olx.in/item/audi-a6-20-tdi-premium-plus-2012-diesel-iid-1632551691',
 'https://www.olx.in/item/tata-xenon-xt-2014-diesel-well-maintained-iid-1650840998',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2016-petrol-33000-km-driven-no-accident-history-iid-1650840445',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-10-2004-petrol-980000-km-driven-iid-1650840427',
 'https://www.olx.in/item/maruti-suzuki-swift-2018-vdi-2018-diesel-iid-1644356961',
 'https://www.olx.in/item/hyundai-eon-era-2012-petrol-iid-1643529316',
 'https://www.olx.in/item/maruti-suzuki-alto-2010-petrol-good-condition-iid-1650840118',
 'https://www.olx.in/item/ford-fiesta-2008-2011-16-duratec-exi-2011-petrol-iid-1650840092',
 'https://www.olx.in/item/mitsubishi-lancer-20-exel-2005-diesel-iid-1650839832',
 'https://www.olx.in/item/toyota-etios-15-g-2014-petrol-iid-1650042505',
 'https://www.olx.in/item/wide-range-of-premium-quality-head-lamp-for-cars-iid-1610833492',
 'https://www.olx.in/item/tata-nexon-2021-petrol-good-condition-iid-1650839553',
 'https://www.olx.in/item/mahindra-jeep-1992-diesel-98000-km-driven-iid-1650839528',
 'https://www.olx.in/item/audi-q7-2013-diesel-92000-km-driven-iid-1650839519',
 'https://www.olx.in/item/ritz-vxi-2015-iid-1650839474',
 'https://www.olx.in/item/honda-brio-12-s-mt-2012-petrol-iid-1646027279',
 'https://www.olx.in/item/eon-era-plus-2017-iid-1649713281',
 'https://www.olx.in/item/volkswagen-jetta-19-highline-tdi-2010-diesel-iid-1627026993',
 'https://www.olx.in/item/toyota-etios-liva-2019-petrol-good-condition-iid-1650837815',
 'https://www.olx.in/item/toyota-innova-2016-iid-1650839131',
 'https://www.olx.in/item/nissan-sunny-2012-diesel-good-condition-iid-1650839072',
 'https://www.olx.in/item/maruti-suzuki-alto-2019-petrol-13000-km-driven-iid-1650839062',
 'https://www.olx.in/item/maruti-suzuki-800-2004-petrol-100800-km-driven-iid-1644874652',
 'https://www.olx.in/item/hyundai-i10-12-kappa-magna-2011-petrol-iid-1614584935',
 'https://www.olx.in/item/volkswagen-ameo-15-tdi-trendline-2017-diesel-iid-1644355204',
 'https://www.olx.in/item/skoda-rapid-15-tdi-active-2012-diesel-iid-1634131861',
 'https://www.olx.in/item/corolla-altis-2011-model-single-owner-iid-1650838674',
 'https://www.olx.in/item/mahindra-bolero-2012-diesel-well-maintaine-iid-1650838645',
 'https://www.olx.in/item/hindustan-motors-ambassador-2006-diesel-stride-engine-iid-1650838232',
 'https://www.olx.in/item/maruti-suzuki-alto-800-lxi-2018-petrol-iid-1645174783',
 'https://www.olx.in/item/maruti-suzuki-ertiga-shvs-vdi-2017-diesel-iid-1645174528',
 'https://www.olx.in/item/mahindra-others-1986-diesel-iid-1614583807',
 'https://www.olx.in/item/honda-city-2011-2013-s-2013-petrol-iid-1650041012',
 'https://www.olx.in/item/maruti-suzuki-baleno-zeta-2018-diesel-iid-1643239711',
 'https://www.olx.in/item/maruti-suzuki-swift-vdi-bs-iv-2008-diesel-iid-1648196195',
 'https://www.olx.in/item/201918-tata-nexon-xza-plus-dual-tone-automatic-18000-km-single-owner-iid-1647320973',
 'https://www.olx.in/item/maruti-suzuki-swift-2018-petrol-well-maintained-iid-1650837809',
 'https://www.olx.in/item/maruti-suzuki-celerio-vxi-amt-2016-petrol-iid-1646753155',
 'https://www.olx.in/item/maruti-suzuki-zen-1999-ac-iid-1612290578',
 'https://www.olx.in/item/honda-jazz-12-s-i-vtec-2016-petrol-iid-1650837572',
 'https://www.olx.in/item/ford-fiesta-2008-diesel-well-maintained-iid-1650837408',
 'https://www.olx.in/item/powerstairing-ac-sentral-ac-new-tair-sentral-lok-new-ensur-new-pepar-iid-1650837370',
 'https://www.olx.in/item/very-good-condition-car-iid-1650837270',
 'https://www.olx.in/item/neat-and-clean-maruti-800-mpfi-5-speed-iid-1650837219',
 'https://www.olx.in/item/maruti-suzuki-baleno-diesel-alpha-2016-iid-1650836942',
 'https://www.olx.in/item/volkswagen-vento-2012-diesel-49000-km-driven-iid-1650836770',
 'https://www.olx.in/item/ford-fiesta-zxi-16-2009-diesel-iid-1635320233',
 'https://www.olx.in/item/audi-q3-2015-diesel-iid-1592630591',
 'https://www.olx.in/item/hyundai-grand-i10-asta-automatic-12-kappa-vtvt-2015-petrol-iid-1647581391',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-vxi-amt-2018-petrol-iid-1647581127',
 'https://www.olx.in/item/hyundai-verna-crdi-16-sx-2011-diesel-iid-1634130457',
 'https://www.olx.in/item/volkswagen-crosspolo-2013-2015-15-tdi-2015-diesel-iid-1648171063',
 'https://www.olx.in/item/renault-pulse-rxl-abs-diesel-2014-diesel-iid-1632186365',
 'https://www.olx.in/item/volkswagen-polo-15-tdi-highline-2017-diesel-iid-1628324033',
 'https://www.olx.in/item/nissan-micra-xv-cvt-2016-petrol-iid-1650836666',
 'https://www.olx.in/item/kenwood-car-amp-500w-iid-1650836599',
 'https://www.olx.in/item/alto-k10-vxi-iid-1650836376',
 'https://www.olx.in/item/toyota-innova-2005-diesel-good-condition-family-used-car-al-paper-new-iid-1650836129',
 'https://www.olx.in/item/maruti-suzuki-800-1999-petrol-well-maintained-iid-1650836118',
 'https://www.olx.in/item/hyundai-creta-2018-petrol-well-maintained-iid-1650835841',
 'https://www.olx.in/item/car-for-rent-iid-1650835777',
 'https://www.olx.in/item/hyundai-eon-2013-petrol-65000-km-driven-iid-1650835688',
 'https://www.olx.in/item/maruti-suzuki-alto-2011-petrol-67000-km-driven-iid-1650835656',
 'https://www.olx.in/item/datsun-go-t-2016-petrol-iid-1649722630',
 'https://www.olx.in/item/hyundai-creta-16-s-automatic-diesel-2016-diesel-iid-1648409905',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-2011-petrol-iid-1643523601',
 'https://www.olx.in/item/toyota-innova-25-g-diesel-8-seater-2009-diesel-iid-1643523258',
 'https://www.olx.in/item/tata-nexon-12-revotron-xm-2019-petrol-iid-1647580879',
 'https://www.olx.in/item/honda-jazz-2016-petrol-well-maintained-iid-1650835375',
 'https://www.olx.in/item/hyundai-i20-2012-diesel-80000-km-driven-iid-1644854843',
 'https://www.olx.in/item/chevrolet-beat-2010-2013-diesel-ps-2011-diesel-iid-1625729137',
 'https://www.olx.in/item/maruti-suzuki-sx4-2007-2012-zxi-bsiii-2007-petrol-iid-1650321428',
 'https://www.olx.in/item/maruti-suzuki-ritz-2010-diesel-well-maintained-iid-1650835024',
 'https://www.olx.in/item/maruti-suzuki-a-star-2012-iid-1650834693',
 'https://www.olx.in/item/maruti-suzuki-800-2006-petrol-82000-km-driven-iid-1643885341',
 'https://www.olx.in/item/toyota-others-2021-petrol-iid-1650615198',
 'https://www.olx.in/item/tata-indica-vista-2008-2013-aqua-tdi-bsiii-2009-diesel-iid-1605460218',
 'https://www.olx.in/item/hyundai-i10-era-2010-petrol-iid-1610408248',
 'https://www.olx.in/item/volkswagen-jetta-20l-tdi-highline-at-2015-diesel-iid-1650834350',
 'https://www.olx.in/item/30000-car--iid-1650834346',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2010-diesel-iid-1613574851',
 'https://www.olx.in/item/toyota-innova-25-gx-diesel-8-seater-bs-iv-2016-diesel-iid-1650589963',
 'https://www.olx.in/item/honda-br-v-2016-petrol-51669-km-driven-iid-1650834318',
 'https://www.olx.in/item/maruti-suzuki-zen-d-ps-2002-diesel-iid-1618546813',
 'https://www.olx.in/item/wagon-r-2011-excellent-condition-iid-1650834306',
 'https://www.olx.in/item/mahindra-scorpio-2006-2009-slx-26-turbo-7-str-2006-diesel-iid-1626275503',
 'https://www.olx.in/item/tata-nano-2012-2015-twist-xe-2015-petrol-iid-1633950033',
 'https://www.olx.in/item/maruti-suzuki-eeco-5-str-with-achtr-2020-petrol-iid-1648251267',
 'https://www.olx.in/item/hyundai-i10-magna-2009-petrol-iid-1644887985',
 'https://www.olx.in/item/toyota-innova-25-v-7-str-2013-diesel-iid-1648173267',
 'https://www.olx.in/item/hyundai-grand-i10-2013-2016-at-asta-2014-petrol-iid-1634917000',
 'https://www.olx.in/item/toyota-fortuner-30-4x4-manual-2010-diesel-iid-1649689145',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-2011-petrol-iid-1649229003',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-lxi-2015-petrol-iid-1649228403',
 'https://www.olx.in/item/hyundai-eon-era-2016-petrol-iid-1649228317',
 'https://www.olx.in/item/mahindra-thar-crde-4x4-bs-iv-2016-diesel-iid-1643521424',
 'https://www.olx.in/item/ashok-leyland-others-2018-diesel-iid-1643522124',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-tour-ldi-2016-diesel-iid-1638903882',
 'https://www.olx.in/item/honda-amaze-2013-diesel-well-maintained-iid-1650833902',
 'https://www.olx.in/item/hyundai-santro-2008-petrol-well-maintained-iid-1650833776',
 'https://www.olx.in/item/renult-duster-automatic-iid-1644122344',
 'https://www.olx.in/item/ibell-car-stereo-iid-1650833408',
 'https://www.olx.in/item/toyota-fortuner-28-4wd-mt-2017-diesel-iid-1650833163',
 'https://www.olx.in/item/jaguar-xf-22-diesel-2019-diesel-iid-1650832840',
 'https://www.olx.in/item/maruti-suzuki-a-star-zxi-2009-petrol-iid-1649227141',
 'https://www.olx.in/item/mercedes-benz-e-class-exclusive-e-220-d-2019-diesel-iid-1650181679',
 'https://www.olx.in/item/porsche-cayenne-s-diesel-2014-diesel-iid-1643592230',
 'https://www.olx.in/item/maruti-suzuki-zen-estilo-lxi-bsiii-2007-petrol-iid-1635063706',
 'https://www.olx.in/item/toyota-etios-liva-14-gd-2015-diesel-iid-1649226580',
 'https://www.olx.in/item/maruti-suzuki-baleno-12-delta-2017-petrol-iid-1649226902',
 'https://www.olx.in/item/8000-sqft-car-work-shop--iid-1641610787',
 'https://www.olx.in/item/premier-rio-2009-2011-dx-2010-diesel-iid-1649226878',
 'https://www.olx.in/item/toyota-corolla-altis-18-j-2009-petrol-iid-1649226399',
 'https://www.olx.in/item/chevrolet-spark-2007-2012-10-lt-2012-petrol-iid-1642716188',
 'https://www.olx.in/item/chevrolet-cruze-2010-2011-ltz-2010-diesel-iid-1641927553',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-vxi-minor-2009-petrol-iid-1638902569',
 'https://www.olx.in/item/showroom-condition-iid-1650832393',
 'https://www.olx.in/item/hyundai-creta-16-sx-automatic-diesel-2016-diesel-iid-1650832327',
 'https://www.olx.in/item/tata-harrier-xza-camo-automatic-iid-1650832155',
 'https://www.olx.in/item/tata-tiago-diesel-single-owner-2017-registered-iid-1650832099',
 'https://www.olx.in/item/new--iid-1650831992',
 'https://www.olx.in/item/toyota-qualis-2004-diesel-good-condition-iid-1650831947',
 'https://www.olx.in/item/datsun-go-plus-2015-petrol-well-maintained-iid-1650831799',
 'https://www.olx.in/item/renault-kwid-10-rxt-amt-opt-2017-petrol-iid-1649909026',
 'https://www.olx.in/item/toyota-yaris-g-optional-2020-petrol-iid-1646406138',
 'https://www.olx.in/item/other-brands-others-2017-iid-1629835489',
 'https://www.olx.in/item/renault-kwid-2019-rxt-1000cc-iid-1650831736',
 'https://www.olx.in/item/maruthi-suzuki-ertiga-zdi-2015-well-maintained-iid-1650831737',
 'https://www.olx.in/item/mahindra-bolero-2011-diesel-good-condition-no-accident-fulloption-iid-1650831696',
 'https://www.olx.in/item/toyota-innova-2006-diesel-198000-km-driven-iid-1650831627',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2012-petrol-69872-km-driven-iid-1650831563',
 'https://www.olx.in/item/clean-body-crd-type-extra-fitting-worth-1-lakh-4-cross-4-iid-1650831391',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-comfortline-2017-petrol-iid-1650831187',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',
 'https://www.olx.in/item/toyota-fortuner-trd-sportivo-28-2wd-at-2014-diesel-iid-1650033695',
 'https://www.olx.in/item/maruti-suzuki-omni-iid-1650830870',
 'https://www.olx.in/item/hyundai-xcent-2014-petrol-38000km-iid-1650830799',
 'https://www.olx.in/item/audi-q7-45-tdi-quattro-premium-plus-2016-diesel-iid-1650294898',
 'https://www.olx.in/item/renault-fluence-15-e4-2011-diesel-iid-1630514373',
 'https://www.olx.in/item/hyundai-i20-14-asta-2012-diesel-iid-1647211469',
 'https://www.olx.in/item/other-brands-others-2018-diesel-iid-1650830758',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2018-petrol-iid-1650830638',
 'https://www.olx.in/item/mahindra-jeep-1986-diesel-well-maintained-iid-1650830516',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2014-petrol-iid-1650830485',
 'https://www.olx.in/item/2015-renault-lodgy-full-option-iid-1650830439',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2010-diesel-130000-km-driven-family-use-iid-1650829863',
 'https://www.olx.in/item/renault-duster-2016-diesel-well-maintained-iid-1650829458',
 'https://www.olx.in/item/mahindra-thar-2011-diesel-well-maintained-iid-1649715787',
 'https://www.olx.in/item/ford-ecosport-15-petrol-titanium-plus-2018-diesel-iid-1649222906',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-comfortline-2016-petrol-iid-1648402213',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-vxi-minor-2009-petrol-iid-1647573571',
 'https://www.olx.in/item/nissan-terrano-xl-d-option-2015-diesel-iid-1638222855',
 'https://www.olx.in/item/hyundai-i10-2011-petrol-well-maintained-iid-1650829241',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2017-petrol-59000-km-driven-iid-1650829092',
 'https://www.olx.in/item/hyundai-eonuber-ola-attached-single-ownerall-paper-clear-iid-1650828996',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-amt-vxi-2016-petrol-iid-1641013444',
 'https://www.olx.in/item/maruti-suzuki-swift-2014-diesel-well-maintained-iid-1645499268',
 'https://www.olx.in/item/hyundai-venue-s-2019-petrol-iid-1650704906',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2005-petrol-iid-1650828913',
 'https://www.olx.in/item/maruti-suzuki-swift-2014-iid-1573259783',
 'https://www.olx.in/item/renault-triber-iid-1650828316',
 'https://www.olx.in/item/hyundai-eon-2015-petrol-well-maintained-iid-1650828180',
 'https://www.olx.in/item/volkswagen-vento-15-tdi-highline-2011-diesel-iid-1650828141',
 'https://www.olx.in/item/mg-hector-sharp-at-2019-petrol-iid-1650828064',
 'https://www.olx.in/item/battery-for-carnano800-iid-1650827922',
 'https://www.olx.in/item/value-for-money-iid-1650827798',
 'https://www.olx.in/item/jeep-compass-14-limited-2018-diesel-iid-1650827739',
 'https://www.olx.in/item/mahindra-xuv500-2011-2015-w8-2wd-2012-diesel-iid-1649220043',
 'https://www.olx.in/item/toyota-qualis-fs-b2-2001-diesel-iid-1647571946',
 'https://www.olx.in/item/honda-city-2015-2017-i-vtec-vx-2017-petrol-iid-1647571082',
 'https://www.olx.in/item/maruti-suzuki-ciaz-2014-2017-vxi-plus-2015-petrol-iid-1646741597',
 'https://www.olx.in/item/maruti-suzuki-800-1997-petrol-iid-1650827485',
 'https://www.olx.in/item/toyota-innova-25-gx-8-str-bs-iii-2015-diesel-iid-1650827224',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2006-petrol-iid-1647093451',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-lxi-minor-2007-petrol-iid-1643796270',
 'https://www.olx.in/item/toyota-innova-75000-km-driven-iid-1650678147',
 'https://www.olx.in/item/hyundai-santro-xing-2010-petrol-97500-km-driven-iid-1650827168',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2013-petrol-74000-km-driven-iid-1650827044',
 'https://www.olx.in/item/kwid-automatic-for-sale-iid-1650827009',
 'https://www.olx.in/item/maruti-suzuki-a-star-2009-petrol-well-maintained-iid-1650826979',
 'https://www.olx.in/item/venta-16-tdi-highline-maintained-well-iid-1650826896',
 'https://www.olx.in/item/kia-others-2021-petrol-iid-1650826789',
 'https://www.olx.in/item/toyota-innova-2018-diesel-good-condition-iid-1650826573',
 'https://www.olx.in/item/maruti-suzuki-alto-2007-petrol-1-km-driven-iid-1650826349',
 'https://www.olx.in/item/compass-jeep-limited-single-owner-company-service-no-accident-history-iid-1650825827',
 'https://www.olx.in/item/toyota-innova-2012-diesel-103000-km-driven-iid-1650826157',
 'https://www.olx.in/item/honda-city-2021-petrol-1000-km-driven-iid-1650825952',
 'https://www.olx.in/item/maruti-suzuki-swift-2017-diesel-iid-1634168885',
 'https://www.olx.in/item/other-brands-others-2018-petrol-iid-1641919877',
 'https://www.olx.in/item/evry-cars-used-spare-parts-avail-on-demand-bmw-audi-vw-skoda-ford-etc-iid-1623410083',
 'https://www.olx.in/item/chevrolet-beat-2011-diesel-good-condition-iid-1650800227',
 'https://www.olx.in/item/toyota-qualis-fs-b1-2002-diesel-iid-1650344253',
 'https://www.olx.in/item/maruti-suzuki-swift-vdi-2014-diesel-iid-1649596342',
 'https://www.olx.in/item/toyota-innova-25-gx-diesel-8-seater-2013-diesel-iid-1634279648',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-taxi-2013-diesel-225000-km-driven-iid-1650825251',

In [8]:
producturl2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturl2.append(j.get_attribute('href'))

In [10]:
len(producturl2)

507

In [11]:
url2 = []
for i in producturl2:
    if i not in url2:
        url2.append(i)

In [12]:
len(url2)

506

In [193]:
brand1=[]
model1=[]
variant1=[]
manufacturingyear1=[]
driverkilometers1=[]
fuel1=[]
owners1=[]
location1=[]
price1=[]



for i in url2:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br1=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand1.append(br1.text)
    except NoSuchElementException:
        brand1.append('-')

#Model        
    try:
        mo1=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model1.append(mo1.text)
    except NoSuchElementException:
        model1.append('-')
        
#Variant
    try:
        var1=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant1.append(var1.text)
    except NoSuchElementException:
        variant1.append('-')

#Manufacturingyear
    try:
        yr1=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear1.append(yr1.text)
    except NoSuchElementException:
        manufacturingyear1.append('-')

#Kilometers Driven
    try:
        dr1=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers1.append(dr1.text)
    except NoSuchElementException:
        driverkilometers1.append('-')
        
#Fuel
    try:
        fl1=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel1.append(fl1.text)
    except NoSuchElementException:
        fuel1.append('-')

#no of owners
    try:
        own1=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners1.append(own1.text)
    except NoSuchElementException:
        owners1.append('-')
        
#location
    try:
        loc1=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location1.append(loc1.text)
    except NoSuchElementException:
        location1.append('-')
        
#Price
    try:
        pr1=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price1.append(pr1.text)
    except NoSuchElementException:
        price1.append('-')




brand1 = pd.DataFrame(brand1)            
brand1.columns=['brand']

model1 = pd.DataFrame(model1)            
model1.columns=['model']

variant1 = pd.DataFrame(variant1)            
variant1.columns=['variant']

manufacturingyear1 = pd.DataFrame(manufacturingyear1)            
manufacturingyear1.columns=['manufacturingyear']

driverkilometers1 = pd.DataFrame(driverkilometers1)            
driverkilometers1.columns=['driverkilometers']

fuel1 = pd.DataFrame(fuel1)            
fuel1.columns=['fuel']

owners1 = pd.DataFrame(owners1)            
owners1.columns=['owners']

location1 = pd.DataFrame(location1)            
location1.columns=['location']

price1 = pd.DataFrame(price1)            
price1.columns=['price']



car1=pd.DataFrame({})
car1['Brand']=brand1['brand']
car1['Model']=model1['model']
car1['Variant']=variant1['variant']
car1['Manufacturig year']=manufacturingyear1['manufacturingyear']
car1['Kilometers driven']=driverkilometers1['driverkilometers']
car1['Fuel']=fuel1['fuel']
car1['No of Owners']=owners1['owners']
car1['Location']=location1['location']
car1['Price']=price1['price']
car1
#kerala

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Innova Crysta,2.4 V,2017,"53,000 km",Diesel,2nd,"Puthanathani, Malappuram, Kerala","₹ 18,50,000"
1,Tata,Zest,-,2016,"60,000 km",Diesel,1st,"Ambattukavu, Kochi, Kerala","₹ 3,75,000"
2,Honda,City,-,1998,"86,000 km",Petrol,3rd,"Kowdiar, Thiruvananthapuram, Kerala","₹ 1,35,000"
3,-,-,-,-,-,-,-,-,-
4,BMW,5 Series,520d Luxury Line,2011,"140,000 km",Diesel,1st,"Koduvally, Kozhikode, Kerala","₹ 10,45,000"
...,...,...,...,...,...,...,...,...,...
501,Tata,Tiago,Wizz 1.2 Revotron,2017,"27,000 km",Petrol,1st,"Palarivattom, Kochi, Kerala","₹ 4,65,000"
502,Porsche,Cayenne,-,2017,123 km,Diesel,-,"Kaloor, Kochi, Kerala","₹ 77,77,777"
503,Mahindra,Bolero,SLE,2012,"120,000 km",Diesel,3rd,"Santhi Nagar, Kodungallur, Kerala","₹ 4,25,000"
504,BMW,5 Series,520d M Sport,2017,"65,000 km",Diesel,1st,"Edappally, Kochi, Kerala","₹ 32,00,000"
505,Mercedes-Benz,G,-,2012,"65,000 km",Petrol,2nd,"Edappally, Kochi, Kerala","₹ 70,00,000"

In [194]:
car1.to_csv (r'C:\Users\allen\car1.csv', index = False, header=True)

In [15]:
car1.drop(car1.loc[car1['Brand']=='-'].index, inplace=True)

In [16]:
len(car1)

477

In [19]:
car1

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Innova Crysta,2.4 V,2017,"53,000 km",Diesel,2nd,-,"₹ 18,50,000"
1,Tata,Zest,-,2016,"60,000 km",Diesel,1st,-,"₹ 3,75,000"
2,Honda,City,-,1998,"86,000 km",Petrol,3rd,-,"₹ 1,35,000"
4,BMW,5 Series,520d Luxury Line,2011,"140,000 km",Diesel,1st,-,"₹ 10,45,000"
5,Renault,KWID,Climber 1.0 MT Opt,2018,"13,000 km",Petrol,1st,-,"₹ 3,70,000"
...,...,...,...,...,...,...,...,...,...
501,Tata,Tiago,Wizz 1.2 Revotron,2017,"27,000 km",Petrol,1st,-,"₹ 4,65,000"
502,Porsche,Cayenne,-,2017,123 km,Diesel,-,-,"₹ 77,77,777"
503,Mahindra,Bolero,SLE,2012,"120,000 km",Diesel,3rd,-,"₹ 4,25,000"
504,BMW,5 Series,520d M Sport,2017,"65,000 km",Diesel,1st,-,"₹ 32,00,000"
505,Mercedes-Benz,G,-,2012,"65,000 km",Petrol,2nd,-,"₹ 70,00,000"

In [17]:
driver=webdriver.Chrome("chromedriver.exe")

In [18]:
url='https://www.olx.in/mumbai_g4058997/q-cars'
driver.get(url)

In [22]:
for i in range(0,25):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [23]:
producturl3=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturl3.append(j.get_attribute('href'))

In [24]:
len(producturl3)

500

In [25]:
url3 = []
for i in producturl3:
    if i not in url3:
        url3.append(i)

In [27]:
len(url3)

496

In [29]:
brand2=[]
model2=[]
variant2=[]
manufacturingyear2=[]
driverkilometers2=[]
fuel2=[]
owners2=[]
location2=[]
price2=[]



for i in url3:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br2=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand2.append(br2.text)
    except NoSuchElementException:
        brand2.append('-')

#Model        
    try:
        mo2=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model2.append(mo2.text)
    except NoSuchElementException:
        model2.append('-')
        
#Variant
    try:
        var2=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant2.append(var2.text)
    except NoSuchElementException:
        variant2.append('-')

#Manufacturingyear
    try:
        yr2=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear2.append(yr2.text)
    except NoSuchElementException:
        manufacturingyear2.append('-')

#Kilometers Driven
    try:
        dr2=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers2.append(dr2.text)
    except NoSuchElementException:
        driverkilometers2.append('-')
        
#Fuel
    try:
        fl2=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel2.append(fl2.text)
    except NoSuchElementException:
        fuel2.append('-')

#no of owners
    try:
        own2=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners2.append(own2.text)
    except NoSuchElementException:
        owners2.append('-')
        
#location
    try:
        loc2=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location2.append(loc2.text)
    except NoSuchElementException:
        location2.append('-')
        
#Price
    try:
        pr2=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price2.append(pr2.text)
    except NoSuchElementException:
        price2.append('-')




brand2 = pd.DataFrame(brand2)            
brand2.columns=['brand']

model2 = pd.DataFrame(model2)            
model2.columns=['model']

variant2 = pd.DataFrame(variant2)            
variant2.columns=['variant']

manufacturingyear2 = pd.DataFrame(manufacturingyear2)            
manufacturingyear2.columns=['manufacturingyear']

driverkilometers2 = pd.DataFrame(driverkilometers2)            
driverkilometers2.columns=['driverkilometers']

fuel2 = pd.DataFrame(fuel2)            
fuel2.columns=['fuel']

owners2 = pd.DataFrame(owners2)            
owners2.columns=['owners']

location2 = pd.DataFrame(location2)            
location2.columns=['location']

price2 = pd.DataFrame(price2)            
price2.columns=['price']



car2=pd.DataFrame({})
car2['Brand']=brand2['brand']
car2['Model']=model2['model']
car2['Variant']=variant2['variant']
car2['Manufacturig year']=manufacturingyear2['manufacturingyear']
car2['Kilometers driven']=driverkilometers2['driverkilometers']
car2['Fuel']=fuel2['fuel']
car2['No of Owners']=owners2['owners']
car2['Location']=location2['location']
car2['Price']=price2['price']
car2
#Mumbai

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Mahindra,TUV 300,T8 AMT,2015,"50,500 km",Diesel,1st,"Vile Parle West, Mumbai, Maharashtra","₹ 6,75,000"
1,Toyota,Corolla Altis,1.8 G,2018,"21,227 km",Petrol,1st,"Chembur, Mumbai, Maharashtra","₹ 10,21,700"
2,Skoda,Superb,2008-2013 Elegance 1.8 TSI AT,2015,"37,000 km",Petrol,2nd,"Vile Parle East, Mumbai, Maharashtra","₹ 12,25,000"
3,-,-,-,-,-,-,-,-,-
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
491,Toyota,Innova,2.5 G (Diesel) 7 Seater BS IV,2014,"111,771 km",Diesel,1st,"Kurla West, Mumbai, Maharashtra","₹ 9,99,000"
492,Maruti Suzuki,Swift Dzire,VDI,2012,"49,000 km",Diesel,1st,"Santacruz West, Mumbai, Maharashtra","₹ 4,39,000"
493,Maruti Suzuki,Vitara Brezza,ZDi,2019,"36,000 km",Diesel,1st,"Chembur, Mumbai, Maharashtra","₹ 9,75,111"
494,Volkswagen,Vento,1.2 TSI Highline,2011,"85,000 km",Petrol,2nd,"Chembur, Mumbai, Maharashtra","₹ 2,65,000"
495,Maruti Suzuki,-,-,2021,0 km,-,-,"Kurla East, Mumbai, Maharashtra","₹ 1,29,550"

In [30]:
car2.to_csv (r'C:\Users\allen\car2.csv', index = False, header=True)

In [32]:
car2.drop(car2.loc[car2['Brand']=='-'].index, inplace=True)

In [33]:
car2

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Mahindra,TUV 300,T8 AMT,2015,"50,500 km",Diesel,1st,"Vile Parle West, Mumbai, Maharashtra","₹ 6,75,000"
1,Toyota,Corolla Altis,1.8 G,2018,"21,227 km",Petrol,1st,"Chembur, Mumbai, Maharashtra","₹ 10,21,700"
2,Skoda,Superb,2008-2013 Elegance 1.8 TSI AT,2015,"37,000 km",Petrol,2nd,"Vile Parle East, Mumbai, Maharashtra","₹ 12,25,000"
5,Hyundai,Venue,SX Turbo,2021,1 km,-,-,"Sion East, Mumbai, Maharashtra","₹ 2,45,000"
6,Toyota,Fortuner,2.8 2WD AT,2013,"98,145 km",Diesel,2nd,"Chembur, Mumbai, Maharashtra","₹ 13,75,000"
...,...,...,...,...,...,...,...,...,...
491,Toyota,Innova,2.5 G (Diesel) 7 Seater BS IV,2014,"111,771 km",Diesel,1st,"Kurla West, Mumbai, Maharashtra","₹ 9,99,000"
492,Maruti Suzuki,Swift Dzire,VDI,2012,"49,000 km",Diesel,1st,"Santacruz West, Mumbai, Maharashtra","₹ 4,39,000"
493,Maruti Suzuki,Vitara Brezza,ZDi,2019,"36,000 km",Diesel,1st,"Chembur, Mumbai, Maharashtra","₹ 9,75,111"
494,Volkswagen,Vento,1.2 TSI Highline,2011,"85,000 km",Petrol,2nd,"Chembur, Mumbai, Maharashtra","₹ 2,65,000"
495,Maruti Suzuki,-,-,2021,0 km,-,-,"Kurla East, Mumbai, Maharashtra","₹ 1,29,550"

In [34]:
url2

['https://www.olx.in/item/toyota-innova-crysta-24-v-2017-diesel-iid-1633534874',
 'https://www.olx.in/item/tata-zest-2016-diesel-iid-1649277891',
 'https://www.olx.in/item/honda-city-1998-petrol-iid-1646994630',
 'https://www.olx.in/item/honda-city-2006-petrol-iid-1650467418',
 'https://www.olx.in/item/bmw-5-series-2011-diesel-luxury-line-hr-registration-single-owner-iid-1649440139',
 'https://www.olx.in/item/renault-kwid-climber-10-mt-opt-2018-petrol-iid-1650844324',
 'https://www.olx.in/item/renault-kwid-10-rxt-amt-opt-2017-petrol-iid-1650844290',
 'https://www.olx.in/item/ford-ikon-14-tdci-duratorq-2010-diesel-iid-1650844265',
 'https://www.olx.in/item/hyundai-i10-12-kappa-magna-2013-petrol-iid-1650844246',
 'https://www.olx.in/item/maruti-suzuki-celerio-vxi-amt-2014-petrol-iid-1650844217',
 'https://www.olx.in/item/hyundai-grand-i10-12-crdi-sportz-option-2013-diesel-iid-1650844190',
 'https://www.olx.in/item/hyundai-i20-2009-2011-magna-2011-petrol-iid-1650844169',
 'https://www.olx.in/item/hyundai-santro-xing-2008-petrol-72000-km-driven-iid-1646261971',
 'https://www.olx.in/item/chevrolet-sail-u-va-12-lt-abs-2013-petrol-iid-1650844153',
 'https://www.olx.in/item/toyota-etios-liva-2013-diesel-well-maintained-iid-1650844040',
 'https://www.olx.in/item/mahindra-jeep-1995-diesel-well-maintained-iid-1650843915',
 'https://www.olx.in/item/toyota-commuter-diesel-2014-diesel-iid-1650843645',
 'https://www.olx.in/item/mitsubishi-pajero-select-plus-4x4-mt-2011-diesel-iid-1650843591',
 'https://www.olx.in/item/skoda-rapid-2011-2013-16-tdi-active-2014-diesel-iid-1634135454',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2015-petrol-well-maintained-iid-1650843065',
 'https://www.olx.in/item/toyota-land-cruiser-v8-petrol-2007-petrol-iid-1647088073',
 'https://www.olx.in/item/jeep-compass-14-limited-option-2018-petrol-iid-1649996009',
 'https://www.olx.in/item/hyundai-verna-anniversary-edition-2018-iid-1649927466',
 'https://www.olx.in/item/hyundai-santro-xing-2008-petrol-iid-1642339922',
 'https://www.olx.in/item/toyota-innova-2007-diesel-well-maintained-iid-1645741242',
 'https://www.olx.in/item/ford-ikon-2003-iid-1645635738',
 'https://www.olx.in/item/honda-city-i-vtec-v-2018-petrol-iid-1650045255',
 'https://www.olx.in/item/audi-a4-20-tdi-177bhp-premium-2010-diesel-iid-1650045077',
 'https://www.olx.in/item/maruti-suzuki-swift-2004-2010-13-lxi-2006-petrol-iid-1625533434',
 'https://www.olx.in/item/toyota-innova-crysta-28-zx-at-2019-diesel-iid-1649237333',
 'https://www.olx.in/item/ford-ikon-2010-diesel-well-maintained-iid-1650842016',
 'https://www.olx.in/item/second-hand-omni-venam-iid-1650842008',
 'https://www.olx.in/item/toyota-innova-2012-diesel-235000-km-driven-iid-1650841825',
 'https://www.olx.in/item/maruti-suzuki-800-2010-petrol-good-condition-iid-1650841788',
 'https://www.olx.in/item/honda-amaze-2018-diesel-35500-km-driven-iid-1650841607',
 'https://www.olx.in/item/tata-nano-2010-petrol-good-condition-iid-1650841342',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-2010-petrol-82000-km-driven-iid-1650841217',
 'https://www.olx.in/item/used-car-loan-kuwy-iid-1566588557',
 'https://www.olx.in/item/mahindra-thar-crde-4x4-bs-iv-2021-diesel-iid-1649236350',
 'https://www.olx.in/item/mercedes-benz-s-class-s-500-l-2011-petrol-iid-1650003289',
 'https://www.olx.in/item/used-car-loan-service-iid-1649735883',
 'https://www.olx.in/item/mercedes-benz-new-c-class-c-250-cdi-avantgarde-2012-diesel-iid-1646388547',
 'https://www.olx.in/item/audi-a6-20-tdi-premium-plus-2012-diesel-iid-1632551691',
 'https://www.olx.in/item/tata-xenon-xt-2014-diesel-well-maintained-iid-1650840998',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2016-petrol-33000-km-driven-no-accident-history-iid-1650840445',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-10-2004-petrol-980000-km-driven-iid-1650840427',
 'https://www.olx.in/item/maruti-suzuki-swift-2018-vdi-2018-diesel-iid-1644356961',
 'https://www.olx.in/item/hyundai-eon-era-2012-petrol-iid-1643529316',
 'https://www.olx.in/item/maruti-suzuki-alto-2010-petrol-good-condition-iid-1650840118',
 'https://www.olx.in/item/ford-fiesta-2008-2011-16-duratec-exi-2011-petrol-iid-1650840092',
 'https://www.olx.in/item/mitsubishi-lancer-20-exel-2005-diesel-iid-1650839832',
 'https://www.olx.in/item/toyota-etios-15-g-2014-petrol-iid-1650042505',
 'https://www.olx.in/item/wide-range-of-premium-quality-head-lamp-for-cars-iid-1610833492',
 'https://www.olx.in/item/tata-nexon-2021-petrol-good-condition-iid-1650839553',
 'https://www.olx.in/item/mahindra-jeep-1992-diesel-98000-km-driven-iid-1650839528',
 'https://www.olx.in/item/audi-q7-2013-diesel-92000-km-driven-iid-1650839519',
 'https://www.olx.in/item/ritz-vxi-2015-iid-1650839474',
 'https://www.olx.in/item/honda-brio-12-s-mt-2012-petrol-iid-1646027279',
 'https://www.olx.in/item/eon-era-plus-2017-iid-1649713281',
 'https://www.olx.in/item/volkswagen-jetta-19-highline-tdi-2010-diesel-iid-1627026993',
 'https://www.olx.in/item/toyota-etios-liva-2019-petrol-good-condition-iid-1650837815',
 'https://www.olx.in/item/toyota-innova-2016-iid-1650839131',
 'https://www.olx.in/item/nissan-sunny-2012-diesel-good-condition-iid-1650839072',
 'https://www.olx.in/item/maruti-suzuki-alto-2019-petrol-13000-km-driven-iid-1650839062',
 'https://www.olx.in/item/maruti-suzuki-800-2004-petrol-100800-km-driven-iid-1644874652',
 'https://www.olx.in/item/hyundai-i10-12-kappa-magna-2011-petrol-iid-1614584935',
 'https://www.olx.in/item/volkswagen-ameo-15-tdi-trendline-2017-diesel-iid-1644355204',
 'https://www.olx.in/item/skoda-rapid-15-tdi-active-2012-diesel-iid-1634131861',
 'https://www.olx.in/item/corolla-altis-2011-model-single-owner-iid-1650838674',
 'https://www.olx.in/item/mahindra-bolero-2012-diesel-well-maintaine-iid-1650838645',
 'https://www.olx.in/item/hindustan-motors-ambassador-2006-diesel-stride-engine-iid-1650838232',
 'https://www.olx.in/item/maruti-suzuki-alto-800-lxi-2018-petrol-iid-1645174783',
 'https://www.olx.in/item/maruti-suzuki-ertiga-shvs-vdi-2017-diesel-iid-1645174528',
 'https://www.olx.in/item/mahindra-others-1986-diesel-iid-1614583807',
 'https://www.olx.in/item/honda-city-2011-2013-s-2013-petrol-iid-1650041012',
 'https://www.olx.in/item/maruti-suzuki-baleno-zeta-2018-diesel-iid-1643239711',
 'https://www.olx.in/item/maruti-suzuki-swift-vdi-bs-iv-2008-diesel-iid-1648196195',
 'https://www.olx.in/item/201918-tata-nexon-xza-plus-dual-tone-automatic-18000-km-single-owner-iid-1647320973',
 'https://www.olx.in/item/maruti-suzuki-swift-2018-petrol-well-maintained-iid-1650837809',
 'https://www.olx.in/item/maruti-suzuki-celerio-vxi-amt-2016-petrol-iid-1646753155',
 'https://www.olx.in/item/maruti-suzuki-zen-1999-ac-iid-1612290578',
 'https://www.olx.in/item/honda-jazz-12-s-i-vtec-2016-petrol-iid-1650837572',
 'https://www.olx.in/item/ford-fiesta-2008-diesel-well-maintained-iid-1650837408',
 'https://www.olx.in/item/powerstairing-ac-sentral-ac-new-tair-sentral-lok-new-ensur-new-pepar-iid-1650837370',
 'https://www.olx.in/item/very-good-condition-car-iid-1650837270',
 'https://www.olx.in/item/neat-and-clean-maruti-800-mpfi-5-speed-iid-1650837219',
 'https://www.olx.in/item/maruti-suzuki-baleno-diesel-alpha-2016-iid-1650836942',
 'https://www.olx.in/item/volkswagen-vento-2012-diesel-49000-km-driven-iid-1650836770',
 'https://www.olx.in/item/ford-fiesta-zxi-16-2009-diesel-iid-1635320233',
 'https://www.olx.in/item/audi-q3-2015-diesel-iid-1592630591',
 'https://www.olx.in/item/hyundai-grand-i10-asta-automatic-12-kappa-vtvt-2015-petrol-iid-1647581391',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-vxi-amt-2018-petrol-iid-1647581127',
 'https://www.olx.in/item/hyundai-verna-crdi-16-sx-2011-diesel-iid-1634130457',
 'https://www.olx.in/item/volkswagen-crosspolo-2013-2015-15-tdi-2015-diesel-iid-1648171063',
 'https://www.olx.in/item/renault-pulse-rxl-abs-diesel-2014-diesel-iid-1632186365',
 'https://www.olx.in/item/volkswagen-polo-15-tdi-highline-2017-diesel-iid-1628324033',
 'https://www.olx.in/item/nissan-micra-xv-cvt-2016-petrol-iid-1650836666',
 'https://www.olx.in/item/kenwood-car-amp-500w-iid-1650836599',
 'https://www.olx.in/item/alto-k10-vxi-iid-1650836376',
 'https://www.olx.in/item/toyota-innova-2005-diesel-good-condition-family-used-car-al-paper-new-iid-1650836129',
 'https://www.olx.in/item/maruti-suzuki-800-1999-petrol-well-maintained-iid-1650836118',
 'https://www.olx.in/item/hyundai-creta-2018-petrol-well-maintained-iid-1650835841',
 'https://www.olx.in/item/car-for-rent-iid-1650835777',
 'https://www.olx.in/item/hyundai-eon-2013-petrol-65000-km-driven-iid-1650835688',
 'https://www.olx.in/item/maruti-suzuki-alto-2011-petrol-67000-km-driven-iid-1650835656',
 'https://www.olx.in/item/datsun-go-t-2016-petrol-iid-1649722630',
 'https://www.olx.in/item/hyundai-creta-16-s-automatic-diesel-2016-diesel-iid-1648409905',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-2011-petrol-iid-1643523601',
 'https://www.olx.in/item/toyota-innova-25-g-diesel-8-seater-2009-diesel-iid-1643523258',
 'https://www.olx.in/item/tata-nexon-12-revotron-xm-2019-petrol-iid-1647580879',
 'https://www.olx.in/item/honda-jazz-2016-petrol-well-maintained-iid-1650835375',
 'https://www.olx.in/item/hyundai-i20-2012-diesel-80000-km-driven-iid-1644854843',
 'https://www.olx.in/item/chevrolet-beat-2010-2013-diesel-ps-2011-diesel-iid-1625729137',
 'https://www.olx.in/item/maruti-suzuki-sx4-2007-2012-zxi-bsiii-2007-petrol-iid-1650321428',
 'https://www.olx.in/item/maruti-suzuki-ritz-2010-diesel-well-maintained-iid-1650835024',
 'https://www.olx.in/item/maruti-suzuki-a-star-2012-iid-1650834693',
 'https://www.olx.in/item/maruti-suzuki-800-2006-petrol-82000-km-driven-iid-1643885341',
 'https://www.olx.in/item/toyota-others-2021-petrol-iid-1650615198',
 'https://www.olx.in/item/tata-indica-vista-2008-2013-aqua-tdi-bsiii-2009-diesel-iid-1605460218',
 'https://www.olx.in/item/hyundai-i10-era-2010-petrol-iid-1610408248',
 'https://www.olx.in/item/volkswagen-jetta-20l-tdi-highline-at-2015-diesel-iid-1650834350',
 'https://www.olx.in/item/30000-car--iid-1650834346',
 'https://www.olx.in/item/ford-figo-2010-2012-diesel-zxi-2010-diesel-iid-1613574851',
 'https://www.olx.in/item/toyota-innova-25-gx-diesel-8-seater-bs-iv-2016-diesel-iid-1650589963',
 'https://www.olx.in/item/honda-br-v-2016-petrol-51669-km-driven-iid-1650834318',
 'https://www.olx.in/item/maruti-suzuki-zen-d-ps-2002-diesel-iid-1618546813',
 'https://www.olx.in/item/wagon-r-2011-excellent-condition-iid-1650834306',
 'https://www.olx.in/item/mahindra-scorpio-2006-2009-slx-26-turbo-7-str-2006-diesel-iid-1626275503',
 'https://www.olx.in/item/tata-nano-2012-2015-twist-xe-2015-petrol-iid-1633950033',
 'https://www.olx.in/item/maruti-suzuki-eeco-5-str-with-achtr-2020-petrol-iid-1648251267',
 'https://www.olx.in/item/hyundai-i10-magna-2009-petrol-iid-1644887985',
 'https://www.olx.in/item/toyota-innova-25-v-7-str-2013-diesel-iid-1648173267',
 'https://www.olx.in/item/hyundai-grand-i10-2013-2016-at-asta-2014-petrol-iid-1634917000',
 'https://www.olx.in/item/toyota-fortuner-30-4x4-manual-2010-diesel-iid-1649689145',
 'https://www.olx.in/item/maruti-suzuki-estilo-lxi-2011-petrol-iid-1649229003',
 'https://www.olx.in/item/maruti-suzuki-alto-k10-lxi-2015-petrol-iid-1649228403',
 'https://www.olx.in/item/hyundai-eon-era-2016-petrol-iid-1649228317',
 'https://www.olx.in/item/mahindra-thar-crde-4x4-bs-iv-2016-diesel-iid-1643521424',
 'https://www.olx.in/item/ashok-leyland-others-2018-diesel-iid-1643522124',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-tour-ldi-2016-diesel-iid-1638903882',
 'https://www.olx.in/item/honda-amaze-2013-diesel-well-maintained-iid-1650833902',
 'https://www.olx.in/item/hyundai-santro-2008-petrol-well-maintained-iid-1650833776',
 'https://www.olx.in/item/renult-duster-automatic-iid-1644122344',
 'https://www.olx.in/item/ibell-car-stereo-iid-1650833408',
 'https://www.olx.in/item/toyota-fortuner-28-4wd-mt-2017-diesel-iid-1650833163',
 'https://www.olx.in/item/jaguar-xf-22-diesel-2019-diesel-iid-1650832840',
 'https://www.olx.in/item/maruti-suzuki-a-star-zxi-2009-petrol-iid-1649227141',
 'https://www.olx.in/item/mercedes-benz-e-class-exclusive-e-220-d-2019-diesel-iid-1650181679',
 'https://www.olx.in/item/porsche-cayenne-s-diesel-2014-diesel-iid-1643592230',
 'https://www.olx.in/item/maruti-suzuki-zen-estilo-lxi-bsiii-2007-petrol-iid-1635063706',
 'https://www.olx.in/item/toyota-etios-liva-14-gd-2015-diesel-iid-1649226580',
 'https://www.olx.in/item/maruti-suzuki-baleno-12-delta-2017-petrol-iid-1649226902',
 'https://www.olx.in/item/8000-sqft-car-work-shop--iid-1641610787',
 'https://www.olx.in/item/premier-rio-2009-2011-dx-2010-diesel-iid-1649226878',
 'https://www.olx.in/item/toyota-corolla-altis-18-j-2009-petrol-iid-1649226399',
 'https://www.olx.in/item/chevrolet-spark-2007-2012-10-lt-2012-petrol-iid-1642716188',
 'https://www.olx.in/item/chevrolet-cruze-2010-2011-ltz-2010-diesel-iid-1641927553',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-vxi-minor-2009-petrol-iid-1638902569',
 'https://www.olx.in/item/showroom-condition-iid-1650832393',
 'https://www.olx.in/item/hyundai-creta-16-sx-automatic-diesel-2016-diesel-iid-1650832327',
 'https://www.olx.in/item/tata-harrier-xza-camo-automatic-iid-1650832155',
 'https://www.olx.in/item/tata-tiago-diesel-single-owner-2017-registered-iid-1650832099',
 'https://www.olx.in/item/new--iid-1650831992',
 'https://www.olx.in/item/toyota-qualis-2004-diesel-good-condition-iid-1650831947',
 'https://www.olx.in/item/datsun-go-plus-2015-petrol-well-maintained-iid-1650831799',
 'https://www.olx.in/item/renault-kwid-10-rxt-amt-opt-2017-petrol-iid-1649909026',
 'https://www.olx.in/item/toyota-yaris-g-optional-2020-petrol-iid-1646406138',
 'https://www.olx.in/item/other-brands-others-2017-iid-1629835489',
 'https://www.olx.in/item/renault-kwid-2019-rxt-1000cc-iid-1650831736',
 'https://www.olx.in/item/maruthi-suzuki-ertiga-zdi-2015-well-maintained-iid-1650831737',
 'https://www.olx.in/item/mahindra-bolero-2011-diesel-good-condition-no-accident-fulloption-iid-1650831696',
 'https://www.olx.in/item/toyota-innova-2006-diesel-198000-km-driven-iid-1650831627',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2012-petrol-69872-km-driven-iid-1650831563',
 'https://www.olx.in/item/clean-body-crd-type-extra-fitting-worth-1-lakh-4-cross-4-iid-1650831391',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-comfortline-2017-petrol-iid-1650831187',
 'https://www.olx.in/item/maruti-suzuki-ritz-zxi-2015-petrol-iid-1649225906',
 'https://www.olx.in/item/tata-sumo-victa-gx-tc-8-str-2004-diesel-iid-1649225157',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-bsii-2007-petrol-iid-1642714796',
 'https://www.olx.in/item/maruti-suzuki-omni-5-seater-2007-petrol-iid-1641926510',
 'https://www.olx.in/item/bmw-5-series-520d-2009-diesel-iid-1634126320',
 'https://www.olx.in/item/toyota-fortuner-trd-sportivo-28-2wd-at-2014-diesel-iid-1650033695',
 'https://www.olx.in/item/maruti-suzuki-omni-iid-1650830870',
 'https://www.olx.in/item/hyundai-xcent-2014-petrol-38000km-iid-1650830799',
 'https://www.olx.in/item/audi-q7-45-tdi-quattro-premium-plus-2016-diesel-iid-1650294898',
 'https://www.olx.in/item/renault-fluence-15-e4-2011-diesel-iid-1630514373',
 'https://www.olx.in/item/hyundai-i20-14-asta-2012-diesel-iid-1647211469',
 'https://www.olx.in/item/other-brands-others-2018-diesel-iid-1650830758',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2018-petrol-iid-1650830638',
 'https://www.olx.in/item/mahindra-jeep-1986-diesel-well-maintained-iid-1650830516',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-highline-plus-2014-petrol-iid-1650830485',
 'https://www.olx.in/item/2015-renault-lodgy-full-option-iid-1650830439',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2010-diesel-130000-km-driven-family-use-iid-1650829863',
 'https://www.olx.in/item/renault-duster-2016-diesel-well-maintained-iid-1650829458',
 'https://www.olx.in/item/mahindra-thar-2011-diesel-well-maintained-iid-1649715787',
 'https://www.olx.in/item/ford-ecosport-15-petrol-titanium-plus-2018-diesel-iid-1649222906',
 'https://www.olx.in/item/volkswagen-polo-12-mpi-comfortline-2016-petrol-iid-1648402213',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-vxi-minor-2009-petrol-iid-1647573571',
 'https://www.olx.in/item/nissan-terrano-xl-d-option-2015-diesel-iid-1638222855',
 'https://www.olx.in/item/hyundai-i10-2011-petrol-well-maintained-iid-1650829241',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-2017-petrol-59000-km-driven-iid-1650829092',
 'https://www.olx.in/item/hyundai-eonuber-ola-attached-single-ownerall-paper-clear-iid-1650828996',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-amt-vxi-2016-petrol-iid-1641013444',
 'https://www.olx.in/item/maruti-suzuki-swift-2014-diesel-well-maintained-iid-1645499268',
 'https://www.olx.in/item/hyundai-venue-s-2019-petrol-iid-1650704906',
 'https://www.olx.in/item/maruti-suzuki-alto-800-2005-petrol-iid-1650828913',
 'https://www.olx.in/item/maruti-suzuki-swift-2014-iid-1573259783',
 'https://www.olx.in/item/renault-triber-iid-1650828316',
 'https://www.olx.in/item/hyundai-eon-2015-petrol-well-maintained-iid-1650828180',
 'https://www.olx.in/item/volkswagen-vento-15-tdi-highline-2011-diesel-iid-1650828141',
 'https://www.olx.in/item/mg-hector-sharp-at-2019-petrol-iid-1650828064',
 'https://www.olx.in/item/battery-for-carnano800-iid-1650827922',
 'https://www.olx.in/item/value-for-money-iid-1650827798',
 'https://www.olx.in/item/jeep-compass-14-limited-2018-diesel-iid-1650827739',
 'https://www.olx.in/item/mahindra-xuv500-2011-2015-w8-2wd-2012-diesel-iid-1649220043',
 'https://www.olx.in/item/toyota-qualis-fs-b2-2001-diesel-iid-1647571946',
 'https://www.olx.in/item/honda-city-2015-2017-i-vtec-vx-2017-petrol-iid-1647571082',
 'https://www.olx.in/item/maruti-suzuki-ciaz-2014-2017-vxi-plus-2015-petrol-iid-1646741597',
 'https://www.olx.in/item/maruti-suzuki-800-1997-petrol-iid-1650827485',
 'https://www.olx.in/item/toyota-innova-25-gx-8-str-bs-iii-2015-diesel-iid-1650827224',
 'https://www.olx.in/item/hyundai-santro-xing-gls-2006-petrol-iid-1647093451',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2006-2010-lxi-minor-2007-petrol-iid-1643796270',
 'https://www.olx.in/item/toyota-innova-75000-km-driven-iid-1650678147',
 'https://www.olx.in/item/hyundai-santro-xing-2010-petrol-97500-km-driven-iid-1650827168',
 'https://www.olx.in/item/maruti-suzuki-wagon-r-2013-petrol-74000-km-driven-iid-1650827044',
 'https://www.olx.in/item/kwid-automatic-for-sale-iid-1650827009',
 'https://www.olx.in/item/maruti-suzuki-a-star-2009-petrol-well-maintained-iid-1650826979',
 'https://www.olx.in/item/venta-16-tdi-highline-maintained-well-iid-1650826896',
 'https://www.olx.in/item/kia-others-2021-petrol-iid-1650826789',
 'https://www.olx.in/item/toyota-innova-2018-diesel-good-condition-iid-1650826573',
 'https://www.olx.in/item/maruti-suzuki-alto-2007-petrol-1-km-driven-iid-1650826349',
 'https://www.olx.in/item/compass-jeep-limited-single-owner-company-service-no-accident-history-iid-1650825827',
 'https://www.olx.in/item/toyota-innova-2012-diesel-103000-km-driven-iid-1650826157',
 'https://www.olx.in/item/honda-city-2021-petrol-1000-km-driven-iid-1650825952',
 'https://www.olx.in/item/maruti-suzuki-swift-2017-diesel-iid-1634168885',
 'https://www.olx.in/item/other-brands-others-2018-petrol-iid-1641919877',
 'https://www.olx.in/item/evry-cars-used-spare-parts-avail-on-demand-bmw-audi-vw-skoda-ford-etc-iid-1623410083',
 'https://www.olx.in/item/chevrolet-beat-2011-diesel-good-condition-iid-1650800227',
 'https://www.olx.in/item/toyota-qualis-fs-b1-2002-diesel-iid-1650344253',
 'https://www.olx.in/item/maruti-suzuki-swift-vdi-2014-diesel-iid-1649596342',
 'https://www.olx.in/item/toyota-innova-25-gx-diesel-8-seater-2013-diesel-iid-1634279648',
 'https://www.olx.in/item/maruti-suzuki-swift-dzire-taxi-2013-diesel-225000-km-driven-iid-1650825251',

In [37]:
len(car1),len(car2)

(477, 435)

In [38]:
driver=webdriver.Chrome("chromedriver.exe")

In [39]:
url='https://www.olx.in/karnataka-circle_g5315536/q-cars'
driver.get(url)

In [40]:
for i in range(0,28):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [41]:
producturlk1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlk1.append(j.get_attribute('href'))

In [43]:
len(producturlk1)

562

In [44]:
driver=webdriver.Chrome("chromedriver.exe")

In [46]:
url='https://www.olx.in/bangalore-airport-area_g5313775/q-cars'
driver.get(url)

In [47]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [48]:
producturlk2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlk2.append(j.get_attribute('href'))

In [49]:
len(producturlk2)

561

In [50]:
for i in producturlk2 :
    producturlk1.append(i)

In [53]:
url4 = []
for i in producturlk1:
    if i not in url4:
        url4.append(i)

In [54]:
len(url4)

1109

In [59]:
brand3=[]
model3=[]
variant3=[]
manufacturingyear3=[]
driverkilometers3=[]
fuel3=[]
owners3=[]
location3=[]
price3=[]



for i in url4:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br3=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand3.append(br3.text)
    except NoSuchElementException:
        brand3.append('-')

#Model        
    try:
        mo3=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model3.append(mo3.text)
    except NoSuchElementException:
        model3.append('-')
        
#Variant
    try:
        var3=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant3.append(var3.text)
    except NoSuchElementException:
        variant3.append('-')

#Manufacturingyear
    try:
        yr3=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear3.append(yr3.text)
    except NoSuchElementException:
        manufacturingyear3.append('-')

#Kilometers Driven
    try:
        dr3=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers3.append(dr3.text)
    except NoSuchElementException:
        driverkilometers3.append('-')
        
#Fuel
    try:
        fl3=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel3.append(fl3.text)
    except NoSuchElementException:
        fuel3.append('-')

#no of owners
    try:
        own3=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners3.append(own3.text)
    except NoSuchElementException:
        owners3.append('-')
        
#location
    try:
        loc3=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location3.append(loc3.text)
    except NoSuchElementException:
        location3.append('-')
        
#Price
    try:
        pr3=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price3.append(pr3.text)
    except NoSuchElementException:
        price3.append('-')




brand3 = pd.DataFrame(brand3)            
brand3.columns=['brand']

model3 = pd.DataFrame(model3)            
model3.columns=['model']

variant3 = pd.DataFrame(variant3)            
variant3.columns=['variant']

manufacturingyear3 = pd.DataFrame(manufacturingyear3)            
manufacturingyear3.columns=['manufacturingyear']

driverkilometers3 = pd.DataFrame(driverkilometers3)            
driverkilometers3.columns=['driverkilometers']

fuel3 = pd.DataFrame(fuel3)            
fuel3.columns=['fuel']

owners3 = pd.DataFrame(owners3)            
owners3.columns=['owners']

location3 = pd.DataFrame(location3)            
location3.columns=['location']

price3 = pd.DataFrame(price3)            
price3.columns=['price']



car3=pd.DataFrame({})
car3['Brand']=brand3['brand']
car3['Model']=model3['model']
car3['Variant']=variant3['variant']
car3['Manufacturig year']=manufacturingyear3['manufacturingyear']
car3['Kilometers driven']=driverkilometers3['driverkilometers']
car3['Fuel']=fuel3['fuel']
car3['No of Owners']=owners3['owners']
car3['Location']=location3['location']
car3['Price']=price3['price']
car3
#karnataka

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,-,-,-,-,-,-,-,"Karnataka Circle, Hubballi, Karnataka","₹ 69,000"
1,Honda,City,V,2015,"93,995 km",Petrol,1st,"Unkal, Hubballi, Karnataka","₹ 6,35,000"
2,Hyundai,Creta,1.6 SX (O),2018,"41,475 km",Diesel,1st,"Unkal, Hubballi, Karnataka","₹ 14,50,000"
3,Honda,Amaze,1.5 SMT I DTEC,2018,"37,000 km",Diesel,1st,"Byridewarakoppa, Hubballi, Karnataka","₹ 7,80,000"
4,Volkswagen,Vento,1.5 TDI Highline,2011,"115,000 km",Diesel,1st,"Byridewarakoppa, Hubballi, Karnataka","₹ 4,50,000"
...,...,...,...,...,...,...,...,...,...
1104,-,-,-,-,-,-,-,-,-
1105,-,-,-,-,-,-,-,-,-
1106,-,-,-,-,-,-,-,-,-
1107,-,-,-,-,-,-,-,-,-
1108,-,-,-,-,-,-,-,-,-

In [60]:
car3.to_csv (r'C:\Users\allen\car3.csv', index = False, header=True)

In [61]:
car3.drop(car3.loc[car3['Brand']=='-'].index, inplace=True)

In [62]:
car3

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
1,Honda,City,V,2015,"93,995 km",Petrol,1st,"Unkal, Hubballi, Karnataka","₹ 6,35,000"
2,Hyundai,Creta,1.6 SX (O),2018,"41,475 km",Diesel,1st,"Unkal, Hubballi, Karnataka","₹ 14,50,000"
3,Honda,Amaze,1.5 SMT I DTEC,2018,"37,000 km",Diesel,1st,"Byridewarakoppa, Hubballi, Karnataka","₹ 7,80,000"
4,Volkswagen,Vento,1.5 TDI Highline,2011,"115,000 km",Diesel,1st,"Byridewarakoppa, Hubballi, Karnataka","₹ 4,50,000"
5,Toyota,Innova Crysta,2.4 VX MT 8S,2016,"130,000 km",Diesel,1st,"Unkal, Hubballi, Karnataka","₹ 17,60,000"
...,...,...,...,...,...,...,...,...,...
1053,Mercedes-Benz,E-Class,E250 CDI Elegance,2014,"48,800 km",Diesel,1st,"Koramangala, Bengaluru, Karnataka","₹ 26,50,000"
1054,Hyundai,Grand i10,1.2 Kappa Magna,2019,"13,000 km",Petrol,1st,"Sarjapur Road, Bengaluru, Karnataka","₹ 5,60,000"
1055,Ford,Ecosport,1.5 Diesel Titanium,2016,"60,000 km",Diesel,1st,"Hsr Layout Sector 7, Bengaluru, Karnataka","₹ 8,50,000"
1056,Honda,Jazz,2011-2013 S,2012,"21,000 km",Petrol,3rd,"Puttappa Layout, Bengaluru, Karnataka","₹ 4,50,000"
1057,Volkswagen,Vento,Sport 1.6 TSI MT,2015,"50,000 km",Petrol,2nd,"Koramangala, Bengaluru, Karnataka","₹ 6,50,000"

In [63]:
driver=webdriver.Chrome("chromedriver.exe")

In [65]:
url='https://www.olx.in/tolichowki_g5338350/q-cars'
driver.get(url)

In [68]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [69]:
producturlh1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlh1.append(j.get_attribute('href'))

In [70]:
len(producturlh1)

543

In [71]:
driver=webdriver.Chrome("chromedriver.exe")

In [72]:
url='https://www.olx.in/uppal_g5339042/q-cars'
driver.get(url)

In [75]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [76]:
producturlh2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlh2.append(j.get_attribute('href'))

In [77]:
len(producturlh2)

543

In [78]:
for i in producturlh2 :
    producturlh1.append(i)

In [79]:
len(producturlh1)

1086

In [80]:
url5 = []
for i in producturlh1:
    if i not in url5:
        url5.append(i)

In [81]:
len(url5)

1025

In [82]:
brand4=[]
model4=[]
variant4=[]
manufacturingyear4=[]
driverkilometers4=[]
fuel4=[]
owners4=[]
location4=[]
price4=[]



for i in url5:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br4=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand4.append(br4.text)
    except NoSuchElementException:
        brand4.append('-')

#Model        
    try:
        mo4=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model4.append(mo4.text)
    except NoSuchElementException:
        model4.append('-')
        
#Variant
    try:
        var4=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant4.append(var4.text)
    except NoSuchElementException:
        variant4.append('-')

#Manufacturingyear
    try:
        yr4=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear4.append(yr4.text)
    except NoSuchElementException:
        manufacturingyear4.append('-')

#Kilometers Driven
    try:
        dr4=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers4.append(dr4.text)
    except NoSuchElementException:
        driverkilometers4.append('-')
        
#Fuel
    try:
        fl4=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel4.append(fl4.text)
    except NoSuchElementException:
        fuel4.append('-')

#no of owners
    try:
        own4=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners4.append(own4.text)
    except NoSuchElementException:
        owners4.append('-')
        
#location
    try:
        loc4=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location4.append(loc4.text)
    except NoSuchElementException:
        location4.append('-')
        
#Price
    try:
        pr4=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price4.append(pr4.text)
    except NoSuchElementException:
        price4.append('-')




brand4 = pd.DataFrame(brand4)            
brand4.columns=['brand']

model4 = pd.DataFrame(model4)            
model4.columns=['model']

variant4 = pd.DataFrame(variant4)            
variant4.columns=['variant']

manufacturingyear4 = pd.DataFrame(manufacturingyear4)            
manufacturingyear4.columns=['manufacturingyear']

driverkilometers4 = pd.DataFrame(driverkilometers4)            
driverkilometers4.columns=['driverkilometers']

fuel4 = pd.DataFrame(fuel4)            
fuel4.columns=['fuel']

owners4 = pd.DataFrame(owners4)            
owners4.columns=['owners']

location4 = pd.DataFrame(location4)            
location4.columns=['location']

price4 = pd.DataFrame(price4)            
price4.columns=['price']



car4=pd.DataFrame({})
car4['Brand']=brand4['brand']
car4['Model']=model4['model']
car4['Variant']=variant4['variant']
car4['Manufacturig year']=manufacturingyear4['manufacturingyear']
car4['Kilometers driven']=driverkilometers4['driverkilometers']
car4['Fuel']=fuel4['fuel']
car4['No of Owners']=owners4['owners']
car4['Location']=location4['location']
car4['Price']=price4['price']
car4
#Hyderabad

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Skoda,Yeti,2009-2013 Ambition 4X2,2012,"106,000 km",Diesel,1st,"Banjara Hills, Hyderabad, Telangana","₹ 6,45,000"
1,Hyundai,i20,2015-2017 Sportz 1.4 CRDi,2017,"50,000 km",Diesel,2nd,"Mushk Mahal, Hyderabad, Telangana","₹ 5,85,000"
2,Land Rover,Freelander 2,SE,2011,"84,000 km",Diesel,1st,"Banjara Hills, Hyderabad, Telangana","₹ 14,45,000"
3,-,-,-,-,-,-,-,-,-
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
1020,Hyundai,Santro Xing,GLS,2012,"48,362 km",Petrol,1st,"Adarsh Nagar Colony, LB Nagar, Telangana","₹ 2,80,000"
1021,Hyundai,Grand i10,Asta Automatic 1.2 Kappa VTVT,2015,"53,494 km",Petrol,1st,"Adarsh Nagar Colony, LB Nagar, Telangana","₹ 5,90,000"
1022,Maruti Suzuki,Swift,VDI,2011,"82,255 km",Diesel,1st,"Uppal, Hyderabad, Telangana","₹ 3,55,000"
1023,Honda,City,2008-2011 1.5 S MT,2009,"90,000 km",Petrol,1st,"LB Nagar, Hyderabad, Telangana","₹ 3,40,000"
1024,Volkswagen,Polo,2009-2013 Diesel Highline 1.2L,2010,"88,950 km",Diesel,2nd,"LB Nagar, Hyderabad, Telangana","₹ 3,20,000"

In [83]:
car4.to_csv (r'C:\Users\allen\car4.csv', index = False, header=True)

In [84]:
car4.drop(car4.loc[car4['Brand']=='-'].index, inplace=True)

In [85]:
car4

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Skoda,Yeti,2009-2013 Ambition 4X2,2012,"106,000 km",Diesel,1st,"Banjara Hills, Hyderabad, Telangana","₹ 6,45,000"
1,Hyundai,i20,2015-2017 Sportz 1.4 CRDi,2017,"50,000 km",Diesel,2nd,"Mushk Mahal, Hyderabad, Telangana","₹ 5,85,000"
2,Land Rover,Freelander 2,SE,2011,"84,000 km",Diesel,1st,"Banjara Hills, Hyderabad, Telangana","₹ 14,45,000"
5,Maruti Suzuki,S-Cross,Zeta 1.3,2018,"39,000 km",Diesel,1st,"Madhura Nagar, Hyderabad, Telangana","₹ 9,96,000"
6,Maruti Suzuki,Swift Dzire,1.2 Vxi BSIV,2012,"33,000 km",Petrol,1st,"Panjagutta, Hyderabad, Telangana","₹ 3,85,000"
...,...,...,...,...,...,...,...,...,...
1020,Hyundai,Santro Xing,GLS,2012,"48,362 km",Petrol,1st,"Adarsh Nagar Colony, LB Nagar, Telangana","₹ 2,80,000"
1021,Hyundai,Grand i10,Asta Automatic 1.2 Kappa VTVT,2015,"53,494 km",Petrol,1st,"Adarsh Nagar Colony, LB Nagar, Telangana","₹ 5,90,000"
1022,Maruti Suzuki,Swift,VDI,2011,"82,255 km",Diesel,1st,"Uppal, Hyderabad, Telangana","₹ 3,55,000"
1023,Honda,City,2008-2011 1.5 S MT,2009,"90,000 km",Petrol,1st,"LB Nagar, Hyderabad, Telangana","₹ 3,40,000"
1024,Volkswagen,Polo,2009-2013 Diesel Highline 1.2L,2010,"88,950 km",Diesel,2nd,"LB Nagar, Hyderabad, Telangana","₹ 3,20,000"

In [86]:
driver=webdriver.Chrome("chromedriver.exe")

In [87]:
url='https://www.olx.in/goa_g2001153/q-used-cars?isSearchCall=true'
driver.get(url)

In [90]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [92]:
producturlg1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlg1.append(j.get_attribute('href'))

In [99]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [95]:
producturlg2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlg2.append(j.get_attribute('href'))

In [96]:
len(producturlg2)

590

In [97]:
for i in producturlg2 :
    producturlg1.append(i)

In [98]:
len(producturlg1)

1091

In [100]:
url6 = []
for i in producturlg1:
    if i not in url6:
        url6.append(i)

In [101]:
len(url6)

877

In [103]:
brand5=[]
model5=[]
variant5=[]
manufacturingyear5=[]
driverkilometers5=[]
fuel5=[]
owners5=[]
location5=[]
price5=[]



for i in url6:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br5=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand5.append(br5.text)
    except NoSuchElementException:
        brand5.append('-')

#Model        
    try:
        mo5=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model5.append(mo5.text)
    except NoSuchElementException:
        model5.append('-')
        
#Variant
    try:
        var5=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant5.append(var5.text)
    except NoSuchElementException:
        variant5.append('-')

#Manufacturingyear
    try:
        yr5=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear5.append(yr5.text)
    except NoSuchElementException:
        manufacturingyear5.append('-')

#Kilometers Driven
    try:
        dr5=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers5.append(dr5.text)
    except NoSuchElementException:
        driverkilometers5.append('-')
        
#Fuel
    try:
        fl5=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel5.append(fl5.text)
    except NoSuchElementException:
        fuel5.append('-')

#no of owners
    try:
        own5=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners5.append(own5.text)
    except NoSuchElementException:
        owners5.append('-')
        
#location
    try:
        loc5=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location5.append(loc5.text)
    except NoSuchElementException:
        location5.append('-')
        
#Price
    try:
        pr5=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price5.append(pr5.text)
    except NoSuchElementException:
        price5.append('-')




brand5 = pd.DataFrame(brand5)            
brand5.columns=['brand']

model5 = pd.DataFrame(model5)            
model5.columns=['model']

variant5 = pd.DataFrame(variant5)            
variant5.columns=['variant']

manufacturingyear5 = pd.DataFrame(manufacturingyear5)            
manufacturingyear5.columns=['manufacturingyear']

driverkilometers5 = pd.DataFrame(driverkilometers5)            
driverkilometers5.columns=['driverkilometers']

fuel5 = pd.DataFrame(fuel5)            
fuel5.columns=['fuel']

owners5 = pd.DataFrame(owners5)            
owners5.columns=['owners']

location5 = pd.DataFrame(location5)            
location5.columns=['location']

price5 = pd.DataFrame(price5)            
price5.columns=['price']



car5=pd.DataFrame({})
car5['Brand']=brand5['brand']
car5['Model']=model5['model']
car5['Variant']=variant5['variant']
car5['Manufacturig year']=manufacturingyear5['manufacturingyear']
car5['Kilometers driven']=driverkilometers5['driverkilometers']
car5['Fuel']=fuel5['fuel']
car5['No of Owners']=owners5['owners']
car5['Location']=location5['location']
car5['Price']=price5['price']
car5
#Hyderabad

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Corolla Altis,Altis J,2009,"51,000 km",Petrol,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 3,25,000"
1,Mahindra,XUV500,2011-2015 W8-2WD,2012,"99,000 km",Diesel,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 5,75,000"
2,Maruti Suzuki,Celerio,VXI MT,2014,"49,000 km",Petrol,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 3,25,000"
3,Hyundai,Santro,-,2000,"81,000 km",Petrol,2nd,"Doverlim, Davorlim, Goa","₹ 65,000"
4,Maruti Suzuki,Esteem,Lxi - BSIII,2006,"53,000 km",Petrol,2nd,"Doverlim, Davorlim, Goa","₹ 70,000"
...,...,...,...,...,...,...,...,...,...
872,Mahindra,XUV500,2011-2015 W8 4WD,2014,"98,000 km",Diesel,2nd,"Navelcar Hill City, Old Goa, Goa","₹ 6,50,000"
873,Mahindra,Jeep,Others,2006,100 km,Diesel,2nd,"Maina, Goa Velha, Goa","₹ 3,96,000"
874,Hyundai,Xcent,SX 1.2,2016,"20,000 km",Petrol,1st,"AND Chikalim, Vasco Da Gama, Goa","₹ 5,50,000"
875,Tata,Winger,Deluxe - Flat Roof (AC),2012,"1,900 km",Diesel,1st,"Velha Goa, Old Goa, Goa","₹ 2,50,000"
876,Hyundai,Verna,2016-2017 1.6 VTVT SX Option,2016,"43,288 km",Petrol,1st,"Velha Goa, Old Goa, Goa","₹ 7,50,000"

In [104]:
car5.to_csv (r'C:\Users\allen\car5.csv', index = False, header=True)

In [105]:
car5.drop(car5.loc[car5['Brand']=='-'].index, inplace=True)

In [106]:
car5

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Corolla Altis,Altis J,2009,"51,000 km",Petrol,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 3,25,000"
1,Mahindra,XUV500,2011-2015 W8-2WD,2012,"99,000 km",Diesel,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 5,75,000"
2,Maruti Suzuki,Celerio,VXI MT,2014,"49,000 km",Petrol,1st,"Vidya Nagar, Vasco Da Gama, Goa","₹ 3,25,000"
3,Hyundai,Santro,-,2000,"81,000 km",Petrol,2nd,"Doverlim, Davorlim, Goa","₹ 65,000"
4,Maruti Suzuki,Esteem,Lxi - BSIII,2006,"53,000 km",Petrol,2nd,"Doverlim, Davorlim, Goa","₹ 70,000"
...,...,...,...,...,...,...,...,...,...
872,Mahindra,XUV500,2011-2015 W8 4WD,2014,"98,000 km",Diesel,2nd,"Navelcar Hill City, Old Goa, Goa","₹ 6,50,000"
873,Mahindra,Jeep,Others,2006,100 km,Diesel,2nd,"Maina, Goa Velha, Goa","₹ 3,96,000"
874,Hyundai,Xcent,SX 1.2,2016,"20,000 km",Petrol,1st,"AND Chikalim, Vasco Da Gama, Goa","₹ 5,50,000"
875,Tata,Winger,Deluxe - Flat Roof (AC),2012,"1,900 km",Diesel,1st,"Velha Goa, Old Goa, Goa","₹ 2,50,000"
876,Hyundai,Verna,2016-2017 1.6 VTVT SX Option,2016,"43,288 km",Petrol,1st,"Velha Goa, Old Goa, Goa","₹ 7,50,000"

In [107]:
driver=webdriver.Chrome("chromedriver.exe")

In [108]:
url='https://www.olx.in/bangalore-airport-area_g5313775/q-cars'
driver.get(url)

In [110]:
for i in range(0,29):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [111]:
producturlb1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlb1.append(j.get_attribute('href'))

In [113]:
len(producturlb1)

560

In [114]:
url='https://www.olx.in/mysore_g5316122/q-cars'
driver.get(url)

In [117]:
for i in range(0,25):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [118]:
producturlb2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturlb2.append(j.get_attribute('href'))

In [119]:
len(producturlb2)

540

In [120]:
for i in producturlb2 :
    producturlb1.append(i)

In [121]:
len(producturlb1)

1100

In [122]:
url7 = []
for i in producturlb1:
    if i not in url7:
        url7.append(i)

In [123]:
len(url7)

1074

In [124]:
brand6=[]
model6=[]
variant6=[]
manufacturingyear6=[]
driverkilometers6=[]
fuel6=[]
owners6=[]
location6=[]
price6=[]



for i in url7:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br6=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand6.append(br6.text)
    except NoSuchElementException:
        brand6.append('-')

#Model        
    try:
        mo6=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model6.append(mo6.text)
    except NoSuchElementException:
        model6.append('-')
        
#Variant
    try:
        var6=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant6.append(var6.text)
    except NoSuchElementException:
        variant6.append('-')

#Manufacturingyear
    try:
        yr6=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear6.append(yr6.text)
    except NoSuchElementException:
        manufacturingyear6.append('-')

#Kilometers Driven
    try:
        dr6=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers6.append(dr6.text)
    except NoSuchElementException:
        driverkilometers6.append('-')
        
#Fuel
    try:
        fl6=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel6.append(fl6.text)
    except NoSuchElementException:
        fuel6.append('-')

#no of owners
    try:
        own6=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners6.append(own6.text)
    except NoSuchElementException:
        owners6.append('-')
        
#location
    try:
        loc6=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location6.append(loc6.text)
    except NoSuchElementException:
        location6.append('-')
        
#Price
    try:
        pr6=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price6.append(pr6.text)
    except NoSuchElementException:
        price6.append('-')




brand6 = pd.DataFrame(brand6)            
brand6.columns=['brand']

model6 = pd.DataFrame(model6)            
model6.columns=['model']

variant6 = pd.DataFrame(variant6)            
variant6.columns=['variant']

manufacturingyear6 = pd.DataFrame(manufacturingyear6)            
manufacturingyear6.columns=['manufacturingyear']

driverkilometers6 = pd.DataFrame(driverkilometers6)            
driverkilometers6.columns=['driverkilometers']

fuel6 = pd.DataFrame(fuel6)            
fuel6.columns=['fuel']

owners6 = pd.DataFrame(owners6)            
owners6.columns=['owners']

location6 = pd.DataFrame(location6)            
location6.columns=['location']

price6 = pd.DataFrame(price6)            
price6.columns=['price']



car6=pd.DataFrame({})
car6['Brand']=brand6['brand']
car6['Model']=model6['model']
car6['Variant']=variant6['variant']
car6['Manufacturig year']=manufacturingyear6['manufacturingyear']
car6['Kilometers driven']=driverkilometers6['driverkilometers']
car6['Fuel']=fuel6['fuel']
car6['No of Owners']=owners6['owners']
car6['Location']=location6['location']
car6['Price']=price6['price']
car6
#karnataka (bangalore and mysore)

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Mercedes-Benz,GLA,45 AMG,2018,"14,771 km",Petrol,1st,"Shinivagalu Tank Bed Layout, Bengaluru, Karnataka","₹ 52,00,000"
1,Volvo,XC60,D5 Summum,2013,"131,305 km",Diesel,2nd,"Shinivagalu Tank Bed Layout, Bengaluru, Karnataka","₹ 13,75,000"
2,Skoda,Fabia,2010-2015 1.2 MPI Elegance,2011,"54,000 km",Petrol,1st,"Amar Jyoti Layout, Bengaluru, Karnataka","₹ 3,75,000"
3,-,-,-,-,-,-,-,-,-
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
1069,Honda,Jazz,-,2016,"74,471 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 5,70,000"
1070,Tata,Tiago,-,2016,"93,764 km",Diesel,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,80,000"
1071,Maruti Suzuki,Wagon R,VXI,2016,"47,119 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,20,000"
1072,Volkswagen,Vento,-,2014,"94,692 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,65,000"
1073,Maruti Suzuki,Gypsy,King Hard Top BSII,1986,"47,000 km",Diesel,4+,"Vijayanagar, Mysuru, Karnataka","₹ 2,95,000"

In [125]:
car6.to_csv (r'C:\Users\allen\car6.csv', index = False, header=True)

In [126]:
car6.drop(car6.loc[car6['Brand']=='-'].index, inplace=True)

In [127]:
car6

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Mercedes-Benz,GLA,45 AMG,2018,"14,771 km",Petrol,1st,"Shinivagalu Tank Bed Layout, Bengaluru, Karnataka","₹ 52,00,000"
1,Volvo,XC60,D5 Summum,2013,"131,305 km",Diesel,2nd,"Shinivagalu Tank Bed Layout, Bengaluru, Karnataka","₹ 13,75,000"
2,Skoda,Fabia,2010-2015 1.2 MPI Elegance,2011,"54,000 km",Petrol,1st,"Amar Jyoti Layout, Bengaluru, Karnataka","₹ 3,75,000"
5,Skoda,Rapid,Others,2020,"5,600 km",Petrol,1st,"Sarjapur Road, Bengaluru, Karnataka","₹ 9,90,000"
6,Hyundai,i10,Magna,2008,"95,000 km",Petrol,3rd,"Bangalore Airport Area, Bengaluru, Karnataka","₹ 2,45,000"
...,...,...,...,...,...,...,...,...,...
1069,Honda,Jazz,-,2016,"74,471 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 5,70,000"
1070,Tata,Tiago,-,2016,"93,764 km",Diesel,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,80,000"
1071,Maruti Suzuki,Wagon R,VXI,2016,"47,119 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,20,000"
1072,Volkswagen,Vento,-,2014,"94,692 km",Petrol,-,"Shankar Linga Badawane, Mysuru, Karnataka","₹ 4,65,000"
1073,Maruti Suzuki,Gypsy,King Hard Top BSII,1986,"47,000 km",Diesel,4+,"Vijayanagar, Mysuru, Karnataka","₹ 2,95,000"

In [128]:
driver=webdriver.Chrome("chromedriver.exe")

In [129]:
url='https://www.olx.in/delhi-gate_g5340620/q-cars?isSearchCall=true'
driver.get(url)

In [131]:
for i in range(0,32):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [132]:
producturld1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturld1.append(j.get_attribute('href'))

In [134]:
len(producturld1)

637

In [135]:
url='https://www.olx.in/chirag-delhi_g5327939/q-cars'
driver.get(url)

In [137]:
for i in range(0,28):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [138]:
producturld2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturld2.append(j.get_attribute('href'))

In [139]:
len(producturld2)

500

In [140]:
for i in producturld2 :
    producturld1.append(i)

In [142]:
len(producturld1)

1137

In [143]:
url8 = []
for i in producturld1:
    if i not in url8:
        url8.append(i)

In [144]:
len(url8)

1114

In [145]:
brand7=[]
model7=[]
variant7=[]
manufacturingyear7=[]
driverkilometers7=[]
fuel7=[]
owners7=[]
location7=[]
price7=[]



for i in url8:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br7=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand7.append(br7.text)
    except NoSuchElementException:
        brand7.append('-')

#Model        
    try:
        mo7=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model7.append(mo7.text)
    except NoSuchElementException:
        model7.append('-')
        
#Variant
    try:
        var7=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant7.append(var7.text)
    except NoSuchElementException:
        variant7.append('-')

#Manufacturingyear
    try:
        yr7=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear7.append(yr7.text)
    except NoSuchElementException:
        manufacturingyear7.append('-')

#Kilometers Driven
    try:
        dr7=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers7.append(dr7.text)
    except NoSuchElementException:
        driverkilometers7.append('-')
        
#Fuel
    try:
        fl7=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel7.append(fl7.text)
    except NoSuchElementException:
        fuel7.append('-')

#no of owners
    try:
        own7=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners7.append(own7.text)
    except NoSuchElementException:
        owners7.append('-')
        
#location
    try:
        loc7=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location7.append(loc7.text)
    except NoSuchElementException:
        location7.append('-')
        
#Price
    try:
        pr7=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price7.append(pr7.text)
    except NoSuchElementException:
        price7.append('-')




brand7 = pd.DataFrame(brand7)            
brand7.columns=['brand']

model7 = pd.DataFrame(model7)            
model7.columns=['model']

variant7 = pd.DataFrame(variant7)            
variant7.columns=['variant']

manufacturingyear7 = pd.DataFrame(manufacturingyear7)            
manufacturingyear7.columns=['manufacturingyear']

driverkilometers7 = pd.DataFrame(driverkilometers7)            
driverkilometers7.columns=['driverkilometers']

fuel7 = pd.DataFrame(fuel7)            
fuel7.columns=['fuel']

owners7 = pd.DataFrame(owners7)            
owners7.columns=['owners']

location7 = pd.DataFrame(location7)            
location7.columns=['location']

price7 = pd.DataFrame(price7)            
price7.columns=['price']



car7=pd.DataFrame({})
car7['Brand']=brand7['brand']
car7['Model']=model7['model']
car7['Variant']=variant7['variant']
car7['Manufacturig year']=manufacturingyear7['manufacturingyear']
car7['Kilometers driven']=driverkilometers7['driverkilometers']
car7['Fuel']=fuel7['fuel']
car7['No of Owners']=owners7['owners']
car7['Location']=location7['location']
car7['Price']=price7['price']
car7
#delhi

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Ford,Ecosport,1.5 TDCi Trend,2016,"51,000 km",Diesel,1st,"New Arya Nagar, Ghaziabad, Uttar Pradesh","₹ 5,75,000"
1,Honda,Others,-,2016,"65,000 km",CNG & Hybrids,1st,"Kavi Nagar, Ghaziabad, Uttar Pradesh","₹ 3,65,000"
2,Maruti Suzuki,Celerio,2014-2017 VXI AT,2015,"62,000 km",Petrol,1st,"Ravidas Nagar, Ghaziabad, Uttar Pradesh","₹ 3,40,000"
3,-,-,-,-,-,-,-,-,-
4,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...
1109,Mahindra,XUV500,W8 2WD,2013,"66,000 km",Diesel,1st,"Lajpat Nagar 2, Delhi, Delhi","₹ 6,15,000"
1110,Honda,Brio,2011-2013 S MT,2013.0,"72,000 km",Petrol,1st,"Lajpat Nagar 1, Delhi, Delhi","₹ 2,95,000"
1111,Jaguar,XE,2.0L Diesel Prestige,2019,"20,000 km",Diesel,1st,"South Extension, Delhi, Delhi","₹ 33,85,000"
1112,Toyota,Camry,2.5 Hybrid,2018,"51,000 km",Petrol,1st,"South Extension, Delhi, Delhi","₹ 27,49,000"
1113,Toyota,Corolla Altis,1.8 G,2009,"70,200 km",Petrol,2nd,"Lajpat Nagar 2, Delhi, Delhi","₹ 2,85,000"

In [146]:
car7.to_csv (r'C:\Users\allen\car7.csv', index = False, header=True)

In [198]:
car7.drop(car7.loc[car7['Brand']=='-'].index, inplace=True)

In [199]:
car7

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Ford,Ecosport,1.5 TDCi Trend,2016,"51,000 km",Diesel,1st,"New Arya Nagar, Ghaziabad, Uttar Pradesh","₹ 5,75,000"
1,Honda,Others,-,2016,"65,000 km",CNG & Hybrids,1st,"Kavi Nagar, Ghaziabad, Uttar Pradesh","₹ 3,65,000"
2,Maruti Suzuki,Celerio,2014-2017 VXI AT,2015,"62,000 km",Petrol,1st,"Ravidas Nagar, Ghaziabad, Uttar Pradesh","₹ 3,40,000"
5,Honda,City,i-VTEC VX,2016,"58,555 km",Petrol,1st,"Lohia Nagar, Ghaziabad, Uttar Pradesh","₹ 6,82,000"
6,Maruti Suzuki,Wagon R,VXI 1.2,2018,"57,654 km",Petrol,1st,"Lohia Nagar, Ghaziabad, Uttar Pradesh","₹ 3,73,000"
...,...,...,...,...,...,...,...,...,...
1109,Mahindra,XUV500,W8 2WD,2013,"66,000 km",Diesel,1st,"Lajpat Nagar 2, Delhi, Delhi","₹ 6,15,000"
1110,Honda,Brio,2011-2013 S MT,2013.0,"72,000 km",Petrol,1st,"Lajpat Nagar 1, Delhi, Delhi","₹ 2,95,000"
1111,Jaguar,XE,2.0L Diesel Prestige,2019,"20,000 km",Diesel,1st,"South Extension, Delhi, Delhi","₹ 33,85,000"
1112,Toyota,Camry,2.5 Hybrid,2018,"51,000 km",Petrol,1st,"South Extension, Delhi, Delhi","₹ 27,49,000"
1113,Toyota,Corolla Altis,1.8 G,2009,"70,200 km",Petrol,2nd,"Lajpat Nagar 2, Delhi, Delhi","₹ 2,85,000"

In [147]:
driver=webdriver.Chrome("chromedriver.exe")

In [148]:
url='https://www.olx.in/mdda-dehradun_g5343880/q-cars'
driver.get(url)

In [151]:
for i in range(0,25):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [152]:
producturln1=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturln1.append(j.get_attribute('href'))

In [153]:
len(producturln1)

504

In [154]:
url='https://www.olx.in/ahmedabad_g4058677/q-cars'
driver.get(url)

In [183]:
for i in range(0,30):
    driver.find_element_by_xpath("//button[@data-aut-id='btnLoadMore']").click()
    sleep(3)

In [181]:
producturln2=[]
for j in driver.find_elements_by_xpath("//li[@data-aut-id='itemBox']/a"):
            producturln2.append(j.get_attribute('href'))

In [182]:
len(producturln2)

511

In [184]:
for i in producturln2 :
    producturln1.append(i)

In [185]:
len(producturln1)

1015

In [186]:
url9 = []
for i in producturln1:
    if i not in url9:
        url9.append(i)

In [187]:
len(url9)

988

In [188]:
brand8=[]
model8=[]
variant8=[]
manufacturingyear8=[]
driverkilometers8=[]
fuel8=[]
owners8=[]
location8=[]
price8=[]



for i in url9:
    driver.get(i)
    sleep(6)
    

#Brand   
    try:
        br8=driver.find_element_by_xpath("//span[@data-aut-id='value_make']")
        brand8.append(br8.text)
    except NoSuchElementException:
        brand8.append('-')

#Model        
    try:
        mo8=driver.find_element_by_xpath("//span[@data-aut-id='value_model']")
        model8.append(mo8.text)
    except NoSuchElementException:
        model8.append('-')
        
#Variant
    try:
        var8=driver.find_element_by_xpath("//span[@data-aut-id='value_variant']")
        variant8.append(var8.text)
    except NoSuchElementException:
        variant8.append('-')

#Manufacturingyear
    try:
        yr8=driver.find_element_by_xpath("//span[@data-aut-id='value_year']")
        manufacturingyear8.append(yr8.text)
    except NoSuchElementException:
        manufacturingyear8.append('-')

#Kilometers Driven
    try:
        dr8=driver.find_element_by_xpath("//span[@data-aut-id='value_mileage']")
        driverkilometers8.append(dr8.text)
    except NoSuchElementException:
        driverkilometers8.append('-')
        
#Fuel
    try:
        fl8=driver.find_element_by_xpath("//span[@data-aut-id='value_petrol']")
        fuel8.append(fl8.text)
    except NoSuchElementException:
        fuel8.append('-')

#no of owners
    try:
        own8=driver.find_element_by_xpath("//span[@data-aut-id='value_first_owner']")
        owners8.append(own8.text)
    except NoSuchElementException:
        owners8.append('-')
        
#location
    try:
        loc8=driver.find_element_by_xpath("//div[@data-aut-id='itemLocation']")
        location8.append(loc8.text)
    except NoSuchElementException:
        location8.append('-')
        
#Price
    try:
        pr8=driver.find_element_by_xpath("//span[@class='_2xKfz']")
        price8.append(pr8.text)
    except NoSuchElementException:
        price8.append('-')




brand8 = pd.DataFrame(brand8)            
brand8.columns=['brand']

model8 = pd.DataFrame(model8)            
model8.columns=['model']

variant8 = pd.DataFrame(variant8)            
variant8.columns=['variant']

manufacturingyear8 = pd.DataFrame(manufacturingyear8)            
manufacturingyear8.columns=['manufacturingyear']

driverkilometers8 = pd.DataFrame(driverkilometers8)            
driverkilometers8.columns=['driverkilometers']

fuel8 = pd.DataFrame(fuel8)            
fuel8.columns=['fuel']

owners8 = pd.DataFrame(owners8)            
owners8.columns=['owners']

location8 = pd.DataFrame(location8)            
location8.columns=['location']

price8 = pd.DataFrame(price8)            
price8.columns=['price']



car8=pd.DataFrame({})
car8['Brand']=brand8['brand']
car8['Model']=model8['model']
car8['Variant']=variant8['variant']
car8['Manufacturig year']=manufacturingyear8['manufacturingyear']
car8['Kilometers driven']=driverkilometers8['driverkilometers']
car8['Fuel']=fuel8['fuel']
car8['No of Owners']=owners8['owners']
car8['Location']=location8['location']
car8['Price']=price8['price']
car8
#ahemabad and dehradun

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Fortuner,3.0 4x4 Manual,2012,"96,000 km",Diesel,3rd,"Pnb Enclave, Dehradun, Uttaranchal","₹ 12,25,000"
1,Mercedes-Benz,GLA,Others,2015,"56,000 km",Diesel,-,"Pnb Enclave, Dehradun, Uttaranchal","₹ 19,25,000"
2,Maruti Suzuki,Swift,LXI,2005,"80,000 km",Petrol,4+,"Kunjapuri Vihar, Dehradun, Uttaranchal","₹ 1,25,000"
3,Hyundai,i20,1.4 Sportz,2011,"62,000 km",Petrol,3rd,"Ankitpuram, Dehradun, Uttaranchal","₹ 2,50,000"
4,BMW,3 Series,320i Luxury Line,2013,"80,000 km",Diesel,2nd,"Matawala Bagh, Dehradun, Uttaranchal","₹ 10,00,000"
...,...,...,...,...,...,...,...,...,...
983,-,-,-,-,-,-,-,-,-
984,-,-,-,-,-,-,-,-,-
985,-,-,-,-,-,-,-,-,-
986,-,-,-,-,-,-,-,-,-
987,-,-,-,-,-,-,-,-,-

In [197]:
car8.to_csv (r'C:\Users\allen\car8.csv', index = False, header=True)

In [200]:
car8.drop(car8.loc[car8['Brand']=='-'].index, inplace=True)

In [201]:
car8

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Fortuner,3.0 4x4 Manual,2012,"96,000 km",Diesel,3rd,"Pnb Enclave, Dehradun, Uttaranchal","₹ 12,25,000"
1,Mercedes-Benz,GLA,Others,2015,"56,000 km",Diesel,-,"Pnb Enclave, Dehradun, Uttaranchal","₹ 19,25,000"
2,Maruti Suzuki,Swift,LXI,2005,"80,000 km",Petrol,4+,"Kunjapuri Vihar, Dehradun, Uttaranchal","₹ 1,25,000"
3,Hyundai,i20,1.4 Sportz,2011,"62,000 km",Petrol,3rd,"Ankitpuram, Dehradun, Uttaranchal","₹ 2,50,000"
4,BMW,3 Series,320i Luxury Line,2013,"80,000 km",Diesel,2nd,"Matawala Bagh, Dehradun, Uttaranchal","₹ 10,00,000"
...,...,...,...,...,...,...,...,...,...
978,Maruti Suzuki,Ciaz,ZDI BS IV,2015,"64,000 km",Diesel,1st,"Shahibag, Ahmedabad, Gujarat","₹ 5,50,000"
979,Honda,City,i-VTEC S,2010,"77,000 km",Petrol,2nd,"Pragati Nagar, Ahmedabad, Gujarat","₹ 3,80,000"
980,Hyundai,Grand i10,1.2 Kappa Magna,2017,"67,000 km",Petrol,1st,"Pragati Nagar, Ahmedabad, Gujarat","₹ 4,80,000"
981,Maruti Suzuki,Ciaz,Delta Automatic,2017,"30,000 km",Petrol,1st,"Sunder Nagar, Ahmedabad, Gujarat","₹ 7,75,000"
982,Maruti Suzuki,Eeco,5 STR With AC Plus HTR CNG,2016,"45,000 km",CNG & Hybrids,2nd,"132 Feet Ring Road, Ahmedabad, Gujarat","₹ 3,85,000"

In [274]:
len(car1)+len(car2)+len(car3)+len(car4)+len(car5)+len(car6)+len(car7)+len(car8)

6407

In [275]:
df=(pd.concat([car1,car2,car3,car4,car5,car6,car7,car8]))

In [263]:
len(df)

6407

In [277]:
df.head(10)

,Brand,Model,Variant,Manufacturig year,Kilometers driven,Fuel,No of Owners,Location,Price
0,Toyota,Innova Crysta,2.4 V,2017,"53,000 km",Diesel,2nd,"Puthanathani, Malappuram, Kerala","₹ 18,50,000"
1,Tata,Zest,-,2016,"60,000 km",Diesel,1st,"Ambattukavu, Kochi, Kerala","₹ 3,75,000"
2,Honda,City,-,1998,"86,000 km",Petrol,3rd,"Kowdiar, Thiruvananthapuram, Kerala","₹ 1,35,000"
3,-,-,-,-,-,-,-,-,-
4,BMW,5 Series,520d Luxury Line,2011,"140,000 km",Diesel,1st,"Koduvally, Kozhikode, Kerala","₹ 10,45,000"
5,Renault,KWID,Climber 1.0 MT Opt,2018,"13,000 km",Petrol,1st,"Kazhakoottam, Thiruvananthapuram, Kerala","₹ 3,70,000"
6,Renault,KWID,1.0 RXT AMT Opt,2017,"23,000 km",Petrol,1st,"Kazhakoottam, Thiruvananthapuram, Kerala","₹ 3,80,000"
7,Ford,Ikon,1.4 TDCi DuraTorq,2010,"99,000 km",Diesel,1st,"Kazhakoottam, Thiruvananthapuram, Kerala","₹ 1,09,000"
8,Hyundai,i10,1.2 Kappa Magna,2013,"36,000 km",Petrol,1st,"Kazhakoottam, Thiruvananthapuram, Kerala","₹ 2,85,000"
9,Maruti Suzuki,Celerio,VXI AMT,2014,"51,000 km",Petrol,1st,"Kazhakoottam, Thiruvananthapuram, Kerala","₹ 3,80,000"

In [246]:
df.to_csv (r'C:\Users\allen\dfcar.csv', index = False, header=True)